### ISSUE TITLE
Mac Issues

### ISSUE THREAD

**Issue by charlescrammond** [sebastien-bouffier/Bidoo#1]
Hello, thank you for the plugin!
I tried to compile on Mac High Sierra.
First, an error with make, which was resolved by deleting the /build directory. 
Then the following error

```
c/DTROY.cpp:182:65: error: no member named 'round' in namespace 'std'; did you
      mean 'roundl'?
  ...+ i].value = static_cast<int>(std::round(randomf()*7))
```

which was resolved by adding

#include "cmath" to the top of Bidoo.hpp

The switches only move up! I can't drag them down.
No matter! 
Excellent work, thanks for sharing.

I've put a working mac build here https://github.com/charlescrammond/Bidoo/raw/master/src/Bidoo_040_Mac_1stNov2017.zip

**Comment by sebastien-bouffier** [comment]
Hello Charles, thanks for your help. Antonio aka "Autodafe" (http://www.switchedonrack.com) raised the same issue on MAC and proposed the same fix. I will change it in my next commit. 
Yes I have to find out how to make the switches bidirectional ... but before I have to fix the randomize issue ... controls don't reflect the real value of the parameters and it is just very annoying :)

**Comment by chrisbeckstrom** [comment]
Had a similar issue on linux, and solved it by replacing `std::round` with `round` the two times it appears in `DSTROY.cpp`. Sequencer works great, I love it! Excellent work

**Comment by sebastien-bouffier** [comment]
Hi Chris, thanks for your help and encouragements. Big up for your hyper-custom-modular-system !!!

**Comment by sebastien-bouffier** [comment]
Random step management redesigned. This should be fixed.
