### ISSUE TITLE
Trying to compile for 0.4.0

### ISSUE THREAD

**Issue by Cordoha** [sebastien-bouffier/Bidoo#10]
Trying to compile Bidoo in 0.4.0 from source. Make outputs: 
build/src/Bidoo.cpp.d:1: *** multiple target patterns.  Stop.

Just trying to get all the plugins compiled before 0.5.0 is released so I have a solid working Rack with mostly all plugins working before the big turnover.

**Comment by nay-seven** [comment]
Sorry, can't help, but good idea ! , hope you'll succeed ;-)

**Comment by sebastien-bouffier** [comment]
Hello Cordoha & Nay, please confirm my understanding, you try to build the entire package on Rack 0.4.0 ? It is possible but it requires "some" work to downgrade. dTrOY release is still available for 0.4.0 and it was the sole plugin running on 0.4 so your patches should still work. No ?

**Comment by nay-seven** [comment]
Ha, so ok for me i've dTrOY working , thinking the others works also on 0.4.0. Nevermind, 0.5 is here, hope a Mac release soon  ;-)

**Comment by sebastien-bouffier** [comment]
I have been asked to downgrade the pack by many people since 10 days but Andrew told me that the ETA of 0.5 was so close that it shouldn't be worth the effort. I will ask Autodafe to do the build on mac if he can.
