### ISSUE TITLE
Curt seg fault when changing buffer size

### ISSUE THREAD

**Issue by Coirt** [sebastien-bouffier/Bidoo#103]
OS (if applicable): win7
Version (or "dev" if compiling from source): v1.0.0

Wish I found this sooner.

Got a seg fault when changing the buffer size on Curt. Also freezes rack when connected directly to the audio device with nothing else in the project. Seems to freeze the audio engine sometimes controls respond but only after you change another modules parameters.

not much to go on with a back trace.
```
[New Thread 6524.0xecc]
[New Thread 6524.0x2454]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000001d14b7160 in ?? ()
(gdb) bt
#0  0x00000001d14b7160 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

```

**Comment by Coirt** [comment]
Probably best to comment out `addParam(createParam<BidooBlueSnapTrimpot>(Vec(2, 205), module, CURT::BUFF_SIZE_PARAM));` ? Can't seem to find what the problem is.

**Comment by sebastien-bouffier** [comment]
Hi, this plugin is an attempt to use the psola approach for pitch shifting. I noticed the issues you raised. So I have removed those params and once I understand what is going wrong I will release a stable version.
Cheers.

**Comment by Coirt** [comment]
It is just the buffersize param that causes the issue, everything else is fine.

**Comment by sebastien-bouffier** [comment]
cuRt is working better in the last commit. It still needs improvements especially the gain increase when bins are more overlapped.

**Comment by Coirt** [comment]
No more crash :+1:
