### ISSUE TITLE
N'apparait pas dans Rack

### ISSUE THREAD

**Issue by caecos** [sebastien-bouffier/Bidoo#105]
J'ai compilé les sources du 27 juin et les modules apparaissent dans Rack. Mais avec les derniers sources en date, la compilation se fait sans anicroches mais rien n'apparait dans Rack...

Le tout sous Windows 10 Pro...

**Comment by sebastien-bouffier** [comment]
Bonjour, il y a encore des pb de compilation sous Mac Os. N'ayant plus de mac je ne peux pas vérifier ce point. Le pack sera dispo sous peu on itère sur ce point avec la team migration.

**Comment by caecos** [comment]
Pour ma part les problèmes sont sous Windows, les sources compilent correctement mais Rack ne les voit pas!? Cependant, les sources du 27 juin compilent et Rack les voit.

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : bidoo <notifications@github.com>
Envoyé : Friday, July 5, 2019 1:42:09 PM
À : sebastien-bouffier/Bidoo
Cc : caecos; Author
Objet : Re: [sebastien-bouffier/Bidoo] N'apparait pas dans Rack (#105)


Bonjour, il y a encore des pb de compilation sous Mac Os. N'ayant plus de mac je ne peux pas vérifier ce point. Le pack sera dispo sous peu on itère sur ce point avec la team migration.

**Comment by sebastien-bouffier** [comment]
Ok désolé j'ai mal compris votre premier post. Je check

**Comment by sebastien-bouffier** [comment]
Je ne trouve pas. Je bosse sous W10 et pas de pb. Est-ce que vous pourriez me dire à partir de quel commit le pb apparait svp ? Ou peut être faire tourner rack en debug et voir si il y a un message de pb de slug. Pour ça il faut faire non pas un `make run` mais un `make debug` qui lui lance gdb puis un `run` sous gdb.

**Comment by caecos** [comment]
Il s’agit des commits à compter du 28 juin incluant celle d’hier (5 juillet)... comme je l’écrivais, la commit du 27 juin tourne bien. Je compile à partir du SDK... je réessaye ce soir en revenant du travail avec la fonction debug...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : bidoo <notifications@github.com>
Envoyé : Saturday, July 6, 2019 2:17:34 PM
À : sebastien-bouffier/Bidoo
Cc : caecos; Author
Objet : Re: [sebastien-bouffier/Bidoo] N'apparait pas dans Rack (#105)


Je ne trouve pas. Je bosse sous W10 et pas de pb. Est-ce que vous pourriez me dire à partir de quel commit le pb apparait svp ? Ou peut être faire tourner rack en debug et voir si il y a un message de pb de slug. Pour ça il faut faire non pas un make run mais un make debug qui lui lance gdb puis un run sous gdb.

**Comment by z-plane** [comment]
> Bonjour, il y a encore des pb de compilation sous Mac Os. N'ayant plus de mac je ne peux pas vérifier ce point. Le pack sera dispo sous peu on itère sur ce point avec la team migration.

Si tu cherche quelqu'un sur mac, je peut essayer de faire la compilation. j'ai pas d'experience avec xcode, mais je pense que je peut suivre les instructions! ca parait pas trop compliquer XD

**Comment by sebastien-bouffier** [comment]
Salut @z-plane. Merci pour ta propal d'aide. Je crois qu'on a réussi à mettre le code d'aplomb pour la compilation sous osx avec l'aide de @cschol. Je ne sais pas si tu hésites à mettre les mains dans le cambouis mais je ne peux que t'encourager à essayer de te faire un env pour bidouiller les modules rack car le framework est vraiment plus simple que du vst ou autre. Si jamais je coince encore sous osx je n'hésiterais pas à te demander. Musicalement.

**Comment by caecos** [comment]
Je vais tenter de voir ce qui cloche avec Windows et pourquoi tout compile bien mais que Rack ne voit pas le plugin...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : bidoo <notifications@github.com>
Envoyé : Sunday, July 7, 2019 7:25:19 AM
À : sebastien-bouffier/Bidoo
Cc : caecos; Author
Objet : Re: [sebastien-bouffier/Bidoo] N'apparait pas dans Rack (#105)


Salut @z-plane<https://github.com/z-plane>. Merci pour ta propal d'aide. Je crois qu'on a réussi à mettre le code d'aplomb pour la compilation sous osx avec l'aide de @cschol<https://github.com/cschol>. Je ne sais pas si tu hésites à mettre les mains dans le cambouis mais je ne peux que t'encourager à essayer de te faire un env pour bidouiller les modules rack car le framework est vraiment plus simple que du vst ou autre. Si jamais je coince encore sous osx je n'hésiterais pas à te demander. Musicalement.

**Comment by sebastien-bouffier** [comment]
Salut, je suis en train re rebuild tout rack from scratch pour tenter de trouver d'où que ça vient :) .
Je viens aussi de recevoir un mail d'Andrew, mes modules sont dispo sur la plateforme vcv directement. J'espère que tu pourras les récupérer via le gestionnaire de modules et qu'ils fonctionneront chez toi.

**Comment by caecos** [comment]
J’essaie ça dans quelques heures et je t’en redonne des nouvelles. Merci!

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : bidoo <notifications@github.com>
Envoyé : Sunday, July 7, 2019 12:39:58 PM
À : sebastien-bouffier/Bidoo
Cc : caecos; Author
Objet : Re: [sebastien-bouffier/Bidoo] N'apparait pas dans Rack (#105)


Salut, je suis en train re rebuild tout rack from scratch pour tenter de trouver d'où que ça vient :) .
Je viens aussi de recevoir un mail d'Andrew, mes modules sont dispo sur la plateforme vcv directement. J'espère que tu pourras les récupérer via le gestionnaire de modules et qu'ils fonctionneront chez toi.

**Comment by caecos** [comment]
OK la dernière version des commits fonctionne a merveille...merci pour ta générosité...
