### ISSUE TITLE
BaR compressor v1: very loud noise and output error

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#106]
OS (if applicable): WIN 10
Version (or "dev" if compiling from source): V1

Hi, i get a very loud distorted output just by turning the Treshold button to the left. 
If you need any more info let me know.

**Comment by Coirt** [comment]
Question not related to the compressor issue. Do you have all the modules in win10? should be 35.

**Comment by Eurikon** [comment]
> 
> 
> Question not related to the compressor issue. Do you have all the modules in win10? should be 35.

yes 35

**Comment by Coirt** [comment]
Okay cheers. On the compressor issue what are parameters set to?

**Comment by Eurikon** [comment]
> 
> 
> Okay cheers. On the compressor issue what are parameters set to?

simply default, load in the patch from the module browser, and turn the Treshold rotary to the left: skrreeeeechhhhhh

**Comment by sebastien-bouffier** [comment]
Hi, I check that module.
I notice 2 issues on my side. When added the plugin doesn't work. It works when I reopen the patch. And it doesn't work well !!!! :(
Stay tuned

**Comment by Coirt** [comment]
@sebastien-bouffier 
When loaded ratio is defaulted to 0:1 and has a default value of `0.0f` It has a min value of `1.0f` 
https://github.com/sebastien-bouffier/Bidoo/blob/v1.0/src/BAR.cpp#L51

Clicking on the ratio will set it to min value of 1:1 but you would have to do this every time it is added from the module browser.

**Comment by sebastien-bouffier** [comment]
Yep, thanks. I added the missing getValue, getVoltage etc...
I did not manage to reproduce the 

> skrreeeeechhhhhh

Still trying

**Comment by Coirt** [comment]
I think I reproduced it the first time added but I can't do it now either it sounded like hard clipping.

**Comment by Eurikon** [comment]
thanks guys , good to know you are working on it, i highly depend on BaR, every patch i ever made has BaR in it lol :)))) 
thanks a lot for your efforts, if i can assist please let me know

**Comment by Eurikon** [comment]
> 
> 
> Yep, thanks. I added the missing getValue, getVoltage etc...
> I did not manage to reproduce the
> 
> > skrreeeeechhhhhh
> 
> Still trying

hold on, with skreech i meant overload distort sound, not a noise skreeech , sorry for the miss information. 
if you already found the bug and addressed the overload, then i think all will be good. 
i need to try the new BaR module to be sure.

**Comment by Eurikon** [comment]
Hi Sebastien, is there an update on this issue?

**Comment by sebastien-bouffier** [comment]
Hi, just pushed a new commit, I think the issue is fixed on v1.0 branch.

**Comment by sebastien-bouffier** [comment]
Hi, if the issue is fixed, please, close the thread. 
Cheers

**Comment by Eurikon** [comment]
Yes, BaR is working properly now, thank you!
