### ISSUE TITLE
CANard Sampler Crashed Rack

### ISSUE THREAD

**Issue by blackearth2014** [sebastien-bouffier/Bidoo#107]
OS (if applicable):
Version (or "dev" if compiling from source):
CANard sampler crashes VCVRack when trying to save a recorded sample from its inputs.

**Comment by sebastien-bouffier** [comment]
Hi, do you run cANARd under W10 ?

**Comment by blackearth2014** [comment]
I am running it on my Mac at work. Everything plays find but when I record a audio peace and want to save it, it crashes.

**Comment by sebastien-bouffier** [comment]
Hi, the way sample is saved has been changed in v1.0.2 let me know if you still face the same issue.
Best,

**Comment by blackearth2014** [comment]
Thanks

**Comment by sebastien-bouffier** [comment]
Hi, if the issue is fixed, please, close the thread. 
Cheers

**Comment by blackearth2014** [comment]
Everything is working fine now
