### ISSUE TITLE
Limonade: nothing happens when loading .aif

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#109]
OS (if applicable): win 10/64
Version (or "dev" if compiling from source): 1.0.2

Hi, when i load the SQ80 wavefile with extension .aif nothing appears/happens.

**Comment by sebastien-bouffier** [comment]
Hi the lib I use to read/write wav can not handle aiff format. May I propose you to start by convert your aiff to wav with a free tool (there a many) and at the same time I try to find a lib to handle aiff for a next version of my modules.

**Comment by Eurikon** [comment]
ok sure, no problem! thanks man

**Comment by sebastien-bouffier** [comment]
Hi, I am working on it.
Cheers.

**Comment by sebastien-bouffier** [comment]
In 1.0.13 OUAIve, cANARd and liMonADe are able to read aiff files. I hope that when you write .aif you mean .aiff.

**Comment by Eurikon** [comment]
Hi Sebastien!
Thanks for the update :) 
Yes i meant aiff 👍

**Comment by sebastien-bouffier** [comment]
Ok it is available.
