### ISSUE TITLE
Mac 0.5.0 Build

### ISSUE THREAD

**Issue by charlescrammond** [sebastien-bouffier/Bidoo#11]
[Bidoo Mac 0.5.0.zip](https://github.com/sebastien-bouffier/Bidoo/files/1495166/Bidoo.Mac.0.5.0.zip)

BRILLIANT AMAZING MODULES! Someone was after a mac build on FB so I'm putting this mac build here, built last night.

**Comment by sebastien-bouffier** [comment]
Thanks a lot charles

**Comment by nay-seven** [comment]
Yep, Thanks a lot !
