### ISSUE TITLE
antN: Won't play stations

### ISSUE THREAD

**Issue by therealkitman** [sebastien-bouffier/Bidoo#111]
OS (if applicable): opensuse leap 15.0
Version (or "dev" if compiling from source): V1.0.2
Hi. I can get antN to play the French station "http://direct.franceculture.fr/live/franceculture-midfi.mp3" as in your youtube video for LiMonADe.
But it won;t play any other stream or mp3 file I load.
eg - https://somafm.com/deepspaceone.pls fails
eg - file:///data/chris/BUNKA.mp3 fails.

**Comment by nay-seven** [comment]
hello, i test your link directly in Antn and it don't work, then i paste it in Firefox and it opens a webpage with this address:
http://chai5she.cdn.dvmr.fr/franceculture-midfi.mp3
I paste this one in Antn and it works ?

**Comment by therealkitman** [comment]
antN seems to be a finicky plugin. This morning I tried again to run the SOMAFM url - but it is still playing the audio from "http://direct.franceculture.fr/live/franceculture-midfi.mp3". 
It's like antN is hardcoded to play only one station????
![image](https://user-images.githubusercontent.com/14888092/61601178-ddd6e300-ac66-11e9-8010-a88e04d481ba.png)

**Comment by nay-seven** [comment]
I suppose Antn keep the last in memory ?
.pls don't always work for me too, but your second radio have also .mp3 links, this one works for me:
http://ice4.somafm.com/deepspaceone-128-mp3

**Comment by sebastien-bouffier** [comment]
Hi, sorry to come back late.
One v1.0 migration side effect is that the onchange event of the text field has been replaced by onbutton.
So to make sure the new uri is taken into account you may have to enter a space character after a copy/paste. 
Second point, the current version has a bug when parsing pls.
I try to fix all those issues asap.
I think there is a bug on resources sharing .... 
Cheers

**Comment by therealkitman** [comment]
> I suppose Antn keep the last in memory ?
> .pls don't always work for me too, but your second radio have also .mp3 links, this one works for me:
> http://ice4.somafm.com/deepspaceone-128-mp3

The url is actually http://ice4.somafm.com/deepspaceone-128.mp3 - (128 dot mp3) and yes it works for me but crashes Rack v1.1.1 and V1.1.2 after a few seconds.

**Comment by therealkitman** [comment]
> Hi, sorry to come back late.
> One v1.0 migration side effect is that the onchange event of the text field has been replaced by onbutton.
> So to make sure the new uri is taken into account you may have to enter a space character after a copy/paste.
> Second point, the current version has a bug when parsing pls.
> I try to fix all those issues asap.
> I think there is a bug on resources sharing ....
> Cheers

Hi, a space char after the url made no difference.

**Comment by sebastien-bouffier** [comment]
Hi, v1.0.3 should fix the pls parsing issue.
When the uri is .pls or m3u I call that uri and parse it to find the first "http" line and call that new uri.
I realize now that there is an issue for m3u haaaaa ... 1.0.4.
I added a graphic view of both buffers incoming data and audio data.
I made tests with [https://somafm.com/deepspaceone.pls](https://somafm.com/deepspaceone.pls).
It works, but I had some clipping so I increased the audio buffer that was instantaneously full with your uri.
It seems more stable.
Cheers

**Comment by therealkitman** [comment]
Hi, V1.0.3 is more reliable. I have used a number of mp3 streaming sites and they work.
1. I have to add a space char and carriage return after pasting a url into antN.
2. Sorry but the yellow colour of the graphic view is horrible. Yellow against a light background has no contrast. May I suggest a using better colour - maybe green or red?
![image](https://user-images.githubusercontent.com/14888092/61842683-9b621000-aecb-11e9-902b-7a8b88171e23.png) ![image](https://user-images.githubusercontent.com/14888092/61842718-c0568300-aecb-11e9-82fd-9350ea723758.png)
3. This isn't a major problem but the GAIN does not go to 0. Can use the Mixer's CV Volume input control.
4. Still won't play mp3 file on my local drive eg file:///data/chris/Music/Vocaloids/mp3/Alice.mp3. Should it or is antN only for streaming sites?

But thank you for fixing in V1.0.3!!!

**Comment by sebastien-bouffier** [comment]
Hi, v1.0.4 is pushed with the fix for 1., colors changed for 2., 3. done too and 4. yes it is a stream player.
Best
