### ISSUE TITLE
module request: Bidoo Bar mini

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#112]
Hi , would it be possible for you to create a smaller mono version of the BaR compressor?
![bidoo-bar-mono](https://user-images.githubusercontent.com/40998416/61597834-4eedaa80-ac15-11e9-914c-ab4fd210b8a6.png)

that would really be very useful!

**Comment by Petervos2018** [comment]
And call it "MiNiBaR" sorry I could not resist...

**Comment by sebastien-bouffier** [comment]
Hi, two good ideas :)
Cheers

**Comment by Eurikon** [comment]
thanks so much Sebastien!! and Peter :)

**Comment by Eurikon** [comment]
by the way, for the Attack/Release knob, there are several ways that you can choose from. 
for example like in the picture small knobs, but that might be too small. 
a rotary knob with inner and outer ring. 
or , a rotary knob that needs  click or shift+click on it to change to secondary rotary knob function.

**Comment by sebastien-bouffier** [comment]
Hi, v1.0.3 contains a first version of mINIBar :)

**Comment by Petervos2018** [comment]
Love it !

**Comment by Eurikon** [comment]
whoaaa, this is so cool :D 
thanks man!!

**Comment by Eurikon** [comment]
works and looks fantastic! love it :D 

maybe in next version. you can put the value information either in top of the black screen or bottom?
so that when we touch a button it appear there? 

For me it is not very very important, cause i use my ears as well. 
But maybe some people need visual reference to remember at what value they set the knobs.

**Comment by sebastien-bouffier** [comment]
Upgraded in 1.0.4. Cheers
