### ISSUE TITLE
liMonADe

### ISSUE THREAD

**Issue by vpmaster2004** [sebastien-bouffier/Bidoo#114]
Running on Windows 10
VCV Rack 1.1.3
no manual available for liMonADe

**Comment by sebastien-bouffier** [comment]
Hi, did you take a look at my video on youtube ? I added hints on controls so they are less cryptic I hope. Once bugs will be solved I will take time to write something if you really need it.
Cheers

**Comment by sebastien-bouffier** [comment]
Hi, just updated the wiki. Hope it helps.
Cheers

**Comment by sebastien-bouffier** [comment]
No news, good news ? I hope the wiki answers to your questions, if you have any issue let me know. I close the thread.
