### ISSUE TITLE
VCV Browser Crash

### ISSUE THREAD

**Issue by midiguru** [sebastien-bouffier/Bidoo#115]
I have just updated three plugins (Ohmer, Bidoo, and Coirt/Bark) in VCV for Windows. The VCV browser now crashes consistently when opened. I don't know which plugin is doing this, so I will need the _previous_ version of your Windows plugin in order to test it. Please advise where I can download that. Thanks!

**Comment by midiguru** [comment]
Update: The problem seems definitely to be in your plugin. When I drag the Bidoo folder out of Rack/plugins-v1 and then restart VCV, the browser opens successfully. But when your plugin is in that folder, the browser crashes VCV. Would you like the log.txt file? I don't know if it will help, but here it is.

[log.txt](https://github.com/sebastien-bouffier/Bidoo/files/3438651/log.txt)

**Comment by Coirt** [comment]
@sebastien-bouffier Seems to be MiniBar crashing

**Comment by Coirt** [comment]
Had a look there it does not crash the dev build :(

I think it might be an easy fix though, just scope the custom labels, Surround L287 - L385 with `{...}`

**Comment by Coirt** [comment]
Actually can't get the release to crash either with the dist

**Comment by sebastien-bouffier** [comment]
Hi, just pushed a commit, I hope it fixes the bug since it doesn't crash on my environment

**Comment by Coirt** [comment]
I've tested the previous and latest commits against a few different Rack commits using `./rack debug` I can not get it to crash, though it was not crashing anyway. The Plugin Library `1.0.4` version was the only crash, so it remains to be seen.

Not sure why the dev version of Rack is not crashing there is something different in dev than the release version of Rack, which is a massive headache. Wondering if there is package installed with gdb that prevents dev from crashing.

**Comment by sebastien-bouffier** [comment]
I made a dist and replaced 1.0.3 with my last commit on 1.0.4. No crash.
Maybe midiguru could replace his bidoo folder with the dist in the last release and verify stability.
[https://github.com/sebastien-bouffier/Bidoo/releases/tag/1.0.4](https://github.com/sebastien-bouffier/Bidoo/releases/tag/1.0.4)

**Comment by Coirt** [comment]
Well if it does not crash and the next update from the PM does crash there is something different about the built dist from the plugin manager.

**Comment by midiguru** [comment]
It's not crashing now -- seems to have been fixed in this build of 1.0.4.

--JA

**Comment by sebastien-bouffier** [comment]
@midiguru  Thanks for testing, sounds good and @Coirt you are right too.
