### ISSUE TITLE
VCV Crash

### ISSUE THREAD

**Issue by EdwardRosenfeld** [sebastien-bouffier/Bidoo#116]
OS (if applicable): Latest version of Biddoo plugins causes a crash in my windows platform version of VCV Rack.

**Comment by Coirt** [comment]
duplicate of #115

**Comment by EdwardRosenfeld** [comment]
Thanks for the quick fix...

**Comment by sebastien-bouffier** [comment]
Hi @EdwardRosenfeld  I am working on that issue but to be honest I do not know where it does come from .... stay tuned. I made a release with a W dist so you can try to replace your bidoo folder with the one contained in the last release.
