### ISSUE TITLE
OUAIve slow down UI loading

### ISSUE THREAD

**Issue by z-plane** [sebastien-bouffier/Bidoo#119]
OS (if applicable): OSX 10.13.6
Version (or "dev" if compiling from source): 1.04 (VCV Rack 1.1.3)

Je pense qu'il y a un probleme avec OUAIve, j'ai l'impression que ca ralenti le chargement de VCV Rack car chaque parti des graphismes s'affiche tres lentement. une fois charger le logiciel parait tres ralenti...

J'utilise une boucle 44.khz 24bit de 28 secondes. Pas de problems si j'utilise le module equivalent de CF /o\

**Comment by sebastien-bouffier** [comment]
salut la version 1.0.5 devrait soulager un peu l'affichage tout en conservant la gestion du zoom

**Comment by sebastien-bouffier** [comment]
Any news ?

**Comment by z-plane** [comment]
l'affichage marche mieux mais maintenant j'ai un bug de playback (ca devrai etre x1.0 mais on dirais x2.0). en mode gate ca ne marche pas non plus, bizarre!

<img width="314" alt="Screen Shot 2019-08-27 at 23 11 52" src="https://user-images.githubusercontent.com/5803711/63811696-19c52e00-c920-11e9-80d4-e10933cdd833.png">

**Comment by sebastien-bouffier** [comment]
Salut, la version 1.0.7 (juste pushed donc dispo sous peu) corrige le pb de vitesse de lecture. En ce qui concerne le mode Gate pour moi ça fonctionne "normalement" i.e. quand j'ouvre la gate le sample est lu en fonction de l'input POS. C'est comme ça que j'utilise ce mode, pour prendre la main sur la tête de lecture, l'entrée TRIG/GATE servant de switch sur le port de sortie. Cheers.

**Comment by sebastien-bouffier** [comment]
Salut, si le pb est corrigé pouvez vous fermer cette conversation sinon faites moi savoir ce qui ne fonctionne pas svp ?
Musicalement, Seb

**Comment by z-plane** [comment]
Tout marche, desole pour le delai!

**Comment by sebastien-bouffier** [comment]
pas de p, merci pour l'update
