### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#120]
Hi, 
would it be possible to have a change log link from VCV to see what has been updated , before i hit update? :) 
i'ld love to know for example what has been updated from 1.0.4 > 1.0.5

Thanks

**Comment by sebastien-bouffier** [comment]
Hi,
I do not see any changelog link on the VCV webpage even if there is a link available within the plugin.json file, and I think that there is no way to see any changelog within Rack for that time being.
I try to maintain a minimal/cryptic changelog on my github page with date, version and changes.
1.0.5 contains a fix on liMonADe for loading wavetables and an optimization on OUAIve's waveform display.
Cheers

**Comment by Eurikon** [comment]
ah yes i see now! thanks.
keep up the great work:)

**Comment by sebastien-bouffier** [comment]
thanks

**Comment by Coirt** [comment]
@sebastien-bouffier the changelog field can be linked to any file/anywhere for example:
https://github.com/Coirt/Bark/blob/master/plugin.json#L13

which points to the `changelog.txt` file in my repo

The following edit to your plugin.json#L13 will open the documented changes when a user clicks the changelog link from the update page in Rack
`"changelogUrl": "https://github.com/sebastien-bouffier/Bidoo/blob/v1.0/README.md#last-changes",`

**Comment by sebastien-bouffier** [comment]
Hi Phil thanks so much for that information I will put it in place.
