### ISSUE TITLE
Limonade V1.0.5 - Display Issues

### ISSUE THREAD

**Issue by therealkitman** [sebastien-bouffier/Bidoo#121]
OS (if applicable): opensuse leap 15.0
Version (or "dev" if compiling from source): 1.0.5
Hi,
Doing some more testing with Limonade I found a few 'cosmetic' issues.
1. After I set the sample size from 2048 to 256, each time I reopen VCV or open a preset of Limonade having 256 sample size, the displayed sample size goes back to 2048.

2. As I turn the green edited frame knob, the yellow magnitude and phase bar graphs display the selected frame but the frame count (Frame 1 / 64, Frame 2 / 64) does not update so the frame count and bar graphs are out of sync. But if I use the red played frame knob, it updates the frame count but not the bar graphs. Both knobs should keep frame count and bar graphs in sync. But if only one knob can be fixed then it should be the green edited frame knob as a user would want to know which frame they are editing via the bar graphs.
Regard,
Chris.

**Comment by sebastien-bouffier** [comment]
Hi your second point is fixed in 1.0.6 to come, frame number correspond to the edited one. And your first one is in my todo list :)
Cheers

**Comment by sebastien-bouffier** [comment]
1.0.6 released cheers.

**Comment by therealkitman** [comment]
Hi, v1.0.6 looks very good. Merci beaucoup!! :+1:

**Comment by therealkitman** [comment]
One slight odd thing. When I Morph my 64 frame wavetable, Limonade changes it to a 253 frame wavetable.
![image](https://user-images.githubusercontent.com/14888092/63426084-98aff780-c444-11e9-99a7-cb5f1094c234.png)
But when I Remove morphing it goes back to a 64 frame wavetable. Is this 253 frames normal?

**Comment by sebastien-bouffier** [comment]
Hi, the wave table is 256 (frames) x 2048 (samples). When 64 frames are loaded liMonADe inserts 3 frames for morphing between each 64 frames. 63*3+64=253. If your wave table is 6 frames long then liMonADe inserts 50 frames and you reach 256. We can change that behavior by using all the remaining frames but the morphing won't be linear, if I am correct. Or we may rescale the loaded frames so that all frames are equally distributed but I am not sure of the return on equity in terms of sound :) Let me know if you know a better approach

**Comment by therealkitman** [comment]
Hi. I wouldn't know one approach from another :laughing: 
I thought it was something weird but obviously there is reasoning here so I will close this (finally). In reality I doubt anyone would use just a 4 or 6 frame wavetable.
BTW - the new feature of the edited and played frame displays is excellent!

**Comment by sebastien-bouffier** [comment]
Thanks.
I have found many many many free wave-tables, mostly 2048 samples per frame, with few frames 4, 5 or 6 frames that support very well morphing.
