### ISSUE TITLE
Limonade v1.0.6: DC Offset display

### ISSUE THREAD

**Issue by therealkitman** [sebastien-bouffier/Bidoo#122]
OS (if applicable): opensuse leap 15.1
Version (or "dev" if compiling from source):1.0.6
Hi, I think this is just a display issue - not an operational fault. If I add a DC offset to change the output from +/-5V to 0-10V, the 3D Wavetable Display waveform actually goes downwards.
![image](https://user-images.githubusercontent.com/14888092/63739483-ea7ed480-c8bf-11e9-8fbe-e53c99c3297f.png)

I thought it would have gone upwards.
![image](https://user-images.githubusercontent.com/14888092/63739501-f8345a00-c8bf-11e9-8b01-9bae181d2057.png)
Regards,
Chris.

**Comment by sebastien-bouffier** [comment]
Hi, it is fixed in 1.0.7. 
Best,
Seb

**Comment by therealkitman** [comment]
1.0.7 tests ok Thank you. :+1:
