### ISSUE TITLE
dTroy/bordL V1.0.7 Sequence Issue

### ISSUE THREAD

**Issue by therealkitman** [sebastien-bouffier/Bidoo#124]
OS (if applicable): opensuse leap 15.1
Version (or "dev" if compiling from source): V1.0.7
Hi,
I think there is a bug with both dTroy and bordL is the way they handle the 1st external clock pulse in a simple sequence - that is the 1st step is ignored.
I have a simple 4 step sequence Step 1 - 1 pulse, step 2 - no pulses, step 3 - 3 pulses, step 4 - no pulses. 
When the sequencer is reset and then the external clock starts the 1st step in not played - it's like the 1st clock pulse is lost or ignored. If I use the internal clock the 1st step is played ok.
![image](https://user-images.githubusercontent.com/14888092/64588392-e03afb00-d3d4-11e9-81df-db924bdf8c7a.png)
Attached is my test patch.
[dtroy issue.zip](https://github.com/sebastien-bouffier/Bidoo/files/3593979/dtroy.issue.zip)
Regards...

**Comment by Petervos2018** [comment]
Hi RealKitMan,
This is an ongoing problem with VCV, clocks and sequencers. 
In your case working with clocked, you can solve this most of the time by NOT using the RESET out as a reset but using the RUN out instead, this will play the first note. 
(make sure that "Output reset high..." is UNchecked in the right-click menu... )
It's not solving the first note problem inside the bidoo modules but maybe this work around it is useful for you...
Greetings Peter.

You can try this also with other sequencers that skip the first note.

**Comment by therealkitman** [comment]
Hi @Petervos2018 ,
Thanks for the reply. Yes, I am aware of CLOCKED's context menu settings and tried all combos  - but it still happens.
Wait a minute! You mean I have to "wire" from the RUN output, not the RESET output. That works!!
Well well well. :roll_eyes: 
I thought this problem was unique to dtroy and bordl. I might test this some more tonight on other sequencers and re-open this issue if I have to.
Thanks Peter,
Chris.
