### ISSUE TITLE
BaR / MiniBaR - bypass

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#125]
Hi Sebastien!

would it be possible for you to add a small bypass button on the compressors? 
for a/b comparing.

**Comment by sebastien-bouffier** [comment]
Hi 1.0.8 pushed this morning, bypass is available via a small led button on top of modules

**Comment by Eurikon** [comment]
Excellent! thanks a lot :D

**Comment by Eurikon** [comment]
Hi Sebastien, i am getting an error when unpacking the zipfile, some svg file in it exists double.
And i am getting a warning error when trying to build the plugin from source.

**Comment by Eurikon** [comment]
Never mind i updated now through Rack itself, all good!
