### ISSUE TITLE
dTrOY Step Knobs: No Negatives

### ISSUE THREAD

**Issue by midiguru23** [sebastien-bouffier/Bidoo#126]
In the 1.0.8 release, the eight step knobs along the top of dTrOY won't go below 0.00. That is, the knob will _travel_ further counter-clockwise, but the output of the step never drops below 0.00. As a result, part of the knob's travel/rotation is useless.

**Comment by Petervos2018** [comment]
It is broken as far back as 1.0.2 (the oldest version I have)
I thought he already fixed it but that was BordL. :(

**Comment by sebastien-bouffier** [comment]
Hi, just pushed 1.0.9 that should fix pitch knobs issue on dTrOY
Cheers

**Comment by sebastien-bouffier** [comment]
1.0.9 seems to fix the issue, I close the thread.
Best, Seb
