### ISSUE TITLE
BordL strange issue with shift down

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#127]
Version 1.0.8.

Load BordL, set first pitch to say C3, now press the shift down button.
What happened ?
Keep hitting shift down... nothing happens does it ?

And why are all the pitches set to A#3 when I add a new BordL ?

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi, fixed in 1.0.10 to come.
Cheers

**Comment by Petervos2018** [comment]
The other one... dTroy has the same symptoms A#3 as a starting note and no down shifting did you also look at that one ?
Love your work ;)
Greetings Peter

EDIT : just read the change log and it seems you did ... Well done.
 
I could remove this comment  but I leave it for posterity ;)

**Comment by sebastien-bouffier** [comment]
:)

**Comment by Petervos2018** [comment]
And it's fixed in 1.0.10
Thanks and closed !

Greetings Peter.
