### ISSUE TITLE
Both compressors red line "off the chart"

### ISSUE THREAD

**Issue by SteveRussell33** [sebastien-bouffier/Bidoo#129]
When pushed hard, both red lines go off the main panel.
Win 10 Rack 1.1.5

![barpush](https://user-images.githubusercontent.com/41975381/67173496-e39faa00-f3b6-11e9-91a2-d0c0da93848a.png)

**Comment by sebastien-bouffier** [comment]
Hi Steve, I reproduced this issue and I monitored the incoming audio signal with the help of VCV SCOPE.
NOIS output range is -10V +10V and when passing thru cf's channels it goes from -40V to +40V.
If I refer to VCV standard [https://vcvrack.com/manual/VoltageStandards.html](https://vcvrack.com/manual/VoltageStandards.html) the audio signal should be contained within the -5V +5V range.
I will try to talk with Andrew to understand NOIS output range.
Stay tuned

**Comment by sebastien-bouffier** [comment]
I have read NOIS source code and according to my understanding it is designed to make several noise signals which RMS (and not the peak value) is between -5V and +5V.
I changed the way the display behaves (cap value) in the next version.

**Comment by SteveRussell33** [comment]
Hi Sebastien,
Thanks for reply. I assumed Nois was the usual -10V +10V; however I didn't know cf had that much of a range. Wow.

**Comment by SteveRussell33** [comment]
Built v1.0.12 and thought I would run a small test to check. Your display fixes are working fine.

You mentioned previously that using a scope, you saw that cf channels run at about -40V to +40V - were you quoting the PP figure by mistake? As you can see from the image below, using a fully gained cf channel and 0 make up gain from baR I get ~ -22V to +22V (both v1.0.11 and v1.0.12)

The scope on the right is an slightly updated colour scope from v0.6 days that I've been playing with. Notice that mINIBar has full makeup gain - check the scope's min/max numbers. Having some fun now!
If I push baR's makeup gain to full, the official VCV scope just drops the numbers from display and shows --- for each.

![barpush](https://user-images.githubusercontent.com/41975381/67220062-036bb800-f421-11e9-9fce-df5da4006037.png)

**Comment by sebastien-bouffier** [comment]
Yes you are right, gain from cf is x2 and not x4. Regarding baR and mINIBar the figures seems correct since NOIS is peak to peak ~ -10V to +10V, after cf ~-22V to +22V, baR or mINIBar pushes 60dB of gain i.e. 10^(60/20)=1000 and I see ~-30000V to +22000V.
That's a lot but it can be useful sometime
