### ISSUE TITLE
Is AcnE supposed to look like this ?

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#130]
![AcneRed-03112019](https://user-images.githubusercontent.com/46076474/68091365-236a9500-fe7f-11e9-9a8e-a62c1b82a650.png)
If so please close this issue.

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter, ACnE is not supposed to look like this. Since Rack 1.0 I did not manage to make it behave as before. Gain knobs are supposed to be black or grey when 0dB and gradually become red when > 0dB.
I am still trying to find a way to fix it.
Best

**Comment by Petervos2018** [comment]
O.K., at least I know you are on the case ;)
Red is my favourite colour, but I thought this was a bit much...
Happy hunting,
Peter.

**Comment by sebastien-bouffier** [comment]
Hi, it is fixed in v1.1.0 to come. I fixed the trimpots jumps when recording automation with scenes too.
Cheers

**Comment by Petervos2018** [comment]
Fixed an thanks v1.1.0
Closed.
Greetings Peter
