### ISSUE TITLE
Drifting in zOù MAï

### ISSUE THREAD

**Issue by MaZe6K** [sebastien-bouffier/Bidoo#132]
OS (if applicable):Windows 10
Version (or "dev" if compiling from source):1.1.6

Hi there!
I love zOù MAï, but it has quite some issues with drifting. If I run multiple channels at different speeds they constantly drift apart from each other and continue to do so until I reset the sequencer.
It would be very cool if this could be fixed and everything would stay in sync the whole time without having to reset it.
Maybe it would be a better solution to base everything on a fast running clock and choose subdivisions for speed, length, repeats etc. instead of multiplying a slow clock?

**Comment by sebastien-bouffier** [comment]
Hi,
Yep I noticed that unsatisfying behavior. I was focused on my samplers because I needed to make them engine sample rate compliant :) I take that point as top priority.
Best

**Comment by sebastien-bouffier** [comment]
Hi @MaZe6K,
I just pushed a new version of zOù MAï.
Let me know if it works better for you.
Cheers.

**Comment by MaZe6K** [comment]
Cool!
According to my first tests it stays 100% in sync now.
Thank You!

**Comment by sebastien-bouffier** [comment]
Great :)
I close the thread.
