### ISSUE TITLE
Limonade 1.1.6 and 1.1.8 Windows 7 load wave Crash Rack

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#133]
Hi Seb : 1.1.6 and 1.1.8 both Crash, 1.1.2 and **1.1.5 work** !

33.027 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
31: ZN4rack10appDestroyEv 0x456435
30: gai_strerrorW 0x739800
29: _C_specific_handler 0x76fd71cc
28: _chkstk 0x76febe00
27: RtlInitializeResource 0x76fbfed0
26: KiUserExceptionDispatcher 0x76feb510
25: Z11tLoadSampleR7wtTableNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEyb 0x45f5d5c
24: ZN8LIMONADE10loadSampleEv 0x45f8030
23: ZN25LimonadeBlueBtnLoadSample8onButtonERKN4rack5event6ButtonE 0x46afdb0
22: ZN4rack3app12ModuleWidget8onButtonERKNS_5event6ButtonE 0x495b46
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
20: ZN4rack3app10RackWidget8onButtonERKNS_5event6ButtonE 0x48cbc4
19: ZN4rack6widget10ZoomWidget8onButtonERKNS_5event6ButtonE 0x7715e0
18: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
17: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3ed4
16: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
15: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
14: ZN4rack7updater17isUpdateAvailableEv 0x45914e
13: glfwPlatformUnlockMutex 0x4d78ae
12: TranslateMessageEx 0x76e997e0
11: CallWindowProcW 0x76e93a04
10: CallWindowProcW 0x76e93a04
9: glDebugEntry 0xf258a170
8: TranslateMessageEx 0x76e997e0
7: TranslateMessage 0x76e995a8
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x76d75560
0: RtlUserThreadStart 0x76fd3710

And I use the 02-Acid.wav for all the tests.

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi I will revert to 1.1.5 code for liMonADe. Sorry for the inconvenience.

**Comment by Petervos2018** [comment]
Hi Seb,

no inconvenience at all, most of the time I just test some modules I know that are a bit tricky, after an update, and Limonade is one of them.

From your changelog it looked like you've done nothing to Limonade for some time, the only real change was in the samplerate for samplers.

I'll just wait for the downgrade ;)

Thanks for your modules, and happy holidays,

Peter.

**Comment by sebastien-bouffier** [comment]
Hi, I just pushed 1.1.10 that should fix this issue.
Can you build and test before I submit my release ?
Cheers.

**Comment by Petervos2018** [comment]
Nah, I can test but I can not build :( 

Greetings Peter

**Comment by Petervos2018** [comment]
Yes testing 1.1.10 and loading a wave in liMonADe works (again) 👍 

Thank you,
Peter.
