### ISSUE TITLE
ACnE: request - Add explicit snapshot save button

### ISSUE THREAD

**Issue by johnnovak** [sebastien-bouffier/Bidoo#135]
ACnE would be much more useful if it didn't automatically update the current snapshot. That way you could restore a snapshot, tweak the buttons for a live performance, for example, but those new settings would not be stored in the active snapshot until you press the Save button.

Alternatively, you could add another Autosave switch. If it's on, it's the current behaviour. If it's off, you need to press the Save button to save the scene.

**Comment by sebastien-bouffier** [comment]
Hi,
Good suggestion I will add this feature in a future release.
FYI I use ACnE this way because it allows me to record some kind of automations  when snapshots are driven by a LFO.
Best,

**Comment by johnnovak** [comment]
Cool, making this configurable would be definitely the best way, thanks!

**Comment by sebastien-bouffier** [comment]
Hi, I just pushed 1.1.10 with the feature added.
Can you build and test before I submit my release ?
Cheers.

**Comment by johnnovak** [comment]
No sorry, I don't have a dev env set up and I don't have time for it this week anyway.

**Comment by sebastien-bouffier** [comment]
Hi, in order to clean the issue list I close the case since I think it is solved. If you still have any issue please reopen the thread.
Cheers
