### ISSUE TITLE
MOiRE: scene update bug

### ISSUE THREAD

**Issue by johnnovak** [sebastien-bouffier/Bidoo#136]
How to replicate (from the init state):

1. Turn red crossfade knob fully right (so the upper scene is active).
2. Turn knob 1 to max value.
3. Save scene.
4. Switch to scene 2 using the upper scene select knob.
5. Note that the value of knob 1 has not been updated to min value. But if you just simply click on the red knob (without turning it) the update will happen. You can also click on the upper blue button to the left of the red knob to force the update.

This is the simplest way to reproduce it, but effectively whenever you turn some knobs in a scene and you switch to a new scene by just using the small blue scene selection knobs, the knobs you have tweaked/touched won't update UNTIL you click on either the big red button or the two blue buttons left to it.

Please fix this as this will spare me from writing a very similar module myself that works correctly :P

**Comment by nay-seven** [comment]
!!
you realize your last sentence is a little insulting ?

**Comment by johnnovak** [comment]
Sorry, I didn't want to insult you, I shouldn't have said that so now I apologise. I appreciate the time and effort you put into writing these plugins, especially because you're providing it for everybody for free. It would be nice if you could fix this bug, it would make your module much more useful. Thanks! :)

**Comment by sebastien-bouffier** [comment]
Hi, it is fixed and it will be available in the next release.
It was the occasion to read again the code of this "old" module and once zOù MAï will behave as I want I will probably rewrite MOiRE in a nother release.
Thanks for nay's post and thanks for your reply.
Cheers.

**Comment by sebastien-bouffier** [comment]
Hi, I just pushed 1.1.10 that should fix your issue.
Can you build and test before I submit my release ?
Cheers.

**Comment by johnnovak** [comment]
Sorry, as I said in my other ticket I don't have a dev env set up and I'm very busy this week anyway.

**Comment by sebastien-bouffier** [comment]
Hi, in order to clean the issue list I close the case since I think it is solved. If you still have any issue please reopen the thread.
Cheers
