### ISSUE TITLE
U don't work on 1.6 mac ?

### ISSUE THREAD

**Issue by nay-seven** [sebastien-bouffier/Bidoo#138]
OS (if applicable): Mac OS Mojave
Version (or "dev" if compiling from source): official
<img width="582" alt="Capture d’écran 2020-02-04 à 12 41 39" src="https://user-images.githubusercontent.com/13808201/73742164-172af800-474c-11ea-918d-362cd705518a.png">

Hello,
Here a simple patch working on version 0.6 of rack, but don't work in 1.6 here ?
Thanks

**Comment by sebastien-bouffier** [comment]
Hi, I just pushed 1.1.10 that should fix your issue.
Can you build and test before I submit my release ?
Cheers.

**Comment by nay-seven** [comment]
sorry, never built releases myself, i know i must , but ...;-)

**Comment by nay-seven** [comment]
i just try for the first time, 7 warnings and 11 errors ? 
no zip created

**Comment by nay-seven** [comment]
ok, so someone else compile without errors on the VCV forum, so must be me

**Comment by Coirt** [comment]
This was me I'm on windows.

**Comment by sebastien-bouffier** [comment]
Hi dear users/musicians/friends my pack has been updated this morning so I hope it fixes the issue.
Cheers

**Comment by nay-seven** [comment]
Yes, works now , thanks a lot !

**Comment by sebastien-bouffier** [comment]
Great, I close the thread.
