### ISSUE TITLE
Message de collision?

### ISSUE THREAD

**Issue by caecos** [sebastien-bouffier/Bidoo#139]
$ git clone https://github.com/sebastien-bouffier/Bidoo.git
Clonage dans 'Bidoo'...
remote: Enumerating objects: 558, done.
remote: Counting objects: 100% (558/558), done.
remote: Compressing objects: 100% (371/371), done.
remote: Total 4120 (delta 400), reused 316 (delta 184), pack-reused 3562
Réception d'objets: 100% (4120/4120), 59.23 Mio | 1.12 Mio/s, fait.
Résolution des deltas: 100% (2484/2484), fait.
Mise à jour des fichiers: 100% (192/192), fait.
warning: Les chemins suivants sont en collision (par exemple par des chemins
sensibles à la casse dans une système de fichier insensible) et un
seul du groupe en collision est dans l'arbre de travail :

  'res/ComponentLibrary/bidooLongSLiderHandle.svg'
  'res/ComponentLibrary/bidooLongSliderHandle.svg'

**Comment by sebastien-bouffier** [comment]
yes maybe, thanks I will update the repository

**Comment by sebastien-bouffier** [comment]
Done.
This svg was not used anymore so I removed the component too.
Cheers.

**Comment by sebastien-bouffier** [comment]
Hi, in order to clean the issue list I close the case since I think it is solved. If you still have any issue please reopen the thread.
Cheers
