### ISSUE TITLE
pErCO seems to run into rounding errors with lower sampling rates

### ISSUE THREAD

**Issue by hexdump0815** [sebastien-bouffier/Bidoo#142]
OS (linux):
Version (1.1.13):

hello sebastien,

i'm using vcvrack on arm systems (https://github.com/hexdump0815/vcvrack-dockerbuild-v1) mostly with a 32khz sampling rate to save cpu power, as arm systems are a bit low on cpu. i do this by explicitely setting "sampleRate": 32000.0 in the vcvrack settings json file and it works very good this way (and makes things possible on this hardware which would not be possible at 44.1khz). i just noticed that pErCO seems to have problems with sample rates lower than 44.1khz (lower than 32,78khz to be more exact - but more about that later ...) - as an easy test to show this simply configure vcvrack to 32khz as described and then do a simple patch of an oscillator (i'm using palm loops from 21khz, but any other should do as well) outputting a square wave to the input of pErCO and the LP output of perco to the scope. it works as expected as long as the filter cutoff wheel is not at the right end, but if you go to the right the output stops and the pErCO is stuck in that state. i played around with different sampling rates and found out, that it still works at 32,78khz (and above), it does not work at 32,76khz (and lower) and at 32,77khz you can see it slowly going crazy and breaking up. to me it looks like some rounding error piling up over time and resulting in some undefined state - i guess this happens around here:

https://github.com/sebastien-bouffier/Bidoo/blob/a9d789c05fe9592fd7b28a5eed9588a826829d08/src/PERCO.cpp#L24-L32

do you have an idea where this might come from and how to maybe get this fixed?

a lot of thanks in advance and best wishes - hexdump

p.s.: the problem also appears with the official pErCO and the official vcvrack 1.1.6 for linux

update:i just verified that it also happens the same way if i use vco-1 from vcv as oscillator ....

update 2: i did not see such behaviour with any other vcf, only with pErCO so far

**Comment by hexdump0815** [comment]
i think i have an idea: maybe i'll have to change this line:
https://github.com/sebastien-bouffier/Bidoo/blob/a9d789c05fe9592fd7b28a5eed9588a826829d08/src/PERCO.cpp#L64
to have a lower max cutoff frequency - it looks a bit like the max cutoff frequency has to be below 1/4 of the sampling frequency (just guessing, but it would work out quite well from the numbers in the 32khz case) ... maybe "13.f * 410.58f" instead should make it work for sampling rates down to 22.05khz ... i'll give it a try over the weekend maybe ...

**Comment by sebastien-bouffier** [comment]
Hi, I changed the sampling rate to 32760 and I have the same issue. I will try to fix that bug.
Cheers

**Comment by hexdump0815** [comment]
cool - thanks a lot!

best wishes and stay healthy

**Comment by sebastien-bouffier** [comment]
Hi, it is fixed in the last commit. Tested @ 32KHz.
Best wishes and stay healthy too :)

**Comment by hexdump0815** [comment]
cool - thanks a lot - i'll give it a try soon and report back ...

**Comment by hexdump0815** [comment]
i finally got to rebuilding the plugins and can confirm that your fix works perfectly fine - thanks a lot!

**Comment by sebastien-bouffier** [comment]
you are welcome :)

**Comment by hexdump0815** [comment]
i just came across this old issue again as i noted similar problems in other filters too and tried to understand your fix ... i guess your fix was this clamping of the cutoff frequency here: https://github.com/sebastien-bouffier/Bidoo/blob/v1.0/src/PERCO.cpp#L77 ... might it maybe even be better and safer for all sample frequencies to clamp it to args.sampleRate / 4? ... i'm just guessing as i must admit that i do not understand the full details of the filter code, so i'm better asking you :)

update: might maybe even something like args.sampleRate / 2 - 1000.0f work too? (as said i'm not really understanding the details and this is just a guess)

update 2: looks like VCF of Fundamental is the source of the clamping code: https://github.com/VCVRack/Fundamental/blob/v1/src/VCF.cpp#L149 ... so i asked the above question there too - see: https://github.com/VCVRack/Fundamental/issues/115#issuecomment-687875503

best wishes - hexdump
