### ISSUE TITLE
Slug changes are not allowed

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#143]
Per Andrew's policy on backwards compatibility, slug changes are not allowed.

```
[Bidoo] Issues found in `plugin.json`:

Slug change detected: "slug": [-"BISTROT",-]{+"BIsTrot",+}  
```

**Comment by sebastien-bouffier** [comment]
Hi @cschol I hope you are doing well. BISTROT has been changed in the last commit. Sorry for the inconvenience. Cheers.
