### ISSUE TITLE
Limonade, can't add subsequent waveforms.

### ISSUE THREAD

**Issue by SaccoSVD** [sebastien-bouffier/Bidoo#145]
Win10
Ryzen 9 3900X 64GB, 1080ti

VCV Rack 1.1.6

Limonade 1.1.15

It seems the third button on the first row (the one to load wavs individually per frame) is not loading anything.

I don't think I'm missing something, I've read the manual for the module.

This module is absolutely amazing, I wish I could use it properly.

Here is a video:

https://youtu.be/zkwH46oVV2g

Best regards and thank you for sharing your amazing work.

**Comment by sebastien-bouffier** [comment]
Hi @SaccoSVD,
Thanks a lot for your interest in my modules.
This bug is fixed I will release a new version soon.
Do not forget that you can design your own waveforms with the help of the FFT (magnitude and phase).
Best,
Seb

**Comment by sebastien-bouffier** [comment]
Hi, if the issue is fixed please close the thread.
Best.

**Comment by SaccoSVD** [comment]
I can now load new wavs on new frames:)

However there is still one little bug. (maybe I'm wrong)

The manual mentions if I use the "~" a new frame will be created if not present. But that doesn't happen.

Right now I need to hit "+" to add a new frame, then use the "~" to add the waveform.

Other than that the module seems to be working nicely :)

EDIT: Actually I don't mind it, as I think is useful to be able to change any individual waveform in the frames stack without being forced to add a new frame.

**Comment by sebastien-bouffier** [comment]
yes I see that bug, thanks for your reply.

**Comment by sebastien-bouffier** [comment]
I wrote too fast :) I do not understand the bug or I can not reproduce it :) maybe the manual is not clear. If the wave table is empty and if I click "~" it will add a frame and load the sample on it without having to click on "+". Haaaaa I understand when writing. Ok Maybe I should add a kind of "~+" that adds a frame and load the sample after the selected frame, a kind of insert. Am I right ?

**Comment by SaccoSVD** [comment]
I think the manual is clear, but with the previous bug since I couldn't try I assumed it loaded a new frame.

The manual seems clear, I probably miss interpreted the sentence.

I think is fixed :) I'm gonna close the thread. Thank you SO much for this fix, now Limonade is usable again :)
