### ISSUE TITLE
zou Mai - all buttons with LEDs latch for midi feedback

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#146]
OS (if applicable): Windows
Version (or "dev" if compiling from source): 1.1.15

Hi Sebastian, zou Mai is awesome! I'd like to map it to my touchosc template, however it would be a bit difficult to understand what's going on in the sequencer (without looking to monitor) just because all buttons in the modules are just push, so pushes will not send any midi feedback info on controller for proper monitoring. The latch buttons in opposite is a different deal - it can say to controller properly what's going on at this moment if it state zero or one. For example MindMeld mixer has all latch buttons on board. I know it maybe be hard to do at the bottom row because the state of buttons is multifunctional but I'd be glad if keyboard, octave, page select, track on off states, track select would be latched. 
EDIT: also is it possible to reduce CPU consumption a bit? I've got on i7 3 generation around 10% cpu, the most hungry sequencer btw) but one of the most powerful for sure! thank you so much, this is a brilliant in the sequencer's field

**Comment by sebastien-bouffier** [comment]
Hi @vcvrackideas, thanks :)
I will look at your idea (latch buttons), it may help for performance too (not sure but maybe).
Stay tuned.
Best,
Seb

**Comment by sebastien-bouffier** [comment]
Hi, just pushed 1.1.24 let me know if octave buttons for zOù work fine for you please ?
If it is ok I will replicate that approach for all leds buttons
Best

**Comment by vcvrackideas** [comment]
Thanks Sebastian! New buttons are actually looking pretty cool and yeah latch buttons in this case work as expected. Looking forward to other buttons improvements. 
P.S. also I did some video on Zou Mai hope you will enjoy - https://youtu.be/deeMOsTib7k

**Comment by sebastien-bouffier** [comment]
Hi, thanks for your great video :)
Cheers

**Comment by sebastien-bouffier** [comment]
Hi, 1.1.25 pushed with all buttons changed.
Just added recording capability for tracks.

**Comment by chairbender** [comment]
It would also be nice to have this latching on bordl's SK/SL buttons, for the same reason.

**Comment by chairbender** [comment]
nvm, I see this is an old ticket - I have created separate ticket in #193 for my request
