### ISSUE TITLE
[feature request] dTrOY: separate randomization for pitches/gates

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#15]
OS (if applicable):
Version (or "dev" if compiling from source):

i saw some other sequencer module had menu options for randomize pitch and randomize gates.
would you add that to dTrOY?

edit:
also just noticed that the sliders jump to non-stepped positions when using the regular randomize.
should i file an extra issue for that?

edit2:
aaand: slides/skips aren't reset by when using initialize.

**Comment by sebastien-bouffier** [comment]
Hello phdsg I am gonna look into that. Regarding the slider jumps it seems to be a common issue on "snapped" controls. I did the check some time ago on the Befaco osc and the big rotary knob behave the same way. I will focus on random and init first.

**Comment by phdsg** [comment]
very nice, thx
...also for the explanation on the sliders.

**Comment by sebastien-bouffier** [comment]
dTrOY rands done. I made 3 stages => pitch, gates, slides & skips
Still need to take a look at widgets framework to see why when snapped randomize does not behave the right way. The value is correct it is just a matter of display.

**Comment by phdsg** [comment]
great stuff. thanks again.

**Comment by sebastien-bouffier** [comment]
phdsg
I think that Andrew won't spend time on such minor issue before a long time so I made the fix on my sliders. Released
