### ISSUE TITLE
please add root and scale to zou mai

### ISSUE THREAD

**Issue by ghost** [sebastien-bouffier/Bidoo#153]
OS (if applicable):
Version (or "dev" if compiling from source):

**Comment by ghost** [comment]
also can this play chords on each step? Perhaps add a way to input notes form a midi controller as well. with a little more features this thing could be similar to a very new hardware sequencer that was released

**Comment by sebastien-bouffier** [comment]
Hi, nice ideas. Root and Scale are the reason why I added diktat (quantizer) last week. What sequencer are you talking about ?
Cheers

**Comment by ghost** [comment]
Thanks I saw that. My trouble is I want all the tracks on the Zhou Mai to be the same scale and so forth and have to run them all through the big work around using a separate quantizer. I can make it work using mixers and mults I guess. thanks

**Comment by ghost** [comment]
the sequencer is Vector

**Comment by sebastien-bouffier** [comment]
Interesting seq :) 
How do you imagine quantization in zou mai ? Root + scale per track with a kind of dikt@t on each track or global ? Regarding chords do you think that it would useful on every track or 1 or 2 tracks would be enough ?

**Comment by ghost** [comment]
I imagine it would be just 1 root and scale for everything rather than each track as separate. as far as chords ill leave that to you.

**Comment by sebastien-bouffier** [comment]
Not sure I will be able to implement that shortly so you may achieve the same thing with a merge and the next version of dikt@t which is now polyphonic, available in the next release.

**Comment by ghost** [comment]
ok.  Can you please provide a tutorial how to connect that module? It seems a little differrent

**Comment by sebastien-bouffier** [comment]
ok i will do

**Comment by sebastien-bouffier** [comment]
Here it is. Hope it helps :)
[https://www.youtube.com/watch?v=LlTu6ELQM4I&feature=youtu.be](https://www.youtube.com/watch?v=LlTu6ELQM4I&feature=youtu.be)

**Comment by ghost** [comment]
Thanks

**Comment by sebastien-bouffier** [comment]
V/O & Gate Recording available in 1.1.25
