### ISSUE TITLE
Polyphonic Dikt@at suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#154]
OS (if applicable):
Version (or "dev" if compiling from source):
Could you please make it polyphonic? Each sequence would be normalled to each output. And yeah - I absolutely love ditk@t! And this thing doesn't do unwanted offset to the sequence as JW quantizer do. Now it's my favorite one and polyphonic feature would be awesome too! Thanks for the module

**Comment by sebastien-bouffier** [comment]
good idea, next version :)

**Comment by sebastien-bouffier** [comment]
It is polyphonic in the last commit. I will release it with more fixes.

**Comment by vcvrackideas** [comment]
Thanks Seb! Working nice. Chan knob is also awesome think but could we have an option (right click probably) to apply first channel scale to all channels? To keep all sequences in one scale

**Comment by sebastien-bouffier** [comment]
yes good idea

**Comment by sebastien-bouffier** [comment]
Hi @vcvrackideas  I close this thread since it has been released in 1.1.20
