### ISSUE TITLE
mirack?

### ISSUE THREAD

**Issue by armandvedel** [sebastien-bouffier/Bidoo#155]
Any chance for a mirack version? The sequencers would be perfect.

**Comment by sebastien-bouffier** [comment]
Hi @armandvedel, I didn't know about mirack. I do not find any repository in Github ... do you have a link to the developer website ? Best.

**Comment by armandvedel** [comment]
sure!

http://mifki.com/blog/tag/mirack/

It's an ios version of vcvrack 0.6. Many of the well-known modules are on
it, though not all. Would be really great to use bordL etc. on ipad!

**Comment by sebastien-bouffier** [comment]
I am now in contact with Vitaly, my modules will be available in a future version :)
Best.

**Comment by armandvedel** [comment]
Thank you!!!! That is great news!
