### ISSUE TITLE
zOù MAï running constantly, independent of clock running

### ISSUE THREAD

**Issue by lightsofold** [sebastien-bouffier/Bidoo#157]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 1.1.21

Hi,
I am really enjoying using zOù MAï, but I am expeiencing a couple of issues, which I suspect maybe related.

Is it normal behaviour that zOù MAï should run constantly, simply as a result of being connected to the output of a clock, even when the clock itself is not running? The only way I can get zOù MAï to stop is to physically disconnect the clock cable.

Additionally, when I open a previously saved patch where zOù MAï is connected to a clock (whether the clock was running upon save or not), zOù MAï seems to output random chaotic triggers until the clock is started, after which zOù MAï eventually begins to output correctly.

Thanks.

**Comment by sebastien-bouffier** [comment]
Hi, thanks. Yes I never stop my clock and I did not test and implemented anything regarding that state. So at that point zOù starts with an estimate of gaps between clock pulses and keep on tracking that interval when clock is connected. When clock is turned off, the clock tracking waits and tries to sync with a very long interval. I know the issue when opening a patch and it is linked to the previous issue. I try to fix it asap.

**Comment by lightsofold** [comment]
That's great, thank you.

**Comment by sebastien-bouffier** [comment]
Hi, with the last version of my module, zOù MAï should stop when clock is not running. Still trying to fix patch opening issue. Best.

**Comment by lightsofold** [comment]
Hi. Thank you for making this change.
