### ISSUE TITLE
how do random buttons work on zou mai

### ISSUE THREAD

**Issue by ghost** [sebastien-bouffier/Bidoo#158]
OS (if applicable):
Version (or "dev" if compiling from source):
HI having trouble here. I just want to randomize each tracks notes and steps independently but do not understand the controls.

**Comment by sebastien-bouffier** [comment]
Hi, current controls do not provide notes and steps randomization separately. You can rand all tracks (pattern rand), a track and a step but not notes pitch and gate properties independently. I will look into that, confirm that your need is : randomize only the pitch of all notes of the track and for another action randomize only gates status, length etc... Does it makes sense for a single note ? I am not sure.

**Comment by ghost** [comment]
Thanks is there a diagram for what the small buttons?

**Comment by sebastien-bouffier** [comment]
If you ask for it it means that my design is not clear enough and I should redesign it ...
<img width="7680" alt="tools" src="https://user-images.githubusercontent.com/1842599/82534156-f5ac1b80-9b44-11ea-8f8b-c90f88f0fb86.png">
First row contains actions for patterns so in order of appearance COPY, PASTE, CLEAR, RAND and FULL RAND.
Second row contains the same actions for trigs. The third and fourth are dedicated to tracks with the same actions on the first row and the second row stands for moving all trigs of the track right, then left, up (push trigs one semitone upward) and down (push trigs one semitone downward).
For a trig, RAND randomizes its active status and its pitch, FULL RAND randomize its pulse count too.
For a track , RAND randomizes its length, its read mode (forward, backward etc ...) and applies a RAND on its trigs and FULL RAND randomizes its speed too and applies a FULL RAND on its trigs. For patterns RAND and FULL RAND are applied on all tracks of the current pattern.
Hope it helps.

**Comment by ghost** [comment]
Thanks for that.  I think that explanation is sufficient. Maybe just paste that paragraph on your module site and its good. I see now when I zoom in I can see those little arrows I couldnt see before.

**Comment by ghost** [comment]
Maybe we need a little paragraph for the functions in the Trig display too
