### ISSUE TITLE
Zou Mai fill?

### ISSUE THREAD

**Issue by ghost** [sebastien-bouffier/Bidoo#159]
OS (if applicable):
Version (or "dev" if compiling from source):
Hi is the fill input used for entering notes using a keyboard?

**Comment by sebastien-bouffier** [comment]
Hi, no it is here to switch between both FILL and !FILL status of each note. If a note has its prob set to FILL it will be played only when fill (control or input) is on and the opposite for !FILL. Note input is a pending request from another user :)
