### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by t0m5k1** [sebastien-bouffier/Bidoo#16]
OS (if applicable): Arch Linux
Version (or "dev" if compiling from source): 0.5.0

Please can we have a linux release?

**Comment by phdsg** [comment]
[Bidoo-dev4e69904-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1503844/Bidoo-dev4e69904-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks phdsg

**Comment by phdsg** [comment]
here's 0.5.3 build...
[Bidoo-0.5.3-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1512095/Bidoo-0.5.3-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks again :)

**Comment by phdsg** [comment]
0.5.4
[BidooLIN.0.5.4.zip](https://github.com/sebastien-bouffier/Bidoo/files/1522818/BidooLIN.0.5.4.zip)

**Comment by sebastien-bouffier** [comment]
thanks

**Comment by phdsg** [comment]
0.5.6:
[Bidoo.LIN.0.5.6.zip](https://github.com/sebastien-bouffier/Bidoo/files/1549164/Bidoo.LIN.0.5.6.zip)

**Comment by phdsg** [comment]
btw: huge thanks for this one :) finally some schwing :+1: 

...but what is sonar, if i may ask!?

**Comment by sebastien-bouffier** [comment]
thanks for Linux dist phdsg. Sonar was at the beginning a test to make a pseudo random generator ... the idea was to hear what the web sounds like so you had to input an url and the html was translated to CV based on characters codes ... funny but not very useful. I t allowed me to work with curl for the first time. I trashed the code and started another test to build waveforms based on pictures, nothing really new again ... and suddenly I had the need of a very simple swing tool for a track so I stopped SONar and made lATe :)

**Comment by phdsg** [comment]
whoa, what does a website sound like!?
you are playing with curl :) reminds me that someone (i think on the fb-group) asked if it's possible to have a module that connects to something like this: http://websdr.ewi.utwente.nl:8901/

**Comment by sebastien-bouffier** [comment]
web sounds like ... it depends ... google.com which is a very short page can lead to identify a kind of pattern ... imdb.com .. a mess :) I don't know if connecting to something like http://websdr.ewi.utwente.nl:8901/ is feasible. I looks like it is based on web audio API and not sure that managing callbacks with curl is feasible.

**Comment by sebastien-bouffier** [comment]
As usual thanks a lot phdsg

**Comment by phdsg** [comment]
0.5.11 Happy New Year
[Bidoo-0.5.11-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1595798/Bidoo-0.5.11-lin.zip)

**Comment by sebastien-bouffier** [comment]
Happy new year too :) thanks for lin dist

**Comment by phdsg** [comment]
0.5.12
[Bidoo-0.5.12-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1596415/Bidoo-0.5.12-lin.zip)

**Comment by phdsg** [comment]
0.5.14
[Bidoo-0.5.14-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1597986/Bidoo-0.5.14-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks

**Comment by phdsg** [comment]
0.5.15
[Bidoo-0.5.15-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1601963/Bidoo-0.5.15-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks a lot

**Comment by phdsg** [comment]
0.5.16
[Bidoo-0.5.16-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1609341/Bidoo-0.5.16-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks again :)

**Comment by phdsg** [comment]
0.5.17
[Bidoo-0.5.17-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1640701/Bidoo-0.5.17-lin.zip)

had to make dist from master, the Makefile in the 0.5.17 release still has 0.5.16 in it.
also i get warnings because of the make system changes.

**Comment by sebastien-bouffier** [comment]
hello ok didn't pay attention to that .. I will fix thanks again as usual.

**Comment by phdsg** [comment]
no worries.
another thing (that could be a browser thing too, still checking):
somehow the updated pack.png doesn't show up anymore on the main page of the repo.
only the link. which opens the image, so it's there and i don't know what's wrong. i took a look at the readme.md but couldn't find anything....

**Comment by sebastien-bouffier** [comment]
make file updated ... strange I was sure that I updated the version number ... it is clean now and in line with Andrew's last plugin makefile. Regarding pack.png I did a test and it confirms what I thought .... size matters .... no comment. I will upload a new distrib to make sure that it is conform with Rack standard.

**Comment by phdsg** [comment]
0.5.18 (*)
[Bidoo-0.5.18-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1669519/Bidoo-0.5.18-lin.zip)

(*) fixed the include thing i mentioned in the other issue.u

**Comment by sebastien-bouffier** [comment]
thanks a lot as usual :)

**Comment by phdsg** [comment]
hate to be that guy, but there's another typo:
```
index 2e54be9..13df8ae 100644
--- a/src/dep/filters/biquad.cpp
+++ b/src/dep/filters/biquad.cpp
@@ -17,7 +17,7 @@
 //
 
 #include <math.h>
-#include "Biquad.h"
+#include "biquad.h"
 
 Biquad::Biquad() {
     type = bq_type_lowpass;
```
other than that, great new modules...  
[Bidoo-0.5.19-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1671594/Bidoo-0.5.19-lin.zip)

**Comment by sebastien-bouffier** [comment]
thanks, I don't understand how I can compile and link with those kind of typo .... as usual a big thanks phdsg

**Comment by phdsg** [comment]
i think the windows fs isn't that picky when it comes to capitalization.

**Comment by phdsg** [comment]
[Bidoo-0.5.20-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1691068/Bidoo-0.5.20-lin.zip)

**Comment by sebastien-bouffier** [comment]
with the checksum ... royal ... big thanks

**Comment by phdsg** [comment]
so, where is the `mpg123.h` ???

```
src/ANTN.cpp:7:20: fatal error: mpg123.h: No such file or directory
 #include <mpg123.h>
                    ^
compilation terminated.
../../compile.mk:53: recipe for target 'build/src/ANTN.cpp.o' failed
make: *** [build/src/ANTN.cpp.o] Error 1

```

**Comment by phdsg** [comment]
[Bidoo-0.5.22-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1747505/Bidoo-0.5.22-lin.zip)

sha256sum:
`f30ccc9b23ab675fdcef7dcb1d38f2be2cef8a8120e20566deed4aa7d813ad64  Bidoo-0.5.22-lin.zip
`

**Comment by sebastien-bouffier** [comment]
Thanks a lot. Is there any specific command on Linux ? My make dist fails

**Comment by phdsg** [comment]
odd. i just make dist. what does yours say?

**Comment by sebastien-bouffier** [comment]
make dist
make: *** No rule to make target 'dist'.  Stop.

**Comment by phdsg** [comment]
oh, that probably means that your rack-build is still on the old make system while your Makefile is already using the new format.

**Comment by sebastien-bouffier** [comment]
yep maybe now I will checkout the last version of master and start the migration process for 0.6 ... but still thinking of a groove machine/clock , I got several ideas/needs but I still need to work on it.

**Comment by phdsg** [comment]
0.6 will probably get delay for another 2 weeks (mid march i guess) to get 3rd party plugins integrated into the "new" plugin manager.

**Comment by sebastien-bouffier** [comment]
ok so I have a little bit of work for the next couple of weeks

**Comment by phdsg** [comment]
if you do 0.6 by yourself, might wanna say hello in the repair team issue so your list entry gets a check mark.

**Comment by phdsg** [comment]
here's the latest...
`c21ccfecfebbc36397adbca52f747e50a6233036  Bidoo-0.5.23-lin.zip
`
[Bidoo-0.5.23-lin.zip](https://github.com/sebastien-bouffier/Bidoo/files/1754774/Bidoo-0.5.23-lin.zip)

**Comment by phdsg** [comment]
0.5.23 the last v0.5 release, right? let's close this and we'll do a new one for 0.6 if needed.

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
