### ISSUE TITLE
BaR / MiniBar visual feedback enhancement

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#160]
Hi Sebastien!

Currently the behavior for the compressor is when we use the side-chain input this turns of the visual feedback of the compressor signals,
and only shows up when the side chain input is triggered/active.
Could you please make it so that the compressor signals stay visible but sort of dimmed or grey, while retaining the side chain visual feedback?

Let me know if this makes sense what i try to explain.
Else i'll photoshop it in an example :)

Cheers,
Latif

**Comment by sebastien-bouffier** [comment]
Hi, @Eurikon available in 1.1.23 for baR, miniBar is more tricky since the ui is very small. I will do minibar in 1.1.24.
Best

**Comment by sebastien-bouffier** [comment]
mINIBar pushed in 1.1.24

**Comment by Eurikon** [comment]
Thanks so much for doing this!
Is there a nightly build link? Or is it already on its way to the plugin manager?

All the best,
Latif

**Comment by sebastien-bouffier** [comment]
Hi, it will be available once the magic VCV plugin team will have checked and built the commit.
They are really great and from my experience there is never more than few days (1 or 2) between the push and the availability in VCV.
Best.

**Comment by sebastien-bouffier** [comment]
please close the thread if you are satisfied with the update
cheers
