### ISSUE TITLE
Add URLs to individual module manuals

### ISSUE THREAD

**Issue by AndrewBelt** [sebastien-bouffier/Bidoo#162]
OS (if applicable):
Version (or "dev" if compiling from source): dev 2cfa351

Rack and the VCV Library support per-module manual URLs. Simply add a `"manualUrl"` property to each module object in the `plugin.json` manifest. https://vcvrack.com/manual/Manifest#modules-manualurl Example:
```json
    {
      "slug": "liMonADe",
      "name": "liMonADe",
      "manualUrl": "https://github.com/sebastien-bouffier/Bidoo/wiki#limonade",
      "description": "Wavetable oscillator station & additive synth",
      "tags": [
        "Oscillator"
      ]
    },
```

**Comment by sebastien-bouffier** [comment]
Hi @AndrewBelt changed in 1.1.23
Best,
