### ISSUE TITLE
iATe does something to the gates

### ISSUE THREAD

**Issue by nnbveh** [sebastien-bouffier/Bidoo#166]
OS (if applicable): mac os 10.15.7
Version (or "dev" if compiling from source): 1.1.28

HI, 

If i go from uGraph sequencer directly to the envelopes etc my sound is loud and clear, but if i go to the swing module first sound becomes super quiet, although i can see it's still triggering things...hard to exlpain really, but this started to happen few days ago, before it was working fine...
<img width="1536" alt="Screen Shot 2020-10-31 at 09 48 43" src="https://user-images.githubusercontent.com/39271290/97773134-34301280-1b88-11eb-987d-94b0609b9063.png">

**Comment by sebastien-bouffier** [comment]
Hi @nnbveh this is strange since lATe's code didn't change since a long time. I will try to reproduce your issue, maybe you could send me your patch. I will check if something changed in Rack framework too ... Stay tuned.
