### ISSUE TITLE
zOu MAi loses clock sync on pattern change

### ISSUE THREAD

**Issue by efthymik** [sebastien-bouffier/Bidoo#167]
Hello Sebastien,

First of all a giant thank you for the wonderful plugins and your kind contribution to the community!

Unfortunately this issue is not consistently reproducible. The pattern-change synchronization loss occurs randomly and I am perplexed as to how to overcome it. Because zOu Mai is amazing and this issue prevents my live performance :-(

I see that the start position resets to the beginning beat every time a pattern change is triggered. But sometimes this results in falling back maybe a 16th of a note compared to other synchronized running sequencers in parallel. Even though the change was sent in a correctly quantized time.

To trigger the pattern changes correctly timed I use sample-and-hold. But even though the change is triggered correctly, zOu Mai probably takes some time to process it and may lag behind by restarting the pattern with a light delay.

**Comment by sebastien-bouffier** [comment]
Hi sorry to come back to you so late but I was away from Rack for a period. I made an update to zOu with sync enhancements  so let me know if you still face sync issues.
Best

**Comment by efthymik** [comment]
Hello Sebastien!

I am apologize as well for being awol :-) I will try the new updated zOu MAi and get back to this thread with news. Thanks again!
