### ISSUE TITLE
cARNARD not working?

### ISSUE THREAD

**Issue by ghost** [sebastien-bouffier/Bidoo#169]
HI for some reason I cannot load multiple samples nor add slice markers in this

**Comment by sebastien-bouffier** [comment]
Hi @ghost sorry to be so late but I have been away for a long time.
cANARD is not designed to handle multisamples.
You can import a wav file and add slice markers manually or use the transient detector.
You can record in loop mode (each time the loop is replaced) or in stack mode (records are stacked and separated by slice markers)
That is the way I designed cANARD. If you want to play multi samples Nysthi has a great sample player.
Cheers
