### ISSUE TITLE
Question on Bidoo Moire behaviour

### ISSUE THREAD

**Issue by firolightfog** [sebastien-bouffier/Bidoo#170]
Hi,
I thought to post the [question](https://community.vcvrack.com/t/question-on-bidoo-moire/13951) to this forum also. The original one is on the VCV Community page.
Basically the issue I see is that using a square wave allows me looping through the patterns with this patch. On the other hand if I use a raw wave (to achieve nice slide between the scenes) Moire behaves inreliably. Timing is off, stepping is messed up sometimes. How does that input work exactly? The scene numbers are meant to be changed the same way on both Moire, aren't they? What did I miss? 

[Sample patch](https://community.vcvrack.com/uploads/short-url/134H586l5GPkGOhYqSrNhDzGzP7.vcv)
![image](https://user-images.githubusercontent.com/34127628/131285614-5d0e75b0-7ba8-490a-a39f-66ad3ca10f91.png)

Many thanks, Andras

**Comment by sebastien-bouffier** [comment]
Hi @S0210,

MOiRE was design a long time ago :) and my principal goal for that module was to jump or morph "manually" between scenes. 
It is mostly how I use it but I made some patches where it is automated by other modules.
I never use MOiRE outputs to specify my scenes sequence but I delegate it to other modules.
I join a patch to that reply and I hope it will help you to achieve what you want. 
You will see two MOiRE working in two different situations i.e. the first one "scrolls" between chosen scenes and the second one is more chaotic.

Best.

[question on Bidoo Moire v2 maybe an explanation.txt](https://github.com/sebastien-bouffier/Bidoo/files/7144718/question.on.Bidoo.Moire.v2.maybe.an.explanation.txt)

Just changing the extension from txt to vcv should be enough to open the file with Rack

**Comment by firolightfog** [comment]
Yes, manually it works wonderfully. I wanted to save the extra module but probably it's a good idea. I checked your patch and I think I see what you mean. It is indeed the behavior that confused me. I just don't know yet how to get around it but I'll figure out something. I like Moire too much. :)  

I wish you were secretly considering an additional feature like this: 
![image](https://user-images.githubusercontent.com/34127628/132959991-2bea8054-1a6d-4623-b5dd-c5e8db711748.png)

The auto slide could be switched OFF (current mode) or ON. If it's switched ON then the new knob would automatically (range: 0-10 seconds) slide to the recently changed scene. 

I hope you have an empty slot on your "potential future module enhancements list" for something like this. ;)

Cheers, Andras

**Comment by sebastien-bouffier** [comment]
I will do my best, need to think about it before coding (trigs, sync, use
case etc...)
Best
Seb

**Comment by sebastien-bouffier** [comment]
πlOT is released
