### ISSUE TITLE
Proposal to Bidoo Moire enhancement

### ISSUE THREAD

**Issue by firolightfog** [sebastien-bouffier/Bidoo#171]
Dear Sebastien,

Currently each control of Moire can have two modes: Morph or Target. Would you please consider adding a third mode: Trigger? 

`"types": [ 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]`

* Morph = light off -> the value of the control will be rescaled all along fader movements
* Target = red light on -> the value of the control will be updated only when the fader reaches the highest value
* Trigger = yellow light on -> a single 10V pulse is sent when the fader reaches the highest value

Best regards, Andras

**Comment by sebastien-bouffier** [comment]
Hi @S0210 good idea. Thanks

**Comment by sebastien-bouffier** [comment]
1.1.33 a new module is available => πlOT which is a MOiRE ++
Features are available in the wiki.

**Comment by sebastien-bouffier** [comment]
πlOT is released

**Comment by firolightfog** [comment]
The feature set of πlOT is brilliant! Thank you! 
![image](https://user-images.githubusercontent.com/34127628/134671991-8ace406a-c111-4432-9629-cf3703688c59.png)
Although the layout is a bit messy. :)

**Comment by sebastien-bouffier** [comment]
I was far more exited by making the features alive rather than spending too much time on the UI :) the only thing I wanted at this stage was to make as many controls available and usable (size) as possible. I will rework the UI in a next release. Thanks :)

**Comment by firolightfog** [comment]
Oh, the new look is so much better! Thank you!

And adding LFOs to the curve input it's really funny. It looks like a worm in a box. :D
![image](https://user-images.githubusercontent.com/34127628/134936732-25e27986-a88d-481f-aac5-183860bae2d8.png)
_(I'm sure that you appreciate greatly this comment both from coding and musical point of view.)_

**Comment by sebastien-bouffier** [comment]
Thanks a lot :) take a look at the wiki, controls and sequencer can do a little more than the previous version.
