### ISSUE TITLE
How to operate Zou Mai CV in?

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#172]
Hi Sebastien! How to use input CV mode in Zou Mai? Just connected Gate and 1v\oct and push REC button but seems nothing was happened. I'm sure I'm doing something wrong :-)

**Comment by sebastien-bouffier** [comment]
Hi sorry for this late reply. I join a sample file (change txt to vcv).
[zoumai rec.txt](https://github.com/sebastien-bouffier/Bidoo/files/7232215/zoumai.rec.txt).
Click on RUN on Tocante and once both sequencers are in sync push on record for a loop or two, then zou should record dtroy's pattern.
I made several tests when I was working on that feature with my mpc controller but the midi-CV seemed a little bit too slow and it was not really playable. But I kept the feature.
I have fixed the issue that occurs when clearing a trig it will be pushed soon.
Take a look @ pilot my new module it si fun :)
Cheers
