### ISSUE TITLE
Proposal to Moire enhancement [quick keys]

### ISSUE THREAD

**Issue by firolightfog** [sebastien-bouffier/Bidoo#173]
Dear Seb,
Currently Ctrl-R randomizes everything. Could you please consider the introduction of a quick key (i.e. 'r') that would _randomize the current scene only_? (Practically changing the 16 knobs & leds only...)

![image](https://user-images.githubusercontent.com/34127628/134067082-887cd0df-8d90-4231-9644-0dd7a27449ca.png)

Best regards, Andras

**Comment by sebastien-bouffier** [comment]
Available in 1.1.33 just pushed. I have added a button on the side of save in order to randomize the target scene.

**Comment by sebastien-bouffier** [comment]
released with πlOT at the same time

**Comment by firolightfog** [comment]
Available in the Library. 
Works wonderfully! 
Thank you Seb!
