### ISSUE TITLE
v2 - antN doesn't work

### ISSUE THREAD

**Issue by jpnielsen** [sebastien-bouffier/Bidoo#175]
v2 dev built from source, on Windows 10 - Rack 2.git.5c47e6e0

antN: No movement in VU meters - No sound

tested with a few streams
http://live-icy.dr.dk/A/A03H.mp3.m3u
https://somafm.com/deepspaceone.pls

**Comment by sebastien-bouffier** [comment]
Hi 
http://live-icy.dr.dk/A/A03H.mp3 this one works I may have some issue parsing m3u and pls files
I will fix it, stay tuned

**Comment by sebastien-bouffier** [comment]
fixed and pushed, let me know if it works on your side.
thanks for testing and your interest in bidoo's module :)

**Comment by jpnielsen** [comment]
Works great now.

Thank you
