### ISSUE TITLE
Enable visuals for displays in light-off mode V2

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#179]
Hello friend!

Can you please make the compressors show their screens/displays in light-off mode? :)

VCV Rack V2

**Comment by sebastien-bouffier** [comment]
Hi, available in 2.0.0.13 just pushed

**Comment by Eurikon** [comment]
Thanks!!

**Comment by Eurikon** [comment]
Hi Sebastien,

Steve and i tried this on mac last night, but no change in the displays yet.
They still go dark.

**Comment by sebastien-bouffier** [comment]
Hi I did not noticed that there was a change in V2's reco 
Last push should fix it.
Best

**Comment by Eurikon** [comment]
![Screenshot 2021-11-09 at 15 54 30](https://user-images.githubusercontent.com/40998416/140947385-d5101852-48ef-4eb0-98eb-98f1647d3552.png)


Great Sebastien., thanks!

Cheers,
Latif

**Comment by sebastien-bouffier** [comment]
great
