### ISSUE TITLE
AntN: graphic bug

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#180]
VCV V2
Mac OS
I noticed this when starting a stream:

![Screenshot 2021-11-12 at 16 44 20](https://user-images.githubusercontent.com/40998416/141494115-fa928bd4-a177-4e32-b9f3-15e804b02a81.png)

There was no sound playing after pressing the trigger, 
what stream types are excepted?

**Comment by Eurikon** [comment]
Also noticed this with a playing link: 
![Screenshot 2021-11-12 at 16 49 26](https://user-images.githubusercontent.com/40998416/141495237-e54c5a48-6a08-4702-9e1d-c8556a18dec0.png)

Playback was very skippy :)

**Comment by sebastien-bouffier** [comment]
Hi, it seems that you made a test I never performed that consists in trying to read a file.
antN is designed to read radio streams so I think that in your case the file is pushed very quickly and the audio buffer is over fed ...
antN is supposed to read streams from URLs like those one :
http://fluxradios.blogspot.com/p/flux-radios-francaise.html
https://www.internet-radio.com/
antN can read streams from mp3 extensions and parse pls or m3u file too.

**Comment by Eurikon** [comment]
Hi Sebastien, ok thanks! Will keep it in mind when and if it happens again :)

I have had some streams play good as they should!

**Comment by Petervos2018** [comment]
Just saw this (copy from Eurikon) : wanted to make a screenshot and it was gone ...

![afbeelding](https://user-images.githubusercontent.com/46076474/144764514-477455f4-f6da-4393-a102-e9fccdb8726c.png)

So this still happens (sometimes) Windows 10 Bidoo v2.0.1

Just a heads up..

**Comment by sebastien-bouffier** [comment]
Hi @Eurikon and @Petervos2018 in 2.0.2 the buffers display won't go outside the module and I changed the buffer size so you should be able to listen to Paul Temple and the Geneva Mystery :)
This is a quick win because  AntN is originally designed to read continuous streams and I think I may make another module for huge mp3 files with read position capability, looping etc... maybe

**Comment by Eurikon** [comment]
Ok sweet! Thanks Sebastien :)

**Comment by sebastien-bouffier** [comment]
solved in 2.0.3
