### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pgatt** [sebastien-bouffier/Bidoo#182]
OS (if applicable): Mac
Version (or "dev" if compiling from source): dev

Hi, I don't know if you want to see this yet,

But I'm getting this error when trying to build latest against VCV 2 beta that was just released:

[0.668 warn src/plugin.cpp:170 loadPlugin] Could not load plugin /Users/paulgatt/Documents/Rack2/plugins/Bidoo: Failed to load library /Users/paulgatt/Documents/Rack2/plugins/Bidoo/plugin.dylib: dlopen(/Users/paulgatt/Documents/Rack2/plugins/Bidoo/plugin.dylib, 6): Symbol not found: _curl_easy_cleanup
  Referenced from: /Users/paulgatt/Documents/Rack2/plugins/Bidoo/plugin.dylib
  Expected in: flat namespace
 in /Users/paulgatt/Documents/Rack2/plugins/Bidoo/plugin.dylib

**Comment by pgatt** [comment]
This may or may not be relevant:

https://github.com/VCVRack/Rack/commit/05fa24a72bccf4023f5fb1b0fa7f1c26855c0926

**Comment by Torinbob** [comment]
I'm getting same thing on Mac - compiles fine but modules do not show up in browser

**Comment by sebastien-bouffier** [comment]
Hi dear users, musicians, we are in the period of transition between tow major versions and all feedback is more than welcome.
Many things may produce unavailability of modules and I will do my best to solve them asap.
I understand that the issue raised concerns antN since it is the sole plugin using CURL lib.
SSL issue may be linked to CURL issue so I will dig into that direction.
Stay tuned.

**Comment by cschol** [comment]
@sebastien-bouffier We looked into this and this is an issue with the current Rack beta (missing `curl` symbols in `libRack.so`) and will be fixed in the next Beta release.

**Comment by sebastien-bouffier** [comment]
@cschol thanks, I did a check on the new version of curl in /dep and easy methods (easy_cleanup etc...) are still available so no downgrade on that part. Is it something already fixed or do you want me to try to fix it ?

**Comment by cschol** [comment]
No action required from your side. It will be fixed in the next Beta release.

**Comment by gitterdude** [comment]
The quick-n-dirty hack, just to get the plugin to work until there's a proper fix, is to add  `-lcurl` to the final linking stage; presuming libcurl.so is installed on the system.

Change  `LDFLAGS += -shared` to `LDFLAGS += -shared -lcurl` in Rack/plugin.mk, remove any existing plugin.so in the Bidoo directory and recompile
