### ISSUE TITLE
proposal: more options for Flame

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#184]
Hi Sebastien ! I'm enjoying the new v2 version of Bidoo. The Flame module is very nice in Lights Off mode, but I wondered if you could add some options for varying the FFT and the color scheme. Might be very cool. :) 

Best regards,

dp

**Comment by sebastien-bouffier** [comment]
Hi, good idea :) have you noticed that you can select a rectangle in the fft to generate a magnitude density CV output ?

**Comment by davephillips** [comment]
I noticed the rectangle but didn't know what it does. Now I know. :) Very cool !

**Comment by davephillips** [comment]
Hey, I noticed the neat new features for FLAME. Thank you, Sebastien ! :+1:

**Comment by sebastien-bouffier** [comment]
you are welcome
