### ISSUE TITLE
v2: Slug changes detected

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#185]
```
[Bidoo] Validating plugin.json...FAILED
[Bidoo] Issues found in `plugin.json`:

Slug changes detected: cuRt, clACos, FFilTr, Garcon, PeNEqUe
```

It looks like a few modules were removed and one slug (Garcon) was changed.

Slug changes are **NOT** allowed since it would break backwards compatibility.
Also, I want to make sure that the removal wasn't an accident.

Thank you.

**Comment by sebastien-bouffier** [comment]
Hi @cschol  I understand the issue regarding backward compatibility but I removed them intentionally.
My modules are not on the top list of mainstream modules and the most used are my sequencers, antN (some people need this one to be robust and available), my compressors and my filters. I consider my plugins as a kind of VCV niche :)
The modules I have removed are those that I have never seen being used and that I used as sandbox for self educating purpose so I didn't think it would be an issue.  For example you can do the same thing as PeNEqUe with liMonADe and much more. 
Tell me if it is show stopper for v2 migration and I will make them available again.
Best regards.

**Comment by cschol** [comment]
I understand. Removing modules is fine. I was just checking if that was intentional because there was quite a few.

Changing the slug of `Garcon` is not possible though. Did I see correctly that that one changed? Is is possible to change that one back?

**Comment by sebastien-bouffier** [comment]
I replaced Garçon with fLAME but I can make them available at the same time.

**Comment by cschol** [comment]
Ah, so Garcon is removed and fLAME added. I see. That is OK, I think. Thank you for the clarification.

**Comment by rafaelferreiraql** [comment]
Very old and closed post but I want to say I liked clACos and miss it. It allowed me to neuro with a single oscillator and that was pretty neat.
