### ISSUE TITLE
fLame v2 always there...

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#187]
Hi Seb,

![afbeelding](https://user-images.githubusercontent.com/46076474/144727439-e62ac781-284e-4d40-9717-cd9eb28783b1.png)

![afbeelding](https://user-images.githubusercontent.com/46076474/144727443-dd832eff-ac05-47ae-b6ed-0304b3be23d3.png)

fLame is always shining (through)...

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter, I can hardly reproduce the issue depending on the zoom level. 100% nothing, more than 200% it happens on the right click menu but not as visible as your example, just few lines are over the menu ... what is your OS ?

**Comment by Petervos2018** [comment]
Windows 10 and it's only visible if you don't run any audio through it.

![afbeelding](https://user-images.githubusercontent.com/46076474/144759864-89d3a2fb-2e15-4583-95ed-514f26b693bf.png)

there is no problem when audio is ran through it ( as seen on the picture).

**Comment by sebastien-bouffier** [comment]
On my side with the dev environment it only happens if zoom is not 100%. @ 100% with or without audio there is no problem ... I dig into it

**Comment by sebastien-bouffier** [comment]
Hi in 2.0.2 I removed drawing when not connected, changed the way coordinates are computed and it seems to be better. Tell me.

**Comment by sebastien-bouffier** [comment]
Just found the real issue.
When a shape has a 0 height nvgFill can produce "bleeding" outside of the path and some artifacts appear.
To avoid that issue add `nvgShapeAntiAlias(args.vg,false);` in the `drawLayer` method.

**Comment by sebastien-bouffier** [comment]
solved in 2.0.3

**Comment by Petervos2018** [comment]
Bravo, I think this solved more than only the fLAME module.
Thank you 👍

**Comment by sebastien-bouffier** [comment]
great :)
