### ISSUE TITLE
Are Attack and Decay switched on baR Compressor?

### ISSUE THREAD

**Issue by MaZe6K** [sebastien-bouffier/Bidoo#189]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 2.0.3

Hi!
It seems to me that the Attack and Decay knobs on the baR compressor are switched up, the Attack knob seems to control the Decay and vice versa.

**Comment by sebastien-bouffier** [comment]
Hi @MaZe6K yes you are right !!! never paid attention to that swap i will fix. Thanks

**Comment by sebastien-bouffier** [comment]
released in last update
