### ISSUE TITLE
Permission request for runtime dark mode

### ISSUE THREAD

**Issue by falkTX** [sebastien-bouffier/Bidoo#191]
Just a quick question.
You graphics/artwork is licensed under `CC BY-NC-ND 4.0` which does not allow derivatives.

It is unclear to me if applying color inversion at runtime, without ever modifying the original files, is to be considerate derivative work or not.
To not make things complicated and boring, I thought to just ask your opinion on the subject, if you are okay with such color changes at runtime.

Let me show you the result:

![Screenshot_20220122_234020](https://user-images.githubusercontent.com/1334853/150659025-5d8cc09b-6716-4246-8401-0579f089863e.png)

What do you think? Is this usage ok with you, or you rather not see them "changed" in any way?

**Comment by sebastien-bouffier** [comment]
Hi Filipe, implementation of changing theme colors at runtime has started few weeks ago. I will release it soon. Your proposal looks fine and if you prefer using those versions that is ok for me.

**Comment by falkTX** [comment]
Thanks for the reply, very nice to know this use is okay with you :)

I am curious to see how it looks on your side, can you share an early screenshot?
If I dont have to maintain a dark mode on my side would be good for the long term, thanks a lot for choosing to implement a dark mode! My eyes surely appreciate it haha

**Comment by sebastien-bouffier** [comment]
it looks like that
![image](https://user-images.githubusercontent.com/1842599/151273243-017b4234-f463-4c3a-93d8-fc982aa22673.png)
you will have a dark mode which is a dark gray and full black

**Comment by falkTX** [comment]
that looks good! I like the more grey-ish variant vs the full back one.
text becomes hard to read though, will need to be made white somehow.

btw, I will close this ticket since I really just wanted to ask about permission for the dark mode runtime thingy.
I will enable that for the time being until you finish the official dark mode.
Feel free to ping me if/when you need testing.

Thanks again!
