### ISSUE TITLE
bordL latching SK / SL buttons and Play / Count feedback

### ISSUE THREAD

**Issue by chairbender** [sebastien-bouffier/Bidoo#193]
I have built a UI in OpenStageControl for bordL, using OSC'elot for mapping (planning to share once it's all complete, for the interested). bordL works really well with this setup because all of the sequencing-related controls update when I change the edited track, for example, so I can just about use it entirely from my custom UI on a tablet without glancing at VCV, which is great for a live performance setup. 

One exception to this is the SK / SL buttons. It would be nice if they latched so that I can get feedback into OSC on their current state, rather than current behavior where they are pressed and always remain at value "0" despite appearing lit or unlit.

The Play / Count buttons also don't provide this sort of feedback. It would be great if there was a way I could get the currently selected "playback mode" and "count mode". But I am not sure how it would work especially for Play, with it being a button (is it possible for a single button to cycle/latch through multiple values rather than just 0 / 1? If so, that could work for me). I just would want a way so I can indicate the current playback and count mode in my OSC UI without having to "assume".

**Comment by sebastien-bouffier** [comment]
Hi, I was afk for some days I take into account your need. Best.

**Comment by sebastien-bouffier** [comment]
Hi, just pushed 2.0.9
bordL has new buttons for skip, slide, play mode and count mode so you should be able to map them via OSC.
If you confirm that it works on your side I will apply that change on dTrOY in a further release. 
best

**Comment by sebastien-bouffier** [comment]
Hi @chairbender please let me know if last updates enable you to drive bordL via OSC as expected so i can close the issue.
Best.

**Comment by chairbender** [comment]
> Hi @chairbender please let me know if last updates enable you to drive bordL via OSC as expected so i can close the issue. Best.

Just tested it out, works great, exactly how I was hoping 👍
