### ISSUE TITLE
Persistent theme color in browser and as default

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#194]
Hi, Sebastien.
Thanks a lot for adding the color themes!! I had not noticed yet till today :D 
Saves me a lot of time to keep editing the svg's with every new update hahah.

So, in an ongoing effort to get many developers to make there plugins behave the same with themes, i wanted to ask you for the following:

With other plugins that provide the option for changing and saving the default theme colour,
those plugins represent their module screenshots in the browser in the saved default colour.

ie: when a module its default is set to dark themed, all the modules in that plugin show up as dark themed in the browser.

Some plugins with such behaviour:
Impromptu
Bogaudio
Geodesics
Surge
Submarine
Count Modula

These plugins modules also retain the default color when inserting a new instance, as they allow it to be the default. 

Would be really nice if your plugin modules followed this behaviour as well.

Cheers!
Latif

**Comment by sebastien-bouffier** [comment]
Hi, just pushed 2.0.9.
When setting a theme on a module it becomes the default theme for all others that will be opened. 
Modules are drawn with the default theme at the first use of the browser.

**Comment by Eurikon** [comment]
Hi Sebastien, 
the update finally arrived today in the library!

All looks well and works well here :D 
(Mac OS)
Thanks for adding this feature.

**Comment by sebastien-bouffier** [comment]
Great I close the issue.
Best regards
