### ISSUE TITLE
Update plugin.json to refer to changelog on v2 branch

### ISSUE THREAD

**Issue by hemmer** [sebastien-bouffier/Bidoo#196]
https://github.com/sebastien-bouffier/Bidoo/blob/a13d5db5ac470f484d1f4c4e0f96deffdb4503de/plugin.json#L13

Tiny change, but the changelog link refers to the v1 version. :)

**Comment by sebastien-bouffier** [comment]
Hi it is fixed in 2.0.13
Best

**Comment by hemmer** [comment]
Nice one!
