### ISSUE TITLE
Feature request Zou Mai Run button and bipolar CV

### ISSUE THREAD

**Issue by omricohenmusic** [sebastien-bouffier/Bidoo#199]
Hi!
It took me a while but I just discovered the beauty of Zou Mai and I had a couple of thoughts. Will it be possible to have a Run button instead of having to use an external signal? It will make things a bit easier I guess. Also, is there a way to make the CV outs bipolar? Sometimes I find myself wanting to close the decay of a sound, or the filter, but it will only output positive voltage so there's a need to either set the initial position of the parameter lower, or to use an inverter externally. 

Thank you so much!

**Comment by sebastien-bouffier** [comment]
Hi @omricohenmusic !!!
I will push soon the 2.0.14. It contains a new button in order to start the sequencer alongside to the dedicated input. CV1and CV2 have a new range from -10V to 10V so you will be able to automate things more freely. I do not know if you use the expander, if no, take a look at it, you can mangle each track at run time. 
Best.

**Comment by omricohenmusic** [comment]
Oh nice, thanks so much 🙂 And yes, I think the expander is great. I did a short video about it also 🙂 https://youtu.be/A6M349T_uNs
Thanks again!
[https://i.ytimg.com/vi/A6M349T_uNs/maxresdefault.jpg]<https://youtu.be/A6M349T_uNs>
Elektron style sequencing \\ Quick Tip<https://youtu.be/A6M349T_uNs>
You can find a walkthrough video of this sequencer together with many other exclusive videos and content on my Patreon page - https://www.patreon.com/posts/p...
youtu.be

________________________________

**Comment by sebastien-bouffier** [comment]
Thanks so much for your video and glad to see that you have good time with zOù MAï :)

**Comment by omricohenmusic** [comment]
Yeah, I'm so happy I finally started using it. And thanks so much for the update!On May 21, 2022 09:02, bidoo ***@***.***> wrote:

Thanks so much for your video and glad to see that you have good time with zOù MAï :)
