### ISSUE TITLE
[feature request] dTrOY: external gate modes/inputs as on the DU-SEQ

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#2]
watching some demo videos for the metropolis hardware, i came across a kind of similar module.
the detroit underground du-seq, has two additional gate modes for each step to choose from one
of two external gate inputs. this can be used to replace the internal gate signals that fire at each pulse
with the ones from the inputs.

here's the example: https://youtu.be/dtj4IQCt1JU?t=13m8s

i think this would be a nice addition to your already awesome seq.

let me hear what you think.
thx

**Comment by sebastien-bouffier** [comment]
Hey, didn't know this seq and this is an awesome idea ... mmm gonna work on it :)

**Comment by sebastien-bouffier** [comment]
Hey, didn't know this seq and this is an awesome idea ... mmm gonna work on it :)

**Comment by phdsg** [comment]
thanx for picking this up. really looking forward to that.
this module is already so good i use it in almost every session.
thats why i spent some time in inkscape to make a darker version for less stress during longer sessions.
![dtroy_dark](https://user-images.githubusercontent.com/33329578/32567169-c6dac12a-c4ba-11e7-8b0a-712f92f3145f.PNG)

**Comment by phdsg** [comment]
thanx for picking this up. really looking forward to that.
this module is already so good i use it in almost every session.
thats why i spent some time in inkscape to make a darker version for less stress during longer sessions.
![dtroy_dark](https://user-images.githubusercontent.com/33329578/32567169-c6dac12a-c4ba-11e7-8b0a-712f92f3145f.PNG)

**Comment by phdsg** [comment]
thanx for picking this up. really looking forward to that.
this module is already so good i use it in almost every session.
thats why i spent some time in inkscape to make a darker version for less stress during longer sessions.
![dtroy_dark](https://user-images.githubusercontent.com/33329578/32567169-c6dac12a-c4ba-11e7-8b0a-712f92f3145f.PNG)

**Comment by sebastien-bouffier** [comment]
Gates 1 and 2 done :)
Nice skin :)

**Comment by phdsg** [comment]
wow. that was impressively fast.
so far working as expected.
thank you so much.

**Comment by sebastien-bouffier** [comment]
it was much more a gui rework than dsp so .. and it is a very cool and useful feature that I wanted to test :)
Thanks for sharing the idea.
