### ISSUE TITLE
Issue with bidoo modules saving samples in cardinal.

### ISSUE THREAD

**Issue by TheGuyWhoo** [sebastien-bouffier/Bidoo#202]
OS (if applicable): linux mint 20.
Version (or "dev" if compiling from source): https://github.com/CardinalModules/Bidoo/tree/9440a7f2bcd6a3f8678b013d2274d2061088833b

I mentioned it to the dev of Cardinal [here](https://github.com/DISTRHO/Cardinal/issues/236) and he thinks it might be a bug in the modules.

**Comment by sebastien-bouffier** [comment]
Hi @TheGuyWhoo I just downloaded Cardinal and I admit yes samples are not loaded ... It works fine with VCV 2.0 and Reaper under W10 ... I will take a look at the changes made on my plugins for Cardinal and try to find the bug.
Best

**Comment by TheGuyWhoo** [comment]
Thank you, that is very much appreciated!

**Comment by sebastien-bouffier** [comment]
Hi @TheGuyWhoo I have received an email from @falkTX saying that this issue is fixed in Cardinal.
Thanks to Filipe.
