### ISSUE TITLE
zOù MAï pattern step size CV not 10/8 but 10/7

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#203]
Hi Seb,

I noticed the the voltage needed for the pattern steps is not 10V/8 but 10V/7 and you can only reach step 8 by the full 10V.
Maybe you could change this to 10V/8 so there is pattern 1 : 0-1.24v pattern 2 : 1.25-2.49 pattern 3 : 2.50-3.74 etc 

Greetings Peter.

Then I could easily use it f.i. with this : 

![afbeelding](https://user-images.githubusercontent.com/46076474/178001059-aba84458-5a92-47d7-834a-f59ea27d7387.png)

this does not work right now because I can not reach step 8 (10V).

https://library.vcvrack.com/PdArray/Ministep

**Comment by sebastien-bouffier** [comment]
Hi @Petervos2018 I will take a look at this issue. Before multi CV/Pattern mappings are implemented I suggest you to try 8re module which is designed to command patterns changes on my sequencers.
Stay tuned.
Best

**Comment by Petervos2018** [comment]
Ah, so 8re is a manual selector that is clocked, to prevent glitches. Nice. But there is no way to step trough the 8 selections with automation, except with some stoermelder magic ;)
I think the only "strange" thing here is the 8 step sizes, 10/7 +10V or 10/8.
Thanks for looking into it.

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi it is pushed in 2.0.16, let me know if it works for you now.
Best

**Comment by Petervos2018** [comment]
I saw your post in the VCV library, it seems you/we were just too late.
BTW I'm not as kind as you think I am ;)

Best Peter.

**Comment by Petervos2018** [comment]
Hi Seb,

Thank you for implementing this for me, I updated to 2.0.17 and it works perfectly 🤗 

Greetings Peter.
