### ISSUE TITLE
bordL crashing Rack when attempting to insert it from the module browser into the rack on Windows

### ISSUE THREAD

**Issue by pgatt** [sebastien-bouffier/Bidoo#205]
OS (if applicable): Windows 10 & 11
Version (or "dev" if compiling from source): 2.0.15 and dev.

Hi Sebastien,

Paul from VCV Rack Support here, a user has emailed support saying that bordL is crashing Rack on Windows 10 when clicking on it in the module browser attempting to insert into the rack. I have verified and can reproduce here on Windows 11, and VCV Rack 2.1.2.

My log file is linked below:

[log.txt](https://github.com/sebastien-bouffier/Bidoo/files/9108179/log.txt)

Let me know if you need more information.

**Comment by sebastien-bouffier** [comment]
Hi Paul, the same issue has been raised on Linux few days ago, I have been able to reproduce it under W10 and I pushed a commit 2.0.17 few days ago that fix it under Linux and W10. Can you compile my module on your setup and make a test ?
Best.

**Comment by pgatt** [comment]
Hi Sebastien,

I've now tested 2.0.17 and the issue is confirmed resolved here.

**Comment by sebastien-bouffier** [comment]
Great.
