### ISSUE TITLE
Strange .gitmodules file in the repository

### ISSUE THREAD

**Issue by iv-m** [sebastien-bouffier/Bidoo#209]
OS (if applicable): all
Version (or "dev" if compiling from source): dev

Apparently, this repository does not have any submodules now, but `.gitmodules` file still exists in the current v2 branch (f67f81803140811c68926c0947002924a3085e0a). This may confuse some tooling.

**Comment by sebastien-bouffier** [comment]
Hi @iv-m thanks, this file is removed in my last commit.
Best.

**Comment by iv-m** [comment]
@sebastien-bouffier, thanks a lot.
