### ISSUE TITLE
dTroy Sequencer

### ISSUE THREAD

**Issue by Chaircrusher** [sebastien-bouffier/Bidoo#21]
OS (if applicable): All
Version (or "dev" if compiling from source): Dev

Thd dTroy Sequencer seems to change the pitch even if a step is turned off.  I work around this by using a sample & hold module to only set the pitch when a gate is emitted.

What I did (sample the pitch when a step sends a trigger) is the 'usual' way of doing something like this. If you want the existing behavior to be a possibility, maybe add a switch labeled 'continuous/triggered' that toggles between setting the pitch for every step, or setting pitch at note start.

**Comment by sebastien-bouffier** [comment]
Hello, just pushed a mod on dTrOY, pitch is out when gate is opened under tiggered mode. Tell me if it answers to your need or no. Not sure to understand well "at note start".

**Comment by sebastien-bouffier** [comment]
Last distrib 0.5.8 contains the upgrade on dTrOY.
