### ISSUE TITLE
rabBIT Ctrl-R

### ISSUE THREAD

**Issue by firolightfog** [sebastien-bouffier/Bidoo#214]
This is a shy enhancement request to enable the random function feature. It could be fun, imho...

<img width="259" alt="image" src="https://user-images.githubusercontent.com/34127628/192637881-0019a837-588e-4731-853a-cbfb3c0e431b.png">

**Comment by sebastien-bouffier** [comment]
Hi @firolightfog ok I will do it, it is quite simple but take care to your ears and speakers :)

**Comment by firolightfog** [comment]
Thank you! No worries, [Sonus Dept.](https://library.vcvrack.com/?brand=Sonus%20Dept.) [Bitter](https://library.vcvrack.com/SonusModular/Bitter) has already ruined my speakers as well as my hearing! :)

**Comment by sebastien-bouffier** [comment]
On its way for release in 2.0.23
