### ISSUE TITLE
After last update, Zou Mai triggers not responding to mouse click

### ISSUE THREAD

**Issue by technochitlin** [sebastien-bouffier/Bidoo#216]
OS (if applicable): win10
Version (or "dev" if compiling from source): 2.025

**Comment by Petervos2018** [comment]
Indeed you can not choose a trigger, Encore still works ;)

**Comment by Petervos2018** [comment]
Indeed you can not click a trigger.

**Comment by speckydarwin** [comment]
Absolutely, cannot click a trigger.

**Comment by sebastien-bouffier** [comment]
Fixed in last commit, sorry guys for the inconvenience. @technochitlin I can not reproduce the other issue you raised on enCORE. can you send me a sample project please ?

**Comment by technochitlin** [comment]
Wellll... now I can't duplicate it. Rack sometimes does some strange things to my setup, so I usually reboot and try again just to be sure, but when I tried to reproduce the two dead keys this morning they weren't dead.   ¯\_(ツ)_/¯

If it happens again in the future I'll send it along.

**Comment by sebastien-bouffier** [comment]
Ok thanks. I close both threads. Best.
