### ISSUE TITLE
Graphical glitch when zooming in on sample using cANARd sampler

### ISSUE THREAD

**Issue by GBaige** [sebastien-bouffier/Bidoo#219]
OS (if applicable): Windows 11
Version (or "dev" if compiling from source): 2.0.18 or whatever is included in VCV Rack 2 and Cardinal VST

When zooming in on sample using left-click and drag, the sample window will appear to stretch outside of the module's bounds.

![image](https://user-images.githubusercontent.com/115324169/202944854-c45b2202-9083-4345-92f6-7285e55aaa48.png)

**Comment by sebastien-bouffier** [comment]
Hi @GBaige I just pushed a fix. Let me know if you confirm it is ok on your side.
Best.

**Comment by sebastien-bouffier** [comment]
Update is available in VCV Rack, please close the issue if fixed.
Best.

**Comment by GBaige** [comment]
Thanks!
