### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by ValleyAudio** [sebastien-bouffier/Bidoo#22]
OS (if applicable): Mac
Version (or "dev" if compiling from source): 0.5.6

Hey. I've compiled a mac binary if you wish to add it to your release page.
[Bidoo-0.5.6-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1553790/Bidoo-0.5.6-mac.zip)

**Comment by sebastien-bouffier** [comment]
Thanks a lot Dale
