### ISSUE TITLE
Plugin manager

### ISSUE THREAD

**Issue by Phal-anx** [sebastien-bouffier/Bidoo#24]
I started to help Andrew with the plugin manager ;) 

somehow your zip file is corrupt.. if i compile it myself it works just nice without asking for an update (red dot) but if i choose yours on vcvrack.com (plugin manager) it will let me know that there is a "new" module pack available.. therefor something is not working right with your zip file.
i actually tried to make a new sha256 but this also didnt solve it...
when i tried to do "make dist" it cried error.. in case of creating a zip file

so if you need help to fix your module pack let me know e.g here or on FB (Struggl Michael)

**Comment by sebastien-bouffier** [comment]
Hello Michael I will try to fix it asap.

**Comment by sebastien-bouffier** [comment]
Just pushed 0.5.10 and updated my json in Community. Hope it will fix the issue. I tried to unzip the dist archive on my computer and it works fine, VirusTotal didn't see any issue on the zip file, sha key should be good too. Once the pull request on Community will be accepted I will perform a test to check if the update plugin light still appear. Best.

**Comment by sebastien-bouffier** [comment]
Andrew merged my pull request. I deleted all the content of my Documents/Rack/Plugins. Deselected all plugins from my account on the website ... As expected I only have Core and Fundamentals plugins but ... but ... but ... red light still there. So it will be difficult to say if it is an issue on my pack.
Best.

**Comment by Phal-anx** [comment]
write you here now again as you mentioned that you are not that much on FB ;)
your package is now fixed (no more red dot)

please, always change the version number in your json file aswell when you make a pull request..
looks like we all have overseen this :)

**Comment by sebastien-bouffier** [comment]
OK even if there no change to the source ? I work on W10 and I depend on users kindness for Lin and Mac dist so when they send me a dist for another platform than W10 I will have to change the version ?

**Comment by Phal-anx** [comment]
no as you provide them already with the correct makefile they just compile it ;)

the version number in the makefile and the version number in the json file needs to be ident. it doesnt matter for which OS it will be compiled..

so if you create a new version e.g. -> version = "0.5.3" 
the version number in the makefile and the json file needs to be changed to version = "0.5.3" 

I hope I discribed it properly.. I m not a pro in english :D

**Comment by sebastien-bouffier** [comment]
Clear enough for me thanks a lot Michael
