### ISSUE TITLE
dTrOY: new instance doesn't start in default state

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#26]
OS (if applicable): WIN
Version (or "dev" if compiling from source): 0.5.12

not a biggie, but when adding a new instance of dtroy, it's started with all
knobs (except clock) fully left, instead of their default (initialized) position.

**Comment by sebastien-bouffier** [comment]
That's right I will fix it.

**Comment by sebastien-bouffier** [comment]
seems to be fixed with 0.5.13

**Comment by phdsg** [comment]
yep. initial start state is good now.
only one little leftover with the initialize:
when i change preset 1.
then switch to another preset.
use initialize from the menu...
...first preset only gets partially initialized.

**Comment by sebastien-bouffier** [comment]
done in 0.5.14
