### ISSUE TITLE
Segmentation Fault pressing "Play" Button.

### ISSUE THREAD

**Issue by Cordoha** [sebastien-bouffier/Bidoo#27]
Ubuntu 16.04
Latest Dev version of RACK

I have the latest build of Bidoo running, I hit the play button about 5 times or so, and VCV Rack does a segmentation fault, it is reproducible. Not sure if it's Rack, or Bidoo, or if you're aware of the issue. Here's the output of make debug:

LD_LIBRARY_PATH=dep/lib gdb -ex run ./Rack
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Rack...done.
Starting program: /home/justin/Rack3/Rack/Rack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[info] Current working directory: /home/justin/Rack3/Rack
[info] Global directory: ./
[info] Local directory: ./
[info] Loading plugins from ./plugins
[info] Loaded plugin ./plugins/JW-Modules/plugin.so
[info] Loaded plugin ./plugins/trowaSoft-VCV/plugin.so
[info] Loaded plugin ./plugins/NonLinearInstruments/plugin.so
[info] Loaded plugin ./plugins/Grayscale/plugin.so
[info] Loaded plugin ./plugins/Fundamental/plugin.so
[info] Loaded plugin ./plugins/Autodafe/plugin.so
[info] Loaded plugin ./plugins/LOGinstruments/plugin.so
[info] Loaded plugin ./plugins/nohmad/plugin.so
[info] Loaded plugin ./plugins/RJModules/plugin.so
[info] Loaded plugin ./plugins/cf/plugin.so
[info] Loaded plugin ./plugins/AmalgamatedHarmonics/plugin.so
[info] Loaded plugin ./plugins/Befaco/plugin.so
[info] Loaded plugin ./plugins/s-ol/plugin.so
[info] Loaded plugin ./plugins/MSM/plugin.so
[info] Loaded plugin ./plugins/Stellare-Modular/plugin.so
[info] Loaded plugin ./plugins/NYSTHI/plugin.so
[info] Loaded plugin ./plugins/AS/plugin.so
[info] Loaded plugin ./plugins/ESeries/plugin.so
[info] Loaded plugin ./plugins/sonusmodular/plugin.so
[info] Loaded plugin ./plugins/ML_modules/plugin.so
[info] Loaded plugin ./plugins/Simple/plugin.so
[info] Loaded plugin ./plugins/Gratrix/plugin.so
[info] Loaded plugin ./plugins/mscHack/plugin.so
[info] Loaded plugin ./plugins/hetrickcv/plugin.so
[info] Loaded plugin ./plugins/ArableInstruments/plugin.so
[info] Loaded plugin ./plugins/BogaudioModules/plugin.so
[info] Loaded plugin ./plugins/KarateSnoopy/plugin.so
[info] Loaded plugin ./plugins/moDllz/plugin.so
[info] Loaded plugin ./plugins/VultModules/plugin.so
[info] Loaded plugin ./plugins/MentalModules/plugin.so
[info] Loaded plugin ./plugins/vcv-MrLumps/plugin.so
[info] Loaded plugin ./plugins/dekStop/plugin.so
[info] Loaded plugin ./plugins/AudibleInstruments/plugin.so
[info] Loaded plugin ./plugins/Parable/plugin.so
[info] Loaded plugin ./plugins/monome-rack/plugin.so
[info] Loaded plugin ./plugins/bbmodulesfree/plugin.so
[info] Loaded plugin ./plugins/qwelk/plugin.so
[info] Loaded plugin ./plugins/Bidoo/plugin.so
[info] Loaded plugin ./plugins/Autodafe-Drums/plugin.so
[info] Loaded plugin ./plugins/AepelzensModules/plugin.so
[info] Loaded plugin ./plugins/NauModular/plugin.so
[info] Loaded plugin ./plugins/ValleyRackFree/plugin.so
[info] Loaded font ./res/DejaVuSans.ttf
[info] Loading patch ./autosave.vcv
[New Thread 0x7fffe44dc700 (LWP 17861)]
[New Thread 0x7fffe445b700 (LWP 17862)]
[Thread 0x7fffe445b700 (LWP 17862) exited]
[Thread 0x7fffe44dc700 (LWP 17861) exited]
[info] Loaded SVG ./res/ComponentLibrary/PJ3410.svg
[New Thread 0x7fffe44dc700 (LWP 17863)]
[New Thread 0x7fffe445b700 (LWP 17864)]
[Thread 0x7fffe445b700 (LWP 17864) exited]
[Thread 0x7fffe44dc700 (LWP 17863) exited]
[debug] Opening audio stream 2
[New Thread 0x7fffe44dc700 (LWP 17865)]
[New Thread 0x7fffe445b700 (LWP 17866)]
[Thread 0x7fffe445b700 (LWP 17866) exited]
[Thread 0x7fffe44dc700 (LWP 17865) exited]
[New Thread 0x7fffe44dc700 (LWP 17867)]
[New Thread 0x7fffe445b700 (LWP 17868)]
[debug] Starting audio stream 2
[New Thread 0x7fffe43c1700 (LWP 17869)]
[info] Loaded SVG ./plugins/ValleyRackFree/res/TopographPanel.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/TopographPanelWhite.svg
[info] Loaded SVG ./res/ComponentLibrary/ScrewBlack.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/LightLEDButton.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSBlue.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSWhite.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSBrightRed.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSOrange.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSYellow.svg
[info] Loaded SVG ./res/ComponentLibrary/PJ301M.svg
[info] Loaded SVG ./plugins/VultModules/res/Trummor2.svg
[info] Loaded font ./plugins/VultModules/res/01 Digit.ttf
[info] Loaded SVG ./plugins/VultModules/res/Screw.svg
[info] Loaded SVG ./plugins/VultModules/res/KnobAlt.svg
[info] Loaded SVG ./plugins/VultModules/res/Select3_A.svg
[info] Loaded SVG ./plugins/VultModules/res/Select3_B.svg
[info] Loaded SVG ./plugins/VultModules/res/Select3_C.svg
[info] Loaded SVG ./plugins/VultModules/res/Knob.svg
[info] Loaded SVG ./plugins/VultModules/res/Jack.svg
[info] Loaded SVG ./plugins/VultModules/res/KnobSmall.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonA_OFF.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonA_ON.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonB_OFF.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonB_ON.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonC_OFF.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonC_ON.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonD_OFF.svg
[info] Loaded SVG ./plugins/VultModules/res/ButtonD_ON.svg
[info] Loaded SVG ./plugins/MentalModules/res/Mixer.svg
[info] Loaded SVG ./res/ComponentLibrary/SynthTechAlco.svg
[info] Loaded SVG ./res/ComponentLibrary/SynthTechAlco_cap.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/OutPort.svg
[info] Loaded SVG ./res/ComponentLibrary/Trimpot.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/InPort.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/CVInPort.svg
[info] Loaded SVG ./res/ComponentLibrary/LEDButton.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/GateInPort.svg
[New Thread 0x7fffd99a0700 (LWP 17870)]
[info] Loaded SVG ./plugins/NYSTHI/res/HotTuna.svg
[info] Loaded font ./plugins/NYSTHI/res/fonts/DejaVuSansMono.ttf
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/nyInputPort22CV.svg
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/nyOutputPort22CV.svg
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/nyRoundBlack.svg
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/nyInputPort.svg
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/nyOutputPort.svg
[info] Loaded SVG ./plugins/NYSTHI/res/ctrls/LEDMiniButton.svg
[info] Loaded SVG ./plugins/VultModules/res/Tohe.svg
[info] Loaded image ./plugins/AudibleInstruments/res/Branches.png
[info] Loaded SVG ./res/ComponentLibrary/ScrewSilver.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSRed.svg
[info] Loaded SVG ./res/ComponentLibrary/TL1105_0.svg
[info] Loaded SVG ./res/ComponentLibrary/TL1105_1.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSGreen.svg
[info] Loaded SVG ./plugins/MentalModules/res/MentalPatchNotes.svg
[info] Loaded SVG ./plugins/Bidoo/res/DTROY.svg
[info] Loaded font ./plugins/Bidoo/res/DejaVuSansMono.ttf
[info] Loaded SVG ./res/ComponentLibrary/RoundBlack.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/BlueKnobBidoo.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/BlueCKD6_0.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/BlueCKD6_1.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/BlueTrimpotBidoo.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/bidooSlidePotLong.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/bidooSlidePotHandle.svg
[info] Loaded SVG ./plugins/Bidoo/res/ComponentLibrary/bidooSlidePotShort.svg
[info] Loading settings ./settings.json
[New Thread 0x7fffd919f700 (LWP 17871)]
[New Thread 0x7fffe4340700 (LWP 17872)]
[Thread 0x7fffe4340700 (LWP 17872) exited]

Thread 12 "Rack" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd919f700 (LWP 17871)]
0x00007fffe5a6d7f9 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (
    this=this@entry=0x7fffd919ea60, __urng=..., __param=...)
    at /usr/include/c++/5/bits/uniform_int_dist.h:217

**Comment by sebastien-bouffier** [comment]
Mmm is it a patch containing a dTrOY instance you made before 0.5.14 ? When you write "I hit the play button about 5 times" .. which play button ? Is it a jump button on MOiRE or somethink else ? Please tell me more so I can help you.

**Comment by phdsg** [comment]
looks like dtroy from the logs. couldn't replicate (hammering away on the play button) on my linux machine.

**Comment by sebastien-bouffier** [comment]
Haaaaaa, ok, the play button ... on dTrOY .. sorry but for me it is Play Mode so I was searching for a play button in Rack ... pffff .. I should go to bed. I did not managed to replicate too. 
Looking at the log I see that there is something about std distrib which is used by dTrOY in random play mode. I check.

**Comment by sebastien-bouffier** [comment]
Made several tests, stress tests and cannot replicate. Can you share your patch please ? Do you use Monome ? This plugin use std distrib too ...

**Comment by Cordoha** [comment]
My patch did change, and now I can't replicate. Weird. Sorry.

**Comment by sebastien-bouffier** [comment]
No pb, most important ... you can make music :)
