### ISSUE TITLE
dTrOY steps and gates

### ISSUE THREAD

**Issue by sebastien-bouffier** [sebastien-bouffier/Bidoo#30]
OS (if applicable):
Version (or "dev" if compiling from source):

dTrOY is absolutly great !
I noticed that two parameters are not saved in a patch or when the module is duplicated in a patch : Steps and Gate…
Thanks ;-)

**Comment by sebastien-bouffier** [comment]
Stratocastix any news ? I do not have that issue. The number of steps and Gate time are saved per pattern so can you provide me with more details please ?

**Comment by NikolaiVChr** [comment]
Great sequencer, use it alot.
Just want to mention that slide knob is also not saved between patches.
Here is how it looks when loading the patch (slide was turned to max when I saved):
![image](https://user-images.githubusercontent.com/3764194/35857365-3b8e993c-0b39-11e8-88b4-628561947eb2.png)

**Comment by sebastien-bouffier** [comment]
Ok ok. I just made a test and can't reproduce. So I take a closer look to your pic and I see that you are on pattern 2 (P2). Can you check that you selected the good pattern ? All the blue knobs are saved in patterns. What is your OS ?

**Comment by NikolaiVChr** [comment]
The pattern is correct, it was saved with P2.

I am on Windows 10. Here is a saved file with slide at max:

[autosave.vcv.zip](https://github.com/sebastien-bouffier/Bidoo/files/1701002/autosave.vcv.zip)

**Comment by sebastien-bouffier** [comment]
Thanks it helps a lot. Slide is not the only parameter concerned, that is the same for scale etc... Saving works fine but when reopening the patch the pattern that was active on close is not loaded as it should be. I try to fix asap.

**Comment by sebastien-bouffier** [comment]
Bug found and fixed. I release asap. Best.

**Comment by sebastien-bouffier** [comment]
Released

**Comment by sebastien-bouffier** [comment]
Released and published so I close
