### ISSUE TITLE
Mustard knobs

### ISSUE THREAD

**Issue by LKHSogpit** [sebastien-bouffier/Bidoo#32]
What do think of this. I like the blue colour but this is a little nicer imo. Lighther on the eyes.

![dtroy](https://user-images.githubusercontent.com/12150421/35330972-84f98e06-00fd-11e8-985d-c633a9302594.JPG)

Zip:  [Bidoo Knob Colour Change.zip](https://github.com/sebastien-bouffier/Bidoo/files/1659682/Bidoo.Knob.Colour.Change.zip)
 The .svg files are just overlayed with a little opacity 93.3% on the mustard over the blue.

I was not digging the high contrast so changed the bigger knob black outline.

**Comment by sebastien-bouffier** [comment]
Hello LKHSogpit and thanks for your interest in that pack. I did a try with you colors and here is my opinion, it looks good, it is closer to Andrew's plugins look (pulse matrix), the fact that the cursor line is white doesn't help to see knob position. For the moment I think will keep blue as standard but if many users (if there a many :)) prefer "mustard" ... why not. I am a little bit reluctant to facebook so I do not read VCV rack user group very often, is blue knobs an issue raised by many users ?

**Comment by LKHSogpit** [comment]
Not that I know of, I like blue too just something different thought I'd share. I will probably customise a good few modules now that I know how.

**Comment by sebastien-bouffier** [comment]
Yes it not so complicated if you have inkscape and respect path/filenames. 
I think that I will stay with blue, the more I think about that the more I think that it is better to let Andrew develop his own graphic identity. Maybe I am wrong but he develops his brand/software for a living so I think it is fair not to be too close of his plugins.
Best,

**Comment by LKHSogpit** [comment]
I made a couple of edits to the source of Bar and Moire there also changed Bar's L/R positions to be consistent with other modules and to swap the top/right relationship for the display. On Moire fixed the red dot and pot positions made 2 changes there. 1 to move the port the other to move the port and dot to be centre on the fader above attached the .svg on the PR.

**Comment by sebastien-bouffier** [comment]
thanks I will take a look asap to your PR, I am working on a LP filter when ready I will pull your PR. best

**Comment by LKHSogpit** [comment]
Cool Bar is quite useful I have a few features I'd love to see will post when you complete the LP.
