### ISSUE TITLE
build fails. typo in #include @ ouaive

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#35]
OS (if applicable): linux
Version (or "dev" if compiling from source): dev

> src/OUAIVE.cpp:5:37: fatal error: dep/audioFile/AudioFile.h: No such file or directory
 #include "dep/audioFile/AudioFile.h"
                                     ^
compilation terminated.
../../compile.mk:53: recipe for target 'build/src/OUAIVE.cpp.o' failed

says audio**F**ile in the include - actual path: audio**f**ile

**Comment by sebastien-bouffier** [comment]
thanks I fix that asap

**Comment by sebastien-bouffier** [comment]
done thanks again
