### ISSUE TITLE
proposal: taking lATe a step further

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#36]
another one of my proposals that spark from an idea i had while using one of your modules (this time it's lATe) and wanting it to do a little more that i can't do myself.
this would probably be a whole new module instead of just a new feature in lATe.

interested?

**Comment by sebastien-bouffier** [comment]
Yep sure. I was messing with filters those days. I wanted to implement a simple vocoder and that's done :) 
Not the best one for sure but it sounds good to my ears so I released it. 
I do not promise to be able to make your dreams real, or to have the time to make it in few days but let's see what kind of spark we have to deal with.

**Comment by phdsg** [comment]
ok, let's see if i can described it well enough. no sketch this time.
so it's basically a gate seq that repeats a 16 step bar with lATe on every 16th.
so each 16th can be a little late (or early) and nice groove patterns can be dialed in.
maybe some preset slots or even midi file import.

**Comment by sebastien-bouffier** [comment]
mmm, somthing "à la" elektron's micro-timing ? Push back push forward .. each step ? Something that could trig groove maps .. like groove/swing in Live ?

**Comment by phdsg** [comment]
:+1:

**Comment by sebastien-bouffier** [comment]
Ho yes it does more :) didn't know this module, nice approach for sequencing. It gives me a lot of ideas. For example might be useful to set probability on dTrOY steps ... I will think about something that can stay simple and make the trick for groove patterns. Before any line of code I will come back with a mock-up to make sure we are in line.

**Comment by phdsg** [comment]
ideas are the best :)
yeah, dTrOY with chances (and groove maybe too).
looking forward to what you come up with.

**Comment by sebastien-bouffier** [comment]
just to make sure I do not miss something ... you already asked for swing/groove in dTrOY ... if we have lATe or something else that modulate the clock in front of dTrOY why would you like to have it in dTrOY ? Is it just a question of "all in one" module or is there something special that could not be done outside dTrOY ?

**Comment by phdsg** [comment]
nah, dtroy is all fine. a groovy clock in front of it will be good enough. was just a "why not!?"-maybe :).

**Comment by sebastien-bouffier** [comment]
just pushed a new module, LoURdE which is a gate tool that can be used to generate patterns (not only). It is still not the groove/quantize ultimate tool but it can help to generate weird things.

**Comment by phdsg** [comment]
love weird :)
will test soon. i got a few days off coming...

**Comment by sebastien-bouffier** [comment]
Something new ... μ. 
It is a step module that looks like an elektron MD/Octatrack step in a sequence. Step length allows you to make it play around the tempo. Retrigs and distance too ... It requires a little of work to setup (cables and cables and more cables) but once done it is ... fun :)
