### ISSUE TITLE
Bingo... Zinc 

### ISSUE THREAD

**Issue by LKHSogpit** [sebastien-bouffier/Bidoo#38]
Had an idea for a module but no clue how to implement then I saw the biquad in the code and it would be the perfect thing I think. Thanks for putting me onto earlevel also! Great resource.

Reading the blog on earlevel. Saw the part about combining biquads " if you need a 24 dB/octave slope, you can cascade two biquads," do you know if that stacks. Casade 3 and you get 36dB/oct, 4 48dB/oct etc...

**Comment by sebastien-bouffier** [comment]
Hello, yes you can stack them that's what I did here
out += cFilter[i+BANDS]->process(cFilter[i]->process(inC*params[GCARR_PARAM].value)) * coeff * params[BG_PARAM+i].value;
I didn't test more than one cascade but thanks to Andrew's framework beauty you can do that test very easily. If you need help do not hesitate to ask, if I can I will :)

**Comment by LKHSogpit** [comment]
What would it look like with just 1 pole. Not stacked. Limbo or perco don't use the same code trying to work it out. The comments on the blog
```
biquad = { a0, a1, a2, b1, b2 };

for (var i = 0; i < input.length; ++i) {
x = input[i];
y = x * biquad[0] + z1;
z1 = z2 – biquad[3] * y;
z2 = x * biquad[2] – biquad[4] * y;

x = y;
y = x * biquad[0] + z11;
z11 = z22 – biquad[3] * y;
z22 = x * biquad[2] – biquad[4] * y;

x = y;
y = x * biquad[0] + z111;
z111 = z222 – biquad[3] * y;
z222 = x * biquad[2] – biquad[4] * y;

output[i] = (float) y;
}
```
```
Yes, that’s pretty much it, except that you’re missing the a1 factor when calculating z1 (z11, z111):

z1 = x * biquad[1] + z2 – biquad[3] * y;
```
Should that be in .h or does it need to be just trying to understand which way to do it.

**Comment by sebastien-bouffier** [comment]
lIMbO and pErCO were made before ziNC and at that time I didn't know about earlevel. I was struggling/learning how to make a BP filter for ziNC and I built them gathering information from several sources. According to my understanding they are all based on the same IIR approach (disclaimer : I am not a dsp guru and Rack is a great opportunity for me to learn what is behind the curtains of audio softwares). By default a biquad is a 2nd order filter 2 poles 2 zeros 12db/o. You can achieve a 1st order filter with a more simple design http://www.earlevel.com/main/2012/12/15/a-one-pole-filter/ or maybe  keeping the biquad source and setting a1 a2 and b2 to 0.

I do not find the url of your quotes can you provide them please ? I am not sure I answered your question.

**Comment by sebastien-bouffier** [comment]
Writing my previous answer I realized that I wrote something wrong in my readme file .. pErCO is not a 1st order but a 2nd order filter. Fixed.

**Comment by LKHSogpit** [comment]
http://www.earlevel.com/main/2003/02/28/biquads/

**Comment by sebastien-bouffier** [comment]
> What would it look like with just 1 pole. Should that be in .h or does it need to be just trying to understand which way to do it.

create a .h file with this code 

    //
    //  OnePole.h
    //
    
    #ifndef OnePole_h
    #define OnePole_h
    
    #include <math.h>
    
    class OnePole {
    public:
        OnePole() {a0 = 1.0; b1 = 0.0; z1 = 0.0;};
        OnePole(double Fc) {z1 = 0.0; setFc(Fc);};
        ~OnePole();
        void setFc(double Fc);
        float process(float in);
        
    protected:    
        double a0, b1, z1;
    };

    inline void OnePole::setFc(double Fc) {
        b1 = exp(-2.0 * M_PI * Fc);
        a0 = 1.0 - b1;
    }

    inline float OnePole::process(float in) {
        return z1 = in * a0 + z1 * b1;
    }
    
    #endif

Source comes from here  http://www.earlevel.com/main/2012/12/15/a-one-pole-filter/ 

In your cpp include your .h, create your filter in your module and in Step() set Fc at your convenience (do not forget sampling rate ratio) and `output = filter->process(input);`

if you want a HP instead of a LP change setFc(double Fc)

    b1 = -exp(-2.0 * M_PI * (0.5 - Fc));
    a0 = 1.0 + b1;

I hope I answered your question.
Best
