### ISSUE TITLE
zinc: band peak display.

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#39]
just a visual taste thing:
i find the flickering text a little bit annoying. it's also almost not visible when zoomed out a bit.
how about ledknobs (transparent knob over a knob-sized light)?

**Comment by sebastien-bouffier** [comment]
just pushed a mod on ziNC tell me what you think about that ?

**Comment by sebastien-bouffier** [comment]
lol it has side effect on all my modules. I find that this kind o display is fine but I need to fix the side effect.

**Comment by phdsg** [comment]
nice. much better.
