### ISSUE TITLE
[bug] ChUTE: ball bounces out of bounds

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#4]
OS: win7 64bit
Rack: dev

here's a screenshot of the bouncy ball going over the top...
![chute_outofbounds](https://user-images.githubusercontent.com/33329578/32558578-6316976e-c4a5-11e7-9828-7acba4127f76.PNG)

**Comment by sebastien-bouffier** [comment]
Hello, it should be fixed. It was due to changes into params that lead the bullet, now a smiley, to be out of the scale. To be more accurate I should draw a kind of scale to reflect changes in params but I try to find the sweet spot between look/information and performances.

**Comment by phdsg** [comment]
wow that was fast. gonna test later and report back...

**Comment by phdsg** [comment]
looks good. no bouncing out of bounds anymore
