### ISSUE TITLE
bordL: rounded values strangeness

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#40]
you may have noticed this already yourself:
when you turn a pitchknob to "eleven" it shows 9.xx until you touch another control. then it switches to 10.  
i have seen this in many plugins, so i think it's a rack thing.

other than that, nice variant of the dTrOY.
the probability thing in the varigate really caught you, did it!? :)
anyway, good work!

**Comment by sebastien-bouffier** [comment]
Hello, no I didn't noticed that  I will check to see if I am not making something wrong. 
Still thinking about groovin' clock ... I am trying to think out of the box to make something with good added value, easy to use and robust ... thanks and yes probability is a nice feature :) , Random on the added CV line is nice too for velocity grooves etc...
