### ISSUE TITLE
dTr0Y closes v/o output to 0 when gate is low.

### ISSUE THREAD

**Issue by carljohanlinell** [sebastien-bouffier/Bidoo#44]
OS: Win 10
Version 0.5.20, Rack 0.5.1

dTr0Y seems to drop V/O output from the desired pitch to 0V when the gate goes low. This creates some unpleasant sounds when using an envelope with a non-zero release time.

Is this intentional? The "real" Atlantis and RYK M-185 don't seem to do this.

**Comment by sebastien-bouffier** [comment]
Hello you have the choice between two modes. Pitch follows gate output as you describe or stays at current value until the next step. You can switch between those modes with the menu (right click on the plugin).

**Comment by sebastien-bouffier** [comment]
Can you confirm it is the behavior you expect ?

**Comment by carljohanlinell** [comment]
Sorry. I'm a fool.
It works as intended, I just didn't investigate the dropdown menu.

carry on folks
