### ISSUE TITLE
baR code for meters

### ISSUE THREAD

**Issue by Coirt** [sebastien-bouffier/Bidoo#45]
Hi seb. Iv'e been trying different things with the meter code from baR on my module Gain for the past week or so. Sadly can't get it to work properly. Its trial and error first coding project. Have the transparent widget and colours set roughly just need to get the solid fill to disappear when no audio is passing through.

Could you take a look if you can spare the time, would really appreciate it, I think I am close with it.
[repo](https://github.com/Coirt/Bark/tree/master/src)

**Comment by sebastien-bouffier** [comment]
Hello, I almost spent 2 weeks away from Rack ... family, work, music band ... didn't had the time to take a look at your issue. I will try this week-end. Best.

**Comment by Coirt** [comment]
Cheers.
