### ISSUE TITLE
Proposal: Add switch to TiARE for Audio/LFO rate, or new module with LFO rate

### ISSUE THREAD

**Issue by patman023** [sebastien-bouffier/Bidoo#46]
OS (if applicable):
Version (or "dev" if compiling from source):
Pretty much what's in the title. I was sad to find I couldn't use a tiare to modulate another tiare's x/y at a usable speed. :-/

**Comment by sebastien-bouffier** [comment]
Hello, I hope I understood your need. Since 0.5.21 you can divide frequency base per 10 with the menu.

**Comment by sebastien-bouffier** [comment]
Released and published so I close.
