### ISSUE TITLE
0.5.21 build error: cannot find -lcurl

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#47]
OS (if applicable): linux debian9
Version (or "dev" if compiling from source): dev

weirdly enough make bails with this message:
```
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
../../compile.mk:43: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

```

i already tried rebuilding rack's deps (which should include curl) but still the same error.
on my windows it builds fine.

**Comment by sebastien-bouffier** [comment]
Hello, I was expecting issues with this release ... I am used to work within VS on windows but as you may know coding for rack is another story ... text editor + msys terminal ... and library dependencies in this environment is not my top one skill :) 
At the same time this is the beauty of that project too ... i learn a lot
I will try to find the source of the issue.
What I can say at that point is that you shouldn't have to rebuild rack's deps so it might be a path or variable name issue within my makefile

**Comment by sebastien-bouffier** [comment]
I have received an email from you but I can't find it on github saying you have an issue with mpg123 lib at the same time. Is it solved by a make dep in my source folder ? If yes the only remaining issue on Linux is curl reference ..

**Comment by sebastien-bouffier** [comment]
can you try to substitute this line in the plugin make file please ?
```
LDFLAGS += -rdynamic -shared -L../../dep/lib -L./src/dep/lib -lmpg123 -lcurl
```
to this one
```
LDFLAGS += -shared -L./src/dep/lib -lmpg123 -lcurl
```
for `ifeq ($(ARCH), lin)`

**Comment by sebastien-bouffier** [comment]
mmm just an idea ... add  -lssl maybe curl needs a ref to this lib for Linux

**Comment by phdsg** [comment]
i'll try a few things...
meanwhile: you mentioned VS. have you seen this: https://github.com/cschol/vcv-rack-vscode ?

**Comment by sebastien-bouffier** [comment]
thanks a lot, no I was not aware of that VS project, I will take a look at it. Still wondering what is the issue with curl on Linux ...

**Comment by phdsg** [comment]
adding -lssl doesn't help. only one more linker error.

**Comment by sebastien-bouffier** [comment]
I pushed a fix on antN that allows switching between urls safely. At the same time I posted in a thread on Rack to request some help. Lets see.

**Comment by sebastien-bouffier** [comment]
Here is a reply from Andrew 
You might need to add a linker path to $(RACK_DIR)
Can you try it please ?

**Comment by phdsg** [comment]
sry for the stupid question: how?

**Comment by sebastien-bouffier** [comment]
Lol
There is no stupid question only...
I am away from my computer but i will come back asap with a proposal 

Envoyé de mon iPhone

**Comment by sebastien-bouffier** [comment]
Just pushed a change in makefile but not sure it will solve the issue ... I do not find where RACK_DIR is defined. I will ask Andrew.

**Comment by phdsg** [comment]
no good, but different error.
```
/usr/bin/ld: ./src/dep/lib/libmpg123.a(id3.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
../../compile.mk:43: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

```

**Comment by sebastien-bouffier** [comment]
another attempt just pushed ...

**Comment by phdsg** [comment]
nope, same error as last try.

**Comment by phdsg** [comment]
meh, i'm getting the feeling this could maybe be rooted in the something with the debian dist. dunno. could set up a different flavor of linux in a vm to try.

**Comment by sebastien-bouffier** [comment]
yes I read things about 32/64 bits arch with shared libs, debian ... I don't know ... maybe try to remove the rdynamic flag, not sure that $(RACK_DIR) helps, maybe I should try to build mpg123 with other flags because I have removed the shared library capability ...

**Comment by sebastien-bouffier** [comment]
Just pushed another change to makefile. Hope it will help.

**Comment by phdsg** [comment]
trying... fingers crossed :)
i always do make clean and dep clean for each build.

**Comment by phdsg** [comment]
nah... :(

**Comment by sebastien-bouffier** [comment]
keep on trying adding paths ... could you try a new pull & build please ?

**Comment by phdsg** [comment]
already on it :)
also installing a different dist in the background.

**Comment by phdsg** [comment]
non. same.

**Comment by sebastien-bouffier** [comment]
Haaaaaaaaaaaaaaaaaaaaaaaaaaaa 
Thanks in advance for your time

**Comment by phdsg** [comment]
ok, installed budgie in virtualbox, grabbed all the deps for rack, built rack, cloned bidoo, same result :(

**Comment by davephillips** [comment]
Hey Sebastien, I've run a successful build here on Fedora 23. The only thing I did was to change this:

cd mpg123-1.25.8 && ./configure --prefix="$(LOCAL)" --with-cpu=generic --disable-shared --enable-modules=yes --enable-static --with-pic

to this:

cd mpg123-1.25.8 && ./configure --prefix="$(LOCAL)" --with-cpu=generic --with-pic --disable-shared --enable-modules=yes --enable-static

I hope that helps. :)

**Comment by sebastien-bouffier** [comment]
Yes it helps, are you able to open a mp3 stream with that version ?
At the same time I have found two threads that makes me think that --with-pic hides something else.
As you can see I have faced some issue on Win at the beginning that made me add the `-lshlwapi` if arch = win.
The two threads ;
[https://stackoverflow.com/questions/19364969/compilation-fails-with-relocation-r-x86-64-32-against-rodata-str1-8-can-not]()
and 
[https://sourceforge.net/p/mpg123/mailman/message/35643151/](url)
So I will push a new make file with that lib link for Lin. 
Tell me if it works.

**Comment by phdsg** [comment]
ooo, new error...

```
g++ -o plugin.so build/src/ACNE.cpp.o build/src/FORK.cpp.o build/src/LIMBO.cpp.o build/src/ANTN.cpp.o build/src/DTROY.cpp.o build/src/LATE.cpp.o build/src/PERCO.cpp.o build/src/CLACOS.cpp.o build/src/Bidoo.cpp.o build/src/OUAIVE.cpp.o build/src/BAR.cpp.o build/src/VOID.cpp.o build/src/ZINC.cpp.o build/src/MOIRE.cpp.o build/src/DUKE.cpp.o build/src/BORDL.cpp.o build/src/TIARE.cpp.o build/src/CHUTE.cpp.o build/src/dep/audiofile/AudioFile.cpp.o build/src/dep/pffft/pffft.c.o build/src/dep/filters/biquad.cpp.o -rdynamic -L./src/dep/lib -L../../dep/lib -L../../dep/include/curl -lmpg123 -lshlwapi -lcurl -shared
/usr/bin/ld: cannot find -lshlwapi
collect2: error: ld returned 1 exit status
../../compile.mk:43: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

```

**Comment by sebastien-bouffier** [comment]
Yep it was a bad idea. Have you been able to use antN with your previous build ? Can you check that you have mpg123.so in dep/lib please ?

**Comment by phdsg** [comment]
so far i have only been able to build it on mac and win. had it playing a lot in my win rack. even multiple devices/streams. fun module. vca on the out would be nice...

**Comment by sebastien-bouffier** [comment]
that Linux issue is driving me mad ...

**Comment by phdsg** [comment]
let's wait for dave's results. meanwhile, installing linux in virtualbox is easypeasy... just sayin' :)

**Comment by phdsg** [comment]
fixed, closing.
