### ISSUE TITLE
ANTN: just a warning, but who knows..

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#49]
after that [antn commit](https://github.com/sebastien-bouffier/Bidoo/commit/3361ce44a498292abc8378afddc6a3411c2a489b) i get this warning when compiling:

> g++ -I./pffft -DPFFFT_SIMD_DISABLE -I./src/dep/include -fPIC -I../../include -I../../dep/include -DSLUG=Bidoo -DVERSION=0.5.21 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/ANTN.cpp.o src/ANTN.cpp
> src/ANTN.cpp: In function 'void* threadTask(void*)':
> src/ANTN.cpp:81:1: warning: no return statement in function returning non-void [-Wreturn-type]
>  }
>  ^
> 
points to here:

https://github.com/sebastien-bouffier/Bidoo/blob/3361ce44a498292abc8378afddc6a3411c2a489b/src/ANTN.cpp#L64-L81

**Comment by sebastien-bouffier** [comment]
Yep I will add a last line to this function 
return 0;
Or change it to a void and pass an & to the caller
It does not affect the code at runtime

**Comment by phdsg** [comment]
btw. nice module. having great fun mangling 'radio' like sources in rack.

**Comment by phdsg** [comment]
warning gone. closing.
