### ISSUE TITLE
[feature] dTrOY: additional play modes

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#5]
again, watching some more videos demoing the metropolis, i noticed that the hardware
has a set of play modes  that determine their pattern length by pulse count instead of steps.

would that be possible?

**Comment by sebastien-bouffier** [comment]
hello, everything is possible :) I am thinking about changing the design of the pattern management so I will take this idea into account for the next release.

**Comment by phdsg** [comment]
sounds great. looking forward to that.
very interested in hearing about the planned changes :)

**Comment by sebastien-bouffier** [comment]
pulse count mode done thanks to pattern management redesign. now if you compile you should see that the next milestone is going from pattern to patterns :)

**Comment by phdsg** [comment]
very nice changes.
also, multiple patterns is a good one, obviously.
nice work. thank you.
