### ISSUE TITLE
build fail latest pull (relocation error)

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#51]
Fedora 23 Linux
Rack 0.5.x

g++ -o plugin.so build/src/ACNE.cpp.o build/src/FORK.cpp.o build/src/LIMBO.cpp.o build/src/ANTN.cpp.o build/src/DTROY.cpp.o build/src/LATE.cpp.o build/src/PERCO.cpp.o build/src/CLACOS.cpp.o build/src/Bidoo.cpp.o build/src/VOID.cpp.o build/src/OUAIVE.cpp.o build/src/BAR.cpp.o build/src/ZINC.cpp.o build/src/MOIRE.cpp.o build/src/DUKE.cpp.o build/src/BORDL.cpp.o build/src/TIARE.cpp.o build/src/CHUTE.cpp.o build/src/dep/audiofile/AudioFile.cpp.o build/src/dep/pffft/pffft.c.o build/src/dep/filters/biquad.cpp.o -rdynamic -L./src/dep/lib -L../../dep/lib -L../../dep/include/curl -lmpg123 -lcurl -shared
/usr/bin/ld: ./src/dep/lib/libmpg123.a(index.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
./src/dep/lib/libmpg123.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
../../compile.mk:43: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

I think this problem should be easy to resolve but I'm not sure where to add the -fPIC option. I have to leave home for a while now, I'll try some solutions later today. Please advise if you have any suggestions.

**Comment by phdsg** [comment]
see https://github.com/sebastien-bouffier/Bidoo/issues/47

**Comment by sebastien-bouffier** [comment]
Hello Dave and thanks for your help. To be honest I do not know what to think about this issue with Linux. I think I will use your settings you mentioned in the other thread 
`cd mpg123-1.25.8 && ./configure --prefix="$(LOCAL)" --with-cpu=generic --with-pic --disable-shared --enable-modules=yes --enable-static`
With a condition on arch=lin because with those flags it doesn't work on Win anymore.
I will mount a VM with Linux, make some tests and I hope I will learn what issue is hidden behind this FPIC message. What dist of Linux you would recommend ?

**Comment by phdsg** [comment]
been using debian9 on my laptop to do the builds and have the same in a vm.
the vm install of budgie (suggested here: https://github.com/jeremywen/JW-Modules/wiki/Dev-FAQ-for-VCV-Rack#how-do-i-build-rack-on-linux ) i did earlier was even easier and faster than debian and also works fine for rack.

**Comment by sebastien-bouffier** [comment]
thanks

**Comment by sebastien-bouffier** [comment]
VM and Linux installed. I think I have found the bug :) 
I will push asap.

**Comment by phdsg** [comment]
yeah, looks fine now. glad you found and squashed that. gonna close #47 then.

**Comment by phdsg** [comment]
unfortunately it segfaults on linux :(  
win is fine tho.

**Comment by sebastien-bouffier** [comment]
yaaaaaaaaaaaaaaaaaaaaaaaaaah
Linux drives me mad
Positive thought ... I have learned on linking etc ... that's the good point
Now I have to understand why that ..... posix thread won't create on Linux

**Comment by phdsg** [comment]
wish i knew how to use gdb... but yeah, this is what it says when crashing. gonna watch for a tut on how to gather more info...```

[New Thread 0x7fffdbc4a700 (LWP 1422)]

Thread 3 "Rack" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdbc4a700 (LWP 1422)]
0x00007ffff7bc3c1f in __pthread_create_2_1 (newthread=<optimized out>, attr=attr@entry=0x0, start_routine=start_routine@entry=0x7fffea074f71 <threadTask(void*)>, arg=arg@entry=0x7fffdfc4a0f0) at pthread_create.c:631
631	pthread_create.c: No such file or directory.
```

**Comment by sebastien-bouffier** [comment]
just pushed a version that should work on all OS. I tried to make the linux dist but make tells me no target ...

**Comment by phdsg** [comment]
ok, gonna check and post the zip...

**Comment by phdsg** [comment]
phew, that was a hard one. well done!

**Comment by sebastien-bouffier** [comment]
thanks and yes still learning :) not used threads a lot until now but that's done :) I close
