### ISSUE TITLE
Help upgrading to Rack v0.6?

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#52]
Hi Sebastien,

Are you interested in help upgrading to the Rack `v0.6` API? The Rack Plugin Repair Team can provide a PR for the changes to upgrade to the new API.

Thank you for providing this awesome plugin!

**Comment by cschol** [comment]
Perfect. Let us know. The release date is currently still being decided. Andrew is considering pushing it out a couple of weeks to get the (new) Plugin Manager up and running for `v0.6`.

**Comment by Coirt** [comment]
I'd be happy to help also Sebastien don't hesitate to ask. I changed a few things on my fork in Bar and your .cpp/.hpp that are compatible with 0.6.0dev.

Did a trial run earlier, Forked a single module project and built against 0.6.0dev. Will be moving onto 0.6dev myself try get ahead of it!

**Comment by sebastien-bouffier** [comment]
Thanks for your proposal but it is almost done :) 
I will look to your fork but to save time what did you changed in baR ? Is there a bug ? A missing feature ? An issue on params calibration ?

**Comment by Coirt** [comment]
Actually built earlier and got a lot of errors. Some were typos. But others are depreciated errors that changing doesn't seem to fix. Getting errors in the components too think its because of BidooComponent.hpp most errors were in there.

`randomf` changed to `randomUniform` `clampi` `clamp` `rescalef` `rescale` (not in fork)

Some other changes harder to explain but put some comments in the fork.

**Comment by cschol** [comment]
Those are deprecation WARNINGS, not errors. Read the API Update Thread on how to make those new calls, for example `clamp`, non-ambigous. You mostly need to add suffixes to your constants (or cast correctly) to clearly identify the data types.

**Comment by sebastien-bouffier** [comment]
Yep migration done and everything works smooth, 
I just need time to make more tests, test again in my linux VM and pray that it will work on all OS X versions.
The biggest part of the upgrade is on components and widgets' headers the rest is find/replace + good cast. @Coirt I will push on saturday I think. I was the good occasion to clean some dead code too :)

**Comment by phdsg** [comment]
`setPanel(SVG::load(assetPlugin(plugin, "res/Panel.svg")));` instead of
```
	box.size = Vec(x, y);

	{
		SVGPanel *panel = new SVGPanel();
		panel->box.size = box.size;
		panel->setBackground(SVG::load(assetPlugin(plugin, "res/Panel.svg")));
		addChild(panel);
	}
```
is also so much nicer now.

**Comment by sebastien-bouffier** [comment]
yep this upgrade is quite nice and as usual Andrew's code is very clean and readable, template help too and community is great :)

**Comment by phdsg** [comment]
i'll test too as soon as you pushed.

**Comment by Coirt** [comment]
Thought it was `setPanel(SVG::load(assetPlugin(pluginSLUG, "res/Panel.svg")));` No?

**Comment by sebastien-bouffier** [comment]
No. For exemple on baR 
```
struct BARWidget : ModuleWidget {
	BARWidget(BAR *module) : ModuleWidget(module) {
		setPanel(SVG::load(assetPlugin(plugin, "res/BAR.svg")));

		addChild(Widget::create<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
		addChild(Widget::create<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
		addChild(Widget::create<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
		addChild(Widget::create<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

		BARDisplay *display = new BARDisplay();
		display->module = module;
		display->box.pos = Vec(12.0f, 40.0f);
		display->box.size = Vec(110.0f, 70.0f);
		addChild(display);
```

**Comment by phdsg** [comment]
@Coirt i just copied the example above from fundamental/mutes, so i don't think so

**Comment by Coirt** [comment]
Was looking at luckyxxl found in Repair thread.

**Comment by phdsg** [comment]
luckyxxl hasn't changed the setpanel thing afaics.

**Comment by sebastien-bouffier** [comment]
There is a [template](https://github.com/VCVRack/Template) for the migration with the best practices, take this one as reference.

**Comment by Coirt** [comment]
It builds for 0.6.0dev though no errors might be another way to do it, idk. That other one I forked did crash when added for the first time though. Also crashes when duped (ctrl+d) Lucky's does not though weirdness. Will try it that way, didn't see that template cheers.

**Comment by AScustomWorks** [comment]
Hey, when this change sneaked in?:
```setPanel(SVG::load(assetPlugin(plugin, "res/MyModule.svg")));```

**Comment by phdsg** [comment]
i think together with the other helper changes for 0.6.

**Comment by sebastien-bouffier** [comment]
0.6.0dev just pushed. works fine on windows. tell me if you have any issue on other platforms.

**Comment by phdsg** [comment]
nearly fine... couple svg missing/not loading
chute and ouaive panel
bidooLongSlider

**Comment by phdsg** [comment]
capital letters in the filenames don't match...

**Comment by Coirt** [comment]
Get an build error:
```
src/ANTN.cpp:6:10: fatal error: mpg123.h: No such file or directory
 #include <mpg123.h>
```

**Comment by phdsg** [comment]
`make dep` before make

**Comment by Coirt** [comment]
That does it!

**Comment by cschol** [comment]
Excellent work. Thanks everybody! Closing this issue.
