### ISSUE TITLE
observations and request re: antN

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#54]
Fedora 23 Linux
Rack 0.5.x

Hi Sebastien !

Just a quick note to say how much I'm enjoying the antN module, it's great fun. :) It works perfectly with mp3 streams, but I do have a question: Would it be possible to support *.m3u (and/or possibly *.pls) streams ? Just wondering. Thanks for the great modules !

**Comment by sebastien-bouffier** [comment]
Hello yes it is planned to take a look at that kind of features in next versions. My road map is first to make sure that the plugin is OK for 0.6, then take a look @ groove/clock ideas I have to go a step further than lATe module which is fine to make simple swing. And after that I will take a look @ antN. At the same time I think about making making something a little bit crazier that ouaiVE for live sampling/mangling etc :) But ye antN might evolve soon.

**Comment by davephillips** [comment]
Greetings ! Thank you so much for supporting pls/m3u playlists, I've been testing the new feature this morning. It works, but occasionally the playback gets stuck in a loop. These errors are reported at the command prompt (Linux here):

Note: Illegal Audio-MPEG-Header 0x69732073 at offset 31201081.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x69732073 at offset 31201081.
Note: Trying to resync...
Note: Skipped 367 bytes in input.

Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:174] error: Aborting layer I decoding after step one.

Note: Illegal Audio-MPEG-Header 0xdf68c82a at offset 31202076.
Note: Trying to resync...
Note: Skipped 407 bytes in input.
Note: Illegal Audio-MPEG-Header 0xdf68c82a at offset 31202076.
Note: Trying to resync...
Note: Skipped 407 bytes in input.

et cetera. Sometimes I can resync simply by pressing the Listen button again, but that doesn't always work. Any suggestions ?

Btw, that "Frankenstein stream" error may have occurred when I tried using a second instance of antN. I'll try to reproduce the error and will report back to you later today.

Also, I have a feature request: Could a CV input be added for the Listen button, like a reset control ?

Anyway, I'm having a lot of fun using antN in Rack 0.6 dev to listen to a blues radio station this morning. :)

**Comment by sebastien-bouffier** [comment]
According to my understanding the "Frankenstein stream" warning arises when we change the stream's url. The mpg library sees a change in frames to decode, he waits for new compressed audio frames and suddenly it receives a new format frame according to the new url and throws that message. 
It is not blocking antN, but I will take a look on how managing those messages. Regarding m3u and pls formats there are few things I have noticed. Often m3u only contains the url of the stream so in that case antN will read the new url and launch the decoding process. But sometimes it contains a link to a pls stream and in that case this url is sent to the mpg library and it is not an audio stream so it fails. To cope with that I should put in place a kind of recursive function that calls itself until I find a valid mp3 stream url. On the other hand pls files are more structured and to manage them correctly I should put in place a kind of listbox on the UI to display all the links contained in the pls file, As it is antN takes the first url it finds and launch the mpg library with that url. 
If you need to read a specific m3u or pls that doesn't work in antN I would suggest you to open the file and take the url manually and test it in your browser and/or antN. 
Finally regarding the CV yes it is quite simple to do but I wonder why you would like to reset the streaming via CV ? What is the use case ?

**Comment by davephillips** [comment]
Thank you for the explanations/advice, I'll test further this afternoon. Re: the reset use case, I misunderstood the cause of the playback error. I thought that a simple reset might break a bad playback loop, but if it isn't affected then the CV input is indeed unnecessary.

**Comment by sebastien-bouffier** [comment]
Ok.  At the same time could you check that you can open many antN without any issue so I can close the corresponding opened issue.
