### ISSUE TITLE
antN: stuck in a loop...

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#55]
OS (if applicable): win7 mingw64
Version (or "dev" if compiling from source): dev 0.6

while testing some other stuff i had antN playing the sound source role.
at some point i noticed it was just looping the buffer.
don't remember what other modules were involved or when the looping began.
also couldn't reproduce until now. :/

**Comment by davephillips** [comment]
Ditto here with Fedora 23 Linux, but only randomly. I'll keep testing to see where/when it produces the loop.

**Comment by phdsg** [comment]
yeah, had it happen a couple more times now. i suspect it's just a stream dropout that causes the buffer to go into loop.

**Comment by sebastien-bouffier** [comment]
Hello bug identified flags to kill the curl thread are shared between instances ... bad bidoo naughty bidoo. 
So if you have more than one instance of antN when you launch the second one it will stop the stream on the first one.

**Comment by a1laserboy** [comment]
Maximum Effort

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
