### ISSUE TITLE
question/request re: antN instances

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#56]
Fedora 23 Linux
Rack 0.5.x

Hi Sebastien, I've noticed that I can run a maximum of three instances of antN. A fourth instance simply doesn't play. Is this is a necessary limitation ? If so, can the number be increased ?

**Comment by sebastien-bouffier** [comment]
Hello, no, no limitation. I made a test with up to 5 antN under windows and it is OK.

**Comment by davephillips** [comment]
Ah, okay, the problem was probably due to the curl-related bug. I'll update and test again. Thanks a lot !

**Comment by phdsg** [comment]
have two instances streaming, (re-)hitting 'listen' on one instance can interrupt the other instance too.

**Comment by sebastien-bouffier** [comment]
Hello, sorry for the delay but unfortunately I have few time to play with rack and develop those days. The last "stress test " I made was with 5 instances of antN under 0.6dev and I noticed that when changing the url on one instance and hitting "listen" the others had small "glitches" but didn't stop playing. When you write interrupt do you mean stop ? What was the version ? 0.5 Lin ?

**Comment by phdsg** [comment]
not stopping. just what you described too: small glitches. 0.6 windows version.

**Comment by sebastien-bouffier** [comment]
Ok thanks. This is my todo check list ...

**Comment by davephillips** [comment]
Just a quick note to let you know that I've been running four instances of antN in Rack 0.6.x without problems. Ran the instances through the Audible Instruments Frames keyframes mixer, with the frames sequence modulated by a simple LFO. I did a similar thing combining antN and Jon Williams rtl-sdr FM radio module through Frames. Lots of fun going on here at Studio D. :)

**Comment by sebastien-bouffier** [comment]
Great, I have found how to avoid Frankenstein messages, I will push the update soon but unfortunately it doesn't solve the glitches when "stressing" the plugin by hitting listen fast several times, seems to be linked to curl, still investigating ...

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
