### ISSUE TITLE
ext to dep

### ISSUE THREAD

**Issue by Coirt** [sebastien-bouffier/Bidoo#57]
OS (if applicable):Win7
Version (or "dev" if compiling from source):0.6.0dev latest

```
src/OUAIVE.cpp:4:10: fatal error: ../ext/osdialog/osdialog.h: No such file or directory
 #include "../ext/osdialog/osdialog.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

I think the calls to `ext` are changed to `dep` in the latest build. Changing `ext` to `dep` in that line fixes anyway.

**Comment by phdsg** [comment]
just did a fresh pull, clean, make of rack and bidoo. not getting that error.
are you really sure everything is at "latest"?

**Comment by Coirt** [comment]
Pretty sure the Audio Interface is different in the version I just cloned and Blamsoft build2 works in it. Also get an error for AS v0.6 modules. Unless there has been an updated version since I cloned, 4 hours ago.

**Comment by phdsg** [comment]
oh damn, my bad.
looks like git didn't clean out the old directories when updating to new ones.
seems i have the headers in both places (old and new) now. bidoo probably too.
i'm gonna clean out and try again...

**Comment by Coirt** [comment]
Question for Bidoo: maybe you know though @phdsg 

Do you need to include `f` at the end of floating point numbers now? e.g. `box.size = Vec(56.0f, 56.0f);` will `box.size = Vec(56.0, 56.0);` suffice? Just starting to build my own modules for this latest version from scratch.

**Comment by sebastien-bouffier** [comment]
Hello I will check this issue with dep/ext thanks. Regarding "f", I think that without the "f" the compiler will make an implicit conversion to float since Vec takes 2 floats. It should not raise any error.

**Comment by Coirt** [comment]
Correct if wrong does that mean it converts to a double if you don't use f. float, 4 bytes double, 8 bytes.

**Comment by sebastien-bouffier** [comment]
According to my understanding 1.0 is a literal for double so `float x =1.0` will be managed by the compiler as a conversion from double to float. The compiler will have more work to achieve but I think it as no influence at run time and in fine x will have a value of 1 on 4 bytes in the binary. Once again this is my understanding .. I am not a compiler/c++ expert.

**Comment by Coirt** [comment]
Gotcha, Thanks.

**Comment by phdsg** [comment]
oh, closed already :(
just here to confirm your report.
the /ext dir was still there with all the headers, that's why i got no errors earlier.

**Comment by phdsg** [comment]
it actually also works with just `#include "osdialog.h"`.
