### ISSUE TITLE
dTr0Y Pattern issue

### ISSUE THREAD

**Issue by jsantos717** [sebastien-bouffier/Bidoo#59]
OS (if applicable): Mac OSX High Sierra 10.13.3
Version (or "dev" if compiling from source): 0.5.1

Just noticed an issue in dTr0Y. When I manually change the Pattern using the knob (Eg.: from P1 to P2), sometimes I go back to P1 and it resets all the Pitch knobs for the default stage.

However, this problem happens really occasionally and might be difficult to detect.

Thanks for all the effort and great work though.

**Comment by sebastien-bouffier** [comment]
Hello, which version of the plugin do you use please ? I have reworked the knobs updating method in the 2 last versions 0.5.23 and 0.5.24. I have just ask if someone could make a dist for 0.5.24 maybe it could solve your issue. I just tested it again under 0.6dev and I can not reproduce. I am gonna stress dTrOY more than ever and try to find what can lead to that behavior.

**Comment by jsantos717** [comment]
Hi Sebastien. 

I am currently using the version 0.5.20.

Thank you very much.

**Comment by jsantos717** [comment]
Hi.

Just a few notes on this issue that I have spotted on the last hours working with dTr0Y:

- Happens more often when switching from P2 to P1. However, happened from P3 to P2 but rarely.

- I suspect that it might be related with the reset input since I have another sequencer triggering it to restart the steps. Also, I am switching the patterns manually.

I hope this helps. :)

**Comment by sebastien-bouffier** [comment]
Hello reset id a good indication since I almost never use that feature. Thanks

**Comment by jsantos717** [comment]
No problem.

I will keep experimenting in order to help you track the issue.
