### ISSUE TITLE
[unsure/crash] segfault when typing into new 'add module' searchbox

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#6]
rack segfaults when pressing a key while 'add module' dialog is open.
i'm not even sure if this is a problem with your code or just a bug with the new
tagging/search function in the 'add module' dialog.
but it only happens when i have your modules in racks plugin directory.
maybe you can have a look at it.

**Comment by sebastien-bouffier** [comment]
huuu didn't test that I'll check

**Comment by sebastien-bouffier** [comment]
I removed my plugins from my Rack dev env and I have the same behavior that you described. Then I removed all third party folders and kept only VCV plugins .. no bug. Then I added my plugins ... no bug. Seems like it comes from another pack of plugins

**Comment by phdsg** [comment]
that's even more weird, because i did it the same way.
first i tried official only, then added one plug after another and yours were the ones.
so i guess, it's probably not a plugin problem, but the 'add module' code...
