### ISSUE TITLE
ACnE - set maximum value by center click 

### ISSUE THREAD

**Issue by 2johjoh2** [sebastien-bouffier/Bidoo#60]
Hi Sebastien,

Your Wiki mentions the possibility to set max values for ACnE by means of a center click.
Right-clicking a knob does reset the value to minimum, but the center click does not do anything ...
Am i missing something ?

OS (if applicable): OSX 10.12.6
Version (or "dev" if compiling from source): 5.1

**Comment by sebastien-bouffier** [comment]
Hello, it is working under W10, I will try to find why it is not working on OS X. Stay tuned.

**Comment by sebastien-bouffier** [comment]
Hello, I do not own a mac so it is difficult to test. According to my understanding, apple mouse management requires sometime some specific code, for example see below 
```
void mouseButtonCallback(GLFWwindow *window, int button, int action, int mods) {
#ifdef ARCH_MAC
	// Ctrl-left click --> right click
	if (button == GLFW_MOUSE_BUTTON_LEFT) {
		if (glfwGetKey(gWindow, GLFW_KEY_LEFT_CONTROL) == GLFW_PRESS || glfwGetKey(gWindow, GLFW_KEY_RIGHT_CONTROL) == GLFW_PRESS) {
			button = GLFW_MOUSE_BUTTON_RIGHT;
		}
	}
#endif
```
If I am correct Rack generates a right click with a left click + Ctrl, so mouse buttons on Mac seems to be a real subject. I did some research on the lib used by rack GLWF and I did not see any information regarding center click. I keep on searching ...

**Comment by sebastien-bouffier** [comment]
Hello dear users, do you all confirm that the middle click is not working on os x ? I ask this question because 1) I am on win/lin 2) I have read that there is a tool to configure the magic mouse 3) I made research on the lib used by Rack and found nothing about center click/os x issue ... please help.

**Comment by AScustomWorks** [comment]
is this for v0.6? tried to compile it, got this error:
```
src/BORDL.cpp:1278:27: error: no member named 'author' in 'rack::Model'
        menuLabel->text = model->author + " " + model->name;
```
And, about the magic mouse config, the default preference panel for doing it only has an option to set up a secondary click (right side). There's a third party app called MagicPrefs that allows you to setup a lot of options, included middle click... but it wreaks havoc everywhere so not really useful. Swipes work great with 2 and 3 fingers combinations, but I'm afraid that's of no use in this case.

**Comment by sebastien-bouffier** [comment]
Last push is for v0.6 dev and I think that you have this error because of that [change ](https://github.com/VCVRack/Rack/commit/0439fc405ae9d944592d341b039e051b00d62576)in Rack so a pull/make on Rack should fix the issue. Regarding the center click I understand that I should propose a key down + click for mac arch. Since GLFW_KEY_LEFT_CONTROL is already used to create the right click which key should I use ? "O" for open ? Any suggestion is welcome. Anyway thanks a lot for your help AS.

**Comment by phdsg** [comment]
is right-click + left-click an option?

**Comment by sebastien-bouffier** [comment]
what do you mean by 

> right-click + left-click

 ?  Both at the same time ? My understanding is that on mac we have only one click .. so i do not see how to manage a synchronous click with one being emulated by ctrl pressed.
Right then left click in a time window ? Meaning click + ctrl/click .. seems to be not very intuitive.
I think I missed something :)

**Comment by AScustomWorks** [comment]
Oh right, didn't noticed that change on rack.
Btw. what about using ALT + right click? 
And, right click + left click can't work, only the first click would be registered on the magic mouse.

**Comment by phdsg** [comment]
both at the same time.
was just an idea. didn't know there's only one mouse button on mac.
back in the days when 3 button mice were not that common i remember using left+right click as middle click, but that was windows too :(

**Comment by nay-seven** [comment]
> on mac we have only one click
For info , it's not true for all configs , pads have 2 clicks, and many users 2 clicks mouse ;-)

**Comment by sebastien-bouffier** [comment]
Just pushed a mod on ACnE that enables SHIFT+LEFT_CLICK for all platforms to set max value on fader. I don't know why but ALT (left Alt) was not working. Tell me if it builds on all platforms (I had to link another Rack dep library) and if you think that it is convenient.

**Comment by AScustomWorks** [comment]
Is working fine here.
btw: wouldn't be better to have this feature globally available?
I can see some users asking Andrew about the same feature later after seeing it on ACnE hehe
On the other side, if Andrew decides to use the same shortcut, yours will break, isn't it?

**Comment by sebastien-bouffier** [comment]
Yes it might break but easy to remove and let Rack framework do that.

**Comment by sebastien-bouffier** [comment]
I take time to clean my repository so I will close that thread considering that SHIFT+LEFT_CLICK is ok for mac users.
In terms of "usability", if anyone read my message, please think about making some kind of positive lobbying regarding the widget menu management in Rack .. I had a conversation with Andrew at some point and we did not manage to agree but I find not really "usable" to have to left or right click out of a menu to close it. I mean that if I right click a plugin and I realize it was not the right one, I have to left or right click outside to close the menu and then right click on the other plugin ... there is one useless click. That being said I understand it is not a high priority :)
