### ISSUE TITLE
build error with latest Rack master

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#61]
Fedora 23 Linux
Rack master (0.6.x dev)

g++ -Wsuggest-override -std=c++11 -I./src/dep/include -I./src/dep/audiofile -I./src/dep/filters -fPIC -I../../include -I../../dep/include -DSLUG=Bidoo -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/DTROY.cpp.o src/DTROY.cpp
src/DTROY.cpp: In member function ‘virtual rack::Menu* DTROYWidget::createContextMenu()’:
src/DTROY.cpp:1060:27: error: ‘struct rack::Model’ has no member named ‘manufacturer’
  menuLabel->text = model->manufacturer + " " + model->name;
                           ^
../../compile.mk:57: recipe for target 'build/src/DTROY.cpp.o' failed
make: *** [build/src/DTROY.cpp.o] Error 1

The same error occurs for BORDL.cpp.

Any suggestions for a fix ?

**Comment by phdsg** [comment]
probably related to: https://github.com/VCVRack/Rack/commit/0439fc405ae9d944592d341b039e051b00d62576

**Comment by davephillips** [comment]
@phdsg Thank you very much, that fixed the error. :)

**Comment by sebastien-bouffier** [comment]
Hello yes that's it, already fixed, I will push asap.

**Comment by sebastien-bouffier** [comment]
pushed
