### ISSUE TITLE
no member named 'author'

### ISSUE THREAD

**Issue by dBiz** [sebastien-bouffier/Bidoo#63]
OS (if applicable): WIN 10
Version (or "dev" if compiling from source): 060dev

On windows I've got a little error 

error: 'struct rack::Model' has no member named 'author'
menuLabel->text = model->author + " " + model->name;

in DTROY and BORDL ;)

**Comment by sebastien-bouffier** [comment]
Hello this is because you do not have the last version of Rack. See this [commit ](https://github.com/VCVRack/Rack/commit/0439fc405ae9d944592d341b039e051b00d62576) so a pull/make on Rack should solve your build issue.

**Comment by sebastien-bouffier** [comment]
No news, good news.
