### ISSUE TITLE
how to change dialog box color in antN

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#65]
Fedora 23 Linux
Rack master (0.6.x)

Greetings ! I'd like to change the color background for the dialog box in antN. Black on grey is not the best combination here, as you may see in the attached screenshot. 
![antnblackongrey](https://user-images.githubusercontent.com/7815938/37621859-95dee860-2b96-11e8-9ab2-5ce56ec92e3a.png)

**Comment by sebastien-bouffier** [comment]
Hello I have just pushed a mod on ANTn to make it more readable and homogeneous with the rest of the plugins. Cheers

**Comment by davephillips** [comment]
Ah, so much better for my old eyes ! Thank you again, the change is appreciated. :)

**Comment by sebastien-bouffier** [comment]
you are welcome :)
