### ISSUE TITLE
0.6 on macos: Fails to find correct version of libcurl.4

### ISSUE THREAD

**Issue by qiemem** [sebastien-bouffier/Bidoo#72]
OS (if applicable): MacOS 10.13.3
Version (or "dev" if compiling from source): 0.6.1

Just tried the new release and got a failed to load error with the following in the logs:

```
[0.009 warn] Failed to load library /Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib: dlopen(/Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib, 2): Library not loaded: /Temp/repro/Rack-0.6/plugins/Bidoo/dep/lib/libcurl.4.dylib
  Referenced from: /Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib
  Reason: Incompatible library version: plugin.dylib requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

When I `make run` the Rack repository with your 0.6.1 build, it works fine however (I have homebrew curl installed). Thus, I believe this may have to with the fact that macos applications are given a default set of environment variables when run. Seems weird, though, since it looks like you're statically compiling against it. I tried pointing Rack to the correct version of libcurl, but then ran into a similar error with another library.

When I compile Bidoo on my machine and then drop it into the release version of Rack and run from Finder, it works. Looking a little more, it doesn't look like it's actually statically compiling against the libraries:

```
▶ otool -L plugin.dylib
plugin.dylib:
	plugin.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/bryan/Development/repos/Rack/plugins/Bidoo/dep/lib/libcurl.4.dylib (compatibility version 10.0.0, current version 10.0.0)
	/Users/bryan/Development/repos/Rack/plugins/Bidoo/dep/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
```

**Comment by sebastien-bouffier** [comment]
Yes thanks for the trace I think I still have to work on my makefile and I think I will have to redesign it in such a manner that I can do something like -dynamic xxx xxx xxx -static lcurl etc...
The way I see to do that at that point is making a make file that doesn't use plugin.mk from Andrew

**Comment by sebastien-bouffier** [comment]
Dear musician/dev users I have rolled back to my previous way of linking curl for antN. After several tries I achieved to get closer to a static linking for curl but I didn't push because it was still not working. 
Btw there was something still unclear to me regarding this issue ... it was working on 0.5 in spite of not static linking. So I made the following test => rollback to my previous approach i.e. dyn link for curl and deployed my plugin on a W10 machine without any dev env installed. Under Rack 0.6 my 0.6.1 plugin works fine. I can build/link/run and play on my linux VM ... so the last thing to check is on mac os x .. If someone can build dist test on mac it would be great. 
I apologize for the delay but those lasts days have been quite complicated and I admit I could have made thing a little bit more fluid in terms of communication on FB but as you may know I am really reluctant to use that media for many good and bad reasons.

**Comment by stephanepericat** [comment]
Could it somehow be related to the new plugin SDK released with 0.6 ?
Not sure, but I can try to build for os x and let you know.

**Comment by stephanepericat** [comment]
So, i just tried to make a build on os x, but it failed with this error:

c++ -std=c++11 -stdlib=libc++ -Idep/include -I./src/dep/audiofile -I./src/dep/filters -I./src/dep/freeverb -DSLUG=Bidoo -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/dep/freeverb/allpass.cpp.o src/dep/freeverb/allpass.cpp
c++ -std=c++11 -stdlib=libc++ -Idep/include -I./src/dep/audiofile -I./src/dep/filters -I./src/dep/freeverb -DSLUG=Bidoo -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/dep/freeverb/comb.cpp.o src/dep/freeverb/comb.cpp
c++ -std=c++11 -stdlib=libc++ -Idep/include -I./src/dep/audiofile -I./src/dep/filters -I./src/dep/freeverb -DSLUG=Bidoo -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/dep/freeverb/revmodel.cpp.o src/dep/freeverb/revmodel.cpp
c++ -o plugin.dylib build/src/ACNE.cpp.o build/src/ANTN.cpp.o build/src/BAR.cpp.o build/src/BORDL.cpp.o build/src/Bidoo.cpp.o build/src/CANARD.cpp.o build/src/CHUTE.cpp.o build/src/CLACOS.cpp.o build/src/DFUZE.cpp.o build/src/DTROY.cpp.o build/src/DUKE.cpp.o build/src/FORK.cpp.o build/src/LATE.cpp.o build/src/LIMBO.cpp.o build/src/LOURDE.cpp.o build/src/MOIRE.cpp.o build/src/OUAIVE.cpp.o build/src/PERCO.cpp.o build/src/TIARE.cpp.o build/src/TOCANTE.cpp.o build/src/VOID.cpp.o build/src/ZINC.cpp.o build/src/dep/audiofile/AudioFile.cpp.o build/src/dep/pffft/pffft.c.o build/src/dep/filters/biquad.cpp.o build/src/dep/filters/smbPitchShift.cpp.o build/src/dep/freeverb/allpass.cpp.o build/src/dep/freeverb/comb.cpp.o build/src/dep/freeverb/revmodel.cpp.o dep/lib/libmpg123.a -L../../dep/lib -lglfw ../../dep/lib/libcurl.a dep/lib/libmpg123.a -shared -undefined dynamic_lookup -stdlib=libc++ -mmacosx-version-min=10.7
clang: error: no such file or directory: '../../dep/lib/libcurl.a'

**Comment by qiemem** [comment]
Alright, I was able to build ok on mac, and it looks like the dynamic link with libcurl is gone:

```
▶ otool -L plugin.dylib
plugin.dylib:
	plugin.dylib (compatibility version 0.0.0, current version 0.0.0)
	lib/libglfw.3.dylib (compatibility version 3.0.0, current version 3.3.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
```

But the dynamic link with libglfw is causing problems when I try to run via the Rack app:

```
[0.010 warn] Failed to load library /Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib: dlopen(/Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib, 2): Library not loaded: lib/libglfw.3.dylib
  Referenced from: /Users/bryan/Documents/Rack/plugins/Bidoo/plugin.dylib
  Reason: image not found
```

**Comment by sebastien-bouffier** [comment]
I made a test on my linux env and the libglfw is not required ... on W10 it is ... so I pushed an new makefile that may work on any os x version

**Comment by qiemem** [comment]
`make dist` on my mac produces a plugin.dylib without any dynamic links and works perfectly in the rack app!

**Comment by stephanepericat** [comment]
thanks @qiemem :)

**Comment by fractalgee** [comment]
excellent @qiemem! Not sure what might have been different with my ```make dist```, maybe make file was changed for the better after my last build. Anyhow, glad we finally have a working one!

**Comment by nay-seven** [comment]
Thanks a lot @qiemem !!

**Comment by blazerunner** [comment]
yes! it's workig for me too. Thanks to everybody.

**Comment by sebastien-bouffier** [comment]
I have updated the last release with @qiemem mac dist.
Thanks to all of you for your patience and efforts.
I will push a new makefile this evening with a modification regarding GLFW link but mac ans lin users are not concerned.
FYI Andrew is working on a global static linking of ext/dep libraries so my makefile will change again when 0.6.1 will be out.

**Comment by sebastien-bouffier** [comment]
@qiemem if you could make a new mac os x dist based on my last push it would be great so all dist would refer to the same commit. best.

**Comment by qiemem** [comment]
Sure thing; here you go!

[Bidoo-0.6.1-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1877438/Bidoo-0.6.1-mac.zip)

**Comment by sebastien-bouffier** [comment]
Thanks a lot!!

**Comment by Tjeerd-Schils** [comment]
@qiemem The latest dist (5 days ago) gave the same error. The one before (6 days ago) works. I'm ok, but just wanted to point it out to you and Sebastien-Bouffier. Both thanks for the work.

**Comment by Tjeerd-Schils** [comment]
@sebastien-bouffier OSX ver 10.13.1

**Comment by nicotep** [comment]
Here on 10.11.6 kind of same problem as @Tjeerd-Schils ... Though the first version of Bidoo-0.6.1-mac.zip posted by @qiemem on apr.3 did have problems (i.e. sampler didn't show any output, and some modules would not open despite being present in VCV menu).
Now with the latest zip, Bidoo doesn't even show up in the plugins menu.

**Comment by sebastien-bouffier** [comment]
I changed links in make file ... hope it will solve mac issue

**Comment by qiemem** [comment]
Here's the new build!

[Bidoo-0.6.1-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1892377/Bidoo-0.6.1-mac.zip)

**Comment by sebastien-bouffier** [comment]
thanks a lot

**Comment by sebastien-bouffier** [comment]
release updated

**Comment by Tjeerd-Schils** [comment]
Works!

**Comment by sebastien-bouffier** [comment]
great

**Comment by sebastien-bouffier** [comment]
great again :)

**Comment by sebastien-bouffier** [comment]
@qiemem  thanks a lot for your help, tests, builds ...

**Comment by qiemem** [comment]
No problem!

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
