### ISSUE TITLE
Mac OS X dist

### ISSUE THREAD

**Issue by sebastien-bouffier** [sebastien-bouffier/Bidoo#75]
Unfortunately my pack is still not compliant with Andrew's cross platform build system.
Can someone provide me with a mac os x dist for 0.6.2 version of my pack please ?

**Comment by AScustomWorks** [comment]
Here:
[Bidoo-0.6.2-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1924567/Bidoo-0.6.2-mac.zip)

**Comment by sebastien-bouffier** [comment]
Thanks a lot

**Comment by sebastien-bouffier** [comment]
I pushed a 0.6.3 release with some enhancements for dTrOY. Can someone make a mac dist please ?
Best.

**Comment by AScustomWorks** [comment]
Here:
[Bidoo-0.6.3-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1964571/Bidoo-0.6.3-mac.zip)

**Comment by sebastien-bouffier** [comment]
thanks a lot

**Comment by sebastien-bouffier** [comment]
Hello, may I ask you to make a mac build for the last release please. Best.

**Comment by AScustomWorks** [comment]
Done ;)
[Bidoo-0.6.5-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1993744/Bidoo-0.6.5-mac.zip)

**Comment by sebastien-bouffier** [comment]
thanks :)

**Comment by sebastien-bouffier** [comment]
Hello, I made changes to antN so I do not need mpg123 anymore ... maybe it means that my pack will make part of the standard build and dl stream thru Rack. If yes I won't bother you with my build requests anymore. May I ask you an ultimate build for 0.6.6 ?

**Comment by AScustomWorks** [comment]
Cool, here you go ;)

[Bidoo-0.6.6-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1998713/Bidoo-0.6.6-mac.zip)
