### ISSUE TITLE
Need help with 0.6 Rack

### ISSUE THREAD

**Issue by xyybob** [sebastien-bouffier/Bidoo#76]
OS (if applicable):Win10 (msys64)
Version (or "dev" if compiling from source):Rack 0.6 - Bidoo dev(0.62)

Successful build of Bidoo 0.62 from source and installed Rack 0.6 from install.

When I run Rack it loads all other managed plugins but cannot load Bidoo. No error messages, just quietly ignores it. Stumped! Plugin.dll and res directory copied over, all correct there. If I do 'make run' in the Rack directory, Rack runs and loads Bidoo just fine. What am I doing wrong?

**Comment by sebastien-bouffier** [comment]
Mmm strange. I would say that if you unzip the Win dist available in my last release into Documents\Rack\Plugins it should work. I made that test for the previous release but not the last one, I will do. Stay tuned.

**Comment by sebastien-bouffier** [comment]
Test done.
If you dl my last release it must work by unzipping it into Documents\Rack\Plugins. If you build your own version you have to launch `make dist` and copy the Bidoo folder under the same path.

**Comment by xyybob** [comment]
Thanks for the reply - you've illuminated my error: I was using 'Program Files/Rack/plugins/...' I must've missed the meeting. Apologies and thanks. All working now. 

Thanks for your hard work on this project - I'm not at all musical but I do love this toy!

**Comment by sebastien-bouffier** [comment]
thanks
