### ISSUE TITLE
Patch doesn't recognize dTRoY

### ISSUE THREAD

**Issue by noamguterman** [sebastien-bouffier/Bidoo#77]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.6.2

Hey Sebastian, following from the facebook post, here's the patch that doesn't recognize dTRoY.
[Strumming-Trees2.zip](https://github.com/sebastien-bouffier/Bidoo/files/1952067/Strumming-Trees2.zip)

Many thanks!

**Comment by sebastien-bouffier** [comment]
[Strumming-Trees2.zip](https://github.com/sebastien-bouffier/Bidoo/files/1952335/Strumming-Trees2.zip)
Try this one and tell me
Best

**Comment by noamguterman** [comment]
Yeah, this works. Thank you so much!




--
Noam Guterman
www.NoamGuterman.com <http://www.noamguterman.com/>
+972-54-2525-652

**Comment by sebastien-bouffier** [comment]
great
