### ISSUE TITLE
Help needed installing

### ISSUE THREAD

**Issue by carlca** [sebastien-bouffier/Bidoo#79]
OS (if applicable): macOS 10.13.4 High Sierra
Version (or "dev" if compiling from source): dev
HI Sebastien, I am new to the world of VCVRack and I am trying to install my first non-precompiled module, namely Bidoo. I couldn't see a way of downloading a binary, so I tried downloading the source. I then copied it to my `~/Documents/Rack/plugins` folder and created a new folder called `Bidoo`. I then entered that folder and typed `make` and `<enter>`. That gave me the following message:
```
Makefile:26: ../../arch.mk: No such file or directory
Makefile:44: ../../plugin.mk: No such file or directory
make: *** No rule to make target `../../plugin.mk'.  Stop.
```
What am I doing wrong?
Thanks in advance,
Carl

**Comment by sebastien-bouffier** [comment]
Hello Carl.
You have a compiled version of my pack in the release section. Last release is [here ](https://github.com/sebastien-bouffier/Bidoo/releases/tag/0.6.3).
If you want to compile it by yourself those a the big steps : 

- first make sure you have a correct dev environment for Rack, instructions are [here](https://github.com/VCVRack/Rack)
- make sure you can `make run` rack by itself
- go in Rack/plugins and clone my repo `git clone etc...` (it will create the Bidoo folder etc...)
- call `make `from /Rack/plugins/Bidoo or `make allplugins` from /Rack

**Comment by sebastien-bouffier** [comment]
Ok great
