### ISSUE TITLE
Compile fails in Mint64

### ISSUE THREAD

**Issue by asbaklm** [sebastien-bouffier/Bidoo#8]
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Bidoo.cpp.o src/Bidoo.cpp
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/OUAIVE.cpp.o src/OUAIVE.cpp
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/VOID.cpp.o src/VOID.cpp
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/MOIRE.cpp.o src/MOIRE.cpp
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/DUKE.cpp.o src/DUKE.cpp
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/CHUTE.cpp.o src/CHUTE.cpp
src/MOIRE.cpp:31:27: error: array must be initialized with a brace-enclosed initializer
  float scenes[16][16] = {0};
                           ^
../../compile.mk:53: recipe for target 'build/src/MOIRE.cpp.o' failed
make: *** [build/src/MOIRE.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by sebastien-bouffier** [comment]
Hello asbaklm
Should be fixed by last commit

**Comment by asbaklm** [comment]
Thank you very much sir
