### ISSUE TITLE
Licensing issue with AudioFile library

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#81]
Hi Sebastien,

I noticed your code uses the `AudioFile` library, which is licensed under the **GPL** license. That would require you to release your code with the same version of the **GPL** license.

I ran into the same issue and ended up using the following library for handling `wav` files, which is Public Domain: [https://mackron.github.io/dr_wav](https://mackron.github.io/dr_wav).

You might want to check the licenses of your other dependencies also.

**Comment by sebastien-bouffier** [comment]
Hi, thanks for raising this issue. I use `AudioFile` and `Gist` which are both GNU GPL. Why didn't you switch to GPL instead of moving to dr_wav ? I will read some articles regarding those licenses to understand pros and cons.

**Comment by cschol** [comment]
While I agree with the spirit of open source software and software freedom, I think the GPL is a little too restrictive. I don't want to have to change the license of my code just to use a library. I would encourage you to read up on the licenses. I decided that MIT/BSD style licenses are more suited for my own purposes.

**Comment by sebastien-bouffier** [comment]
Hello, just pushed my changes to move away from Audiofile and Gist. During my licenses journey I wondered if I would not change for WTFPL :) Now I wait to see if my pack will come back in Rack (download) one of these days ... Cheers
