### ISSUE TITLE
Issues with ext clock in both sequencers 

### ISSUE THREAD

**Issue by JTriggerFish** [sebastien-bouffier/Bidoo#85]
OS (if applicable): Mac OS 10.13
Version (or "dev" if compiling from source): dev
The ext clock in does not appear to function correctly, it makes CPU usage go up massively and results in pops and crackles and garbled output.

**Comment by sebastien-bouffier** [comment]
I changed the way the phase is calculated. Tell me if it works better.

**Comment by JTriggerFish** [comment]
Yes this fixes it, thanks a lot that was super quick !
