### ISSUE TITLE
V/Oct should last for the whole step independently of the gate length

### ISSUE THREAD

**Issue by JTriggerFish** [sebastien-bouffier/Bidoo#86]
OS (if applicable): MacOS 10.13
Version (or "dev" if compiling from source): dev

When using the dTroy sequencer, the V/Oct output should not change until the beginning of the next step, irrespectively of the gate length.
Currently it lasts the same time as the gate which is not correct as the pitch will be wrong during the release time of ADSR envelopes triggered by the gate.

**Comment by sebastien-bouffier** [comment]
take a look at the right click menu => pitch continuous, maybe it should be the default behavior

**Comment by JTriggerFish** [comment]
Ah I see, thanks.
