### ISSUE TITLE
Root note in dTroY doesn't scale correctly to V/Oct ?

### ISSUE THREAD

**Issue by JTriggerFish** [sebastien-bouffier/Bidoo#87]
OS (if applicable): MacOS 10.13
Version (or "dev" if compiling from source): dev

I assumed root note could be used to transpose a sequence by feeding it v/oct but it doesn't seem to be the case, is it missing an exponential converter ?

**Comment by JTriggerFish** [comment]
Actually exponential conversion has probably nothing to do with it as the v/Oct scale is still linear and additive before being passed to VCOs where it’s exponentiated, sorry I wrote this a bit late yesterday.
Still there is something off there.

**Comment by sebastien-bouffier** [comment]
Hi, I agree with both :) no exp issue but quantization issue. Thanks for raising that bug. I do not use that feature so I was not aware of it. I am gonna take a look at that soon. Stay tuned.

**Comment by sebastien-bouffier** [comment]
Just pushed a modification of quantization method. No more options for quantize (full/cycle) but seems to work fine. Tell me. If it is okay I will do the same it on bordL.

**Comment by JTriggerFish** [comment]
Thanks! It seems more responsive but I think the scaling is still off, I tried plugging in the octave Fundamental module to the root input and instead of adding an octave each button seems to be adding about a semitone ?

**Comment by sebastien-bouffier** [comment]
According to my understanding Octave (that I discover) adds or removes n times 1V to the input depending on which level you select. In dTrOY the Root control has 12 values (10V/12) so let's say you choose C as Root, if you add 1V via the Root input you will step up of a semi tone. To test the scaling of the parameters I used a Befaco atenuverter which is able to generate -10V to -10V and the behavior of dTrOY seemed correct to me. Pay attention to the Sensitivity control on top of the pitch knobs on the top right corner, its value is applied to the voltage control of the pitch knobs before entering quantization.

I think that the "standard" way of using Octave it to send V/Oct output from dTrOY in Octave's input and then Octave output to your oscillator.

**Comment by JTriggerFish** [comment]
Ok I see, I didn't expect root to work this way but this makes sense.
Indeed I can also achieve what I want by just adding the output of dTrOY to another CV signal so this is not a big deal.
Thanks for the great plugins and the quick responses !

**Comment by sebastien-bouffier** [comment]
out of curiosity what did you expect from Root param ? I recognize that it is maybe misleading i should write Key on the UI ...

**Comment by JTriggerFish** [comment]
I was expecting it to transpose the whole sequence by adding an offset to the v/oct

**Comment by sebastien-bouffier** [comment]
ok, that's what it does but for a range of 12 semi tones (key selection) if you want to go ahead you have to move pitch knobs .... I was thinking about adding 4 small knobs somewhere on the UI to shift the patterns up, down, left and right that and a kind of transpose input should the trick. Thanks for using/testing/raising ... have fun

**Comment by JTriggerFish** [comment]
You're welcome. Yes I think the only issue is that a range of 12 semi tones per 10v is not something that is produced naturally by many modules so it could be a bit fiddly to use in practice ?

**Comment by sebastien-bouffier** [comment]
just added transpose input + copy/paste on the UI + shitfs

**Comment by JTriggerFish** [comment]
That’s awesome, thank you !
Will you update the official package with all the recent improvements ?

**Comment by sebastien-bouffier** [comment]
You are welcome. Yes I will update in one day or two. I have to update bordL which is dTrOY++ and do a lot of testing :)

**Comment by JTriggerFish** [comment]
I will delete this message later as it is off topic ( not sure how else to contact you ), but I just uploaded my first set of modules https://github.com/JTriggerFish/TriggerFish-VCV
If you have some time to give them a go at some point and some feedback it would be awesome !
I will get them added to the community repository later today.

**Comment by sebastien-bouffier** [comment]
hello, just cloned your repo and tested quickly your plugins.
slop is really grea, VCA i think i did not test it correctly because i have clicks on attack and release so maybe it is designed to be used with another VCA ..? VDPO is really interesting but yes as you write in your home page it is CPU intensive :) you can let your message here no pb if you want to contact me even faster use sebastien.bouffier@gmail.com best.
