### ISSUE TITLE
μ synced pulse generator: how to properly use it?

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#88]
Hey Sebastien,
I played around with the `μ synced pulse generator` and I am confused as to how it works:

- What does the `BPM` setting do when I patch in a clock into the `Step Start` input?
- How to the `Triggers` work? `Trigs count` seems to have no effect.
- How do you properly chain modules to build a sequence?

Could you provide a sample patch or a tutorial video explaining how to set up a sequence from scratch? This seems like an incredibly useful module to build complex sequences, but after watching the test video provided, and reading the explanation in the manual, I am still confused...

Thank you!

**Comment by sebastien-bouffier** [comment]
Hi, i have uploaded a patch using mu. Hope it will help. Best.
[https://patchstorage.com/mu-for-cschol/](https://patchstorage.com/mu-for-cschol/)

**Comment by cschol** [comment]
Ha! Now I get it. Thank you!
