### ISSUE TITLE
Error: Array must be initialized with a brace-enclosed initializer

### ISSUE THREAD

**Issue by Cordoha** [sebastien-bouffier/Bidoo#9]
Awesome plugins by the way! Error in last attempt to build: 

src/MOIRE.cpp:31:27: error: array must be initialized with a brace-enclosed initializer
  float scenes[16][16] = {0};
                           ^
../../compile.mk:53: recipe for target 'build/src/MOIRE.cpp.o' failed
make: *** [build/src/MOIRE.cpp.o] Error 1

**Comment by sebastien-bouffier** [comment]
Hello Cordoha, can you test a build please ? Should be fixed.

**Comment by Cordoha** [comment]
Just built it with your fixes. Thanks.
