### ISSUE TITLE
build fail latest pull

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#90]
Linux Fedora 23
Rack 0.6.2c

Greetings ! I've run into a problem here. Any suggestions for a fix ?

g++ -Wsuggest-override -std=c++11 -Idep/include -I./src/dep/dr_wav -I./src/dep/filters -I./src/dep/freeverb -I./src/dep/gverb/include -I./src/dep/minimp3 -I./src/dep/lodepng -I./src/dep/pffft -DSLUG=Bidoo -fPIC -I../../include -I../../dep/include -DVERSION=0.6.21 -MMD -MP -g -O3 -march=athlon-fx -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/LIMONADE.cpp.o src/LIMONADE.cpp
src/LIMONADE.cpp: In constructor ‘LIMONADEWidget::LIMONADEWidget(LIMONADE*)’:
src/LIMONADE.cpp:832:15: error: cannot convert ‘LIMONADE::loadSample’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->loadSample;
               ^
src/LIMONADE.cpp:840:15: error: cannot convert ‘LIMONADE::loadPNG’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->loadPNG;
               ^
src/LIMONADE.cpp:848:15: error: cannot convert ‘LIMONADE::loadFrame’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->loadFrame;
               ^
src/LIMONADE.cpp:856:15: error: cannot convert ‘LIMONADE::morphWavetable’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->morphWavetable;
               ^
src/LIMONADE.cpp:864:15: error: cannot convert ‘LIMONADE::morphSpectrum’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->morphSpectrum;
               ^
src/LIMONADE.cpp:872:15: error: cannot convert ‘LIMONADE::morphSpectrumConstantPhase’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->morphSpectrumConstantPhase;
               ^
src/LIMONADE.cpp:880:15: error: cannot convert ‘LIMONADE::deleteMorphing’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->deleteMorphing;
               ^
src/LIMONADE.cpp:888:15: error: cannot convert ‘LIMONADE::normalizeAllFrames’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->normalizeAllFrames;
               ^
src/LIMONADE.cpp:896:15: error: cannot convert ‘LIMONADE::normalizeWt’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->normalizeWt;
               ^
src/LIMONADE.cpp:904:15: error: cannot convert ‘LIMONADE::normalizeFrame’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->normalizeFrame;
               ^
src/LIMONADE.cpp:912:15: error: cannot convert ‘LIMONADE::removeDCOffset’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->removeDCOffset;
               ^
src/LIMONADE.cpp:920:15: error: cannot convert ‘LIMONADE::windowWt’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->windowWt;
               ^
src/LIMONADE.cpp:928:15: error: cannot convert ‘LIMONADE::smoothWt’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->smoothWt;
               ^
src/LIMONADE.cpp:936:15: error: cannot convert ‘LIMONADE::addFrame’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->addFrame;
               ^
src/LIMONADE.cpp:944:15: error: cannot convert ‘LIMONADE::deleteFrame’ from type ‘void (LIMONADE::)()’ to type ‘void (LIMONADE::*)()’
   btn->fncPtr = module->deleteFrame;
               ^
../../compile.mk:64: recipe for target 'build/src/LIMONADE.cpp.o' failed
make: *** [build/src/LIMONADE.cpp.o] Error 1

**Comment by sebastien-bouffier** [comment]
Hello, looks like function pointers don't pass under Linux ... I will take a look at that

**Comment by sebastien-bouffier** [comment]
I moved away from function pointers (Cish) to use polymorphism (C++ish).
I can build under linux with my VM now.
That being said I cannot test with my VM because Rack is not working properly (VM+Linux install issues maybe)

I will publish the command list of LIMONADE on the readme of my repository you should be able to test it.

**Comment by sebastien-bouffier** [comment]
I pushed a new version without any mutex => less CPU usage.
http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing
