### ISSUE TITLE
bordL is out of tune?

### ISSUE THREAD

**Issue by Skrylar** [sebastien-bouffier/Bidoo#92]
OS (if applicable): Linux
Version (or "dev" if compiling from source): (latest in plugin manager)

bordL appears to have note displays on top of the sequencer, but they do not actually match the 1V/O they represent. This can be noticed by plugging the 1V/O in to an EvenVCO, both initialized to default values, and the C4 played from bordL is *significantly higher* than the C4 played from MIDI IN.

![screenshot from 2019-01-27 06-20-56](https://user-images.githubusercontent.com/325950/51800884-120fa080-21fc-11e9-8b69-c797d99740e0.png)

C4 is actually **0V** in Rack.

**Comment by sebastien-bouffier** [comment]
@Skrylar Hi, I think it is fixed in commit 0.6.25.
Do you confirm ?

**Comment by Petervos2018** [comment]
> @Skrylar Hi, I think it is fixed in commit 0.6.25.
> Do you confirm ?

The read out is correct now for c7 c4 but the v/oct is way off, old project using 0.6.24 does not sound right. Leave it the way it was and people can use an octave module to get the lower/higher octave.
Or just add 4 to the octave **readout**  and do nothing else. 

Greeting Peter.

**Comment by sebastien-bouffier** [comment]
@Petervos2018 
Hello. 
Sorry I don't understand 

> but the v/oct is way off

I sequence a VCO1 of Fundamentals with bordL. I send the audio out from the VCO1 to a GRAN TUNISMO from NYSTHI and the V/O out from bordL to a SCOPE from Fundamentals.
When C4 is played I see a C4 on the tuner and 0V on the scope. C5 => 1V etc...

Old projects made with previous version of bordL won't sound right because of the V/O calibration that has been changed.

Do you mean that C10 is too low as max value ? Should I let V/O going from -10V to +10V ?

**Comment by Petervos2018** [comment]
I'm not a programmer, I make music.
The only thing wrong with the OLD BordL was the read out ! it said C3 but it was a C7.
The range on the old BordL was C0 to C10   I guess 0V/+10V.
Only thing is in Rack 0V=C4.
So my suggestion is JUST ADD 4 TO THE READOUT.
So C0 becomes C4,  C4 becomes C7 etc.
**### Don't change the V/O calibration** because it will mess up old projects.<- this is what I meant when I said "v/oct is way off", because you changed the calibration !

Greetings Peter

**Comment by Petervos2018** [comment]
> 
> Old projects made with previous version of bordL won't sound right because of the V/O calibration that has been changed.
> 
UNDO the calibration.

> Do you mean that C10 is too low as max value ? Should I let V/O going from -10V to +10V ?

No, leave it as it was , just add 4 to the read out and you are done.

Greetings Peter

**Comment by sebastien-bouffier** [comment]
Hi Peter,
I tried to summarize changes between both versions
![image](https://user-images.githubusercontent.com/1842599/52593204-a7d83c00-2e48-11e9-9abe-55549d1f3976.png)
So, it seems to me that the last version is good. Now C4 is 0V and so on.
I made a test side by side with PhraseSeq from Impromptu and I see the same voltage.
On old projects you should only have to add 4V after bordL's V/O output to offset the new calibration.
Anyway I can make two versions of bordL :)
Thanks for your interest in my toys.

**Comment by Petervos2018** [comment]
Hi Sebastien, you are right on all accounts !
But I stumbled on something strange by accident.
The file I was testing it with had cv going to the KEY input of BordL !

On version 24 this went/stepped 1 semitone at a time now its detuning from 0% to 99% then going to the next note. So all the notes were detuned horribly ! (remember I said they were way off... I was right ! )

This made me think you changed something more than just shifting the voltages.
Thanks for taking the time to explain what you did to me and you are right it works flawless !

No you don't have to make 2 versions of BordL maybe change the KEY back to one semitone steps ?

Greeting Peter

**Comment by sebastien-bouffier** [comment]
Yep I will take a look at the KEY control.
Best, Seb.

**Comment by Skrylar** [comment]
> Or just add 4 to the octave ****readout**** and do nothing else. So the
> readout goes from C4, knob all the way to the left, to C14 all the way
> to the right.

I don't think a sequencer locked to the range of C4-C14 is all that
good of an idea. One can argue that C-1 to C1 is often relegated to
control codes more than music but C2 and C3 certainly do appear in
some tracks.


<a id="org5e8a4ea"></a>

# Stateful stop-gap

This option is to add some kind of context menu flag, which acts as a
compatability toggle.

1.  It defaults to **off**.
2.  `fromJson` is adapted to see if the setting is flipped or not; if
    it can't find an answer, turn it on. Otherwise load whatever is set.

This allows the correct behavior where the parameters are tuned
(ex. their min and max can be adjusted) as they should be. It also
involves adding a semi-permanent menu item and compatibility code
(icky but it works.)


<a id="org79f315e"></a>

# Stateless stop-gap

1.  Revert the CV scaling to its previous state,
2.  Change the parameter minimum so it can reach C0 (would probably be
    a negative value,)
3.  Change the default to the "new" C4,
4.  Add the +4 to the note display,

This does mean the parameters are still off (you'd notice using
`Hovered Value` and `Inject Value` modules) but:

-   Old patches will work untouched, and,
-   You won't notice if you're just eyeballing the knobs.

**Comment by Petervos2018** [comment]
@Skrylar 
As a small part of this post is quoting me I feel the need to react.
I think Sebastien already solved the "problem" to both of our needs in version 25.
The readout is correct, old patches work, even the `Hovered Value` work.
Only reason I got involved in this is, I thought he did it the "wrong" way, which he DID NOT !
As soon as he fixes the KEY control we will all be happy ;)

Greetings Peter

**Comment by sebastien-bouffier** [comment]
Hello, I made a push with a fix for the KEY input. I hope that all of you will be happy with this version :)
Best, Seb.

**Comment by Petervos2018** [comment]
We are very happy now ;)

**Comment by sebastien-bouffier** [comment]
Great :)

**Comment by Petervos2018** [comment]
Some bad news,
the shiftbuttons left and right and up work as they should.
The down button works but when you want to go lower than C4 it does not do what you want.
It slowly makes all the steps C4... try it you see what I mean...
Greetings Peter.

**Comment by sebastien-bouffier** [comment]
I will take a look.
Best Seb

**Comment by sebastien-bouffier** [comment]
Hello, just pushed a fix that allows to move pitch between C0 and C10. When a note reaches C0 or C10 you can not move the pattern in that direction in order to preserve the intervals between the steps.
