### ISSUE TITLE
V1 ?

### ISSUE THREAD

**Issue by Eurikon** [sebastien-bouffier/Bidoo#95]
will these be updated/migrated to Rack V1?

**Comment by sebastien-bouffier** [comment]
hello Eurikon, yes I am working on it.

**Comment by nay-seven** [comment]
Super ! ;-)

**Comment by Eurikon** [comment]
thanks Sebastien!

**Comment by Coirt** [comment]
@sebastien-bouffier If you need any help with migration I'd be more than willing. Just let me know what you need done.

**Comment by sebastien-bouffier** [comment]
Hi Phil, sorry to respond late. Yes, if you want to migrate one or more plugins or if you want to take a look @ simd optimizations ... that is more than ok :) ... tell me. I will create a v1 branch with some of them already migrated (or almost).

**Comment by Coirt** [comment]
Not too sure of how to implement simd have not used it in my modules yet. Yeah sounds good I can work from the bottom of the list upwards.

**Comment by Coirt** [comment]
Actually as well as working up from the bottom a better way to track would be to put all the plugins in the manifest you can use `"disabled": true` and comment out those modules in the `.hpp/.cpp` and I'll place `"description":  "...\nPG\n"` in the manifest for whichever one I'm working on, which can be removed once everything is done. Which ever you have done I'll place your initials in to track.

**Comment by sebastien-bouffier** [comment]
Ok. I will add all .cpp and update the json so you will be able to pick plugins within the list.

**Comment by Coirt** [comment]
Grand! What commit of Rack are you on? 

I'm going to update to the latest and start with CLACOS

**Comment by sebastien-bouffier** [comment]
bidoo Modules are available for V1

**Comment by sebastien-bouffier** [comment]
Hi, can someone check if cANARd crashes when saving sample under OS X ? #107 and provide me with a gdb report please ?

**Comment by nay-seven** [comment]
mac book pro Yosemite and  Mac mini 2012 El capitan here , test ok

**Comment by sebastien-bouffier** [comment]
ok thanks a lot .... it works fine under W10 too .... I don't know where it does come from ....
